### ISSUE TITLE
Problem passing simulator noise configuration

### ISSUE THREAD

**Issue by awcross1** [Qiskit/qiskit-terra#630] opened 2018-07-06 16:23 UTC
### Informations

Say I pass a configuration like this into QISKit, i.e. `qiskit.execute(circuit, 'local_qasm_simulator', shots=shots, config=simulator_config)`:

```python
simulator_config = {
    "noise_params": {
    "readout_error": 0.01,
    "X90": {
        "p_depol": 0.01
    },
    "CX": {
        "p_depol": 0.01
    }
    },
    "data": { "classical_state", "hide_counts" }
}
```

The C++ QASM simulator understands what these parameters mean, but QISKit doesn't successfully encode the "data" field. 

- **QISKit (Python SDK) version**: master
- **Python version**: 3.6
- **Operating system**: Mac

### What is the current behavior?

An exception is raised in the JSON encoder.

### Steps to reproduce the problem

Pass in the configuration above in a call to execute the C++ simulator.

### What is the expected behavior?

The call to execute simulates a quantum circuit with noise and returns a classical bit string for each shot (accessible by a call to get_data on the result object).

### Suggested solutions

As a workaround, I added these two lines to the default method of QASMSimulatorEncoder in the Python backend code for the C++ simulator:

```python
if isinstance(obj, set):
    return list(obj)
```

This seems to fix the problem.

**Comment by delapuente** [comment] 2018-08-01 10:08
@awcross1 can you paste the exception you observe, please? Your solution seems correct, I would love to see it in context? Why don't you try opening a pull request?

**Comment by ajavadia** [comment] 2018-10-07 19:44
@awcross1 Your example works if you pass the data as a list not a set. 
```python
simulator_config = {
    "noise_params": {
    "readout_error": 0.01,
    "X90": {
        "p_depol": 0.01
    },
    "CX": {
        "p_depol": 0.01
    }
    },
    "data": [ "classical_state", "hide_counts" ]   # list instead of set
}
```
And in fact the[ documentation for the simulator says this should be list, not set](https://github.com/Qiskit/qiskit-terra/tree/master/src/qasm-simulator-cpp#table-of-config-options).

So unless there's a reason you would want to pass your config as set, I think this is expected behavior (not a bug).

**Comment by delapuente** [comment] 2018-10-08 11:00
Closing this issue, feel free to reopen if you feel it is not solved.

**Closed by delapuente** 2018-10-08 11:00 UTC
Labels: good first issue
