### ISSUE TITLE
MPL drawer CU1 gate is inconsistent with other drawers

### ISSUE THREAD

**Issue by sumitpuri** [Qiskit/qiskit-terra#3684] opened 2020-01-05 22:53 UTC
### Information

- **Qiskit Terra version**: 0.11.0
- **Python version**: 3.7
- **Operating system**: Mac OS 10.15.1

### What is the current behavior?
```
circuit = QuantumCircuit(2)
theta = numpy.pi/2
circuit.cu1(theta,0,1)
circuit.draw()
```
Output-
```            
q_0: |0>─■─────
         │pi/2 
q_1: |0>─■─────
```
However, mpl shows fine-
![image](https://user-images.githubusercontent.com/6925028/71787125-8a204200-2fd9-11ea-9a9a-2826e2fafbf4.png)

### Steps to reproduce the problem
Paste the above code in Jupyter notebook and run.

### What is the expected behavior?
The text drawer should show up like this-
```            
q_0: |0>─────■──────
        ┌────┴─────┐
q_1: |0>┤ U1(pi/2) ├
        └──────────┘
```

### Suggested solutions

Fix is provided below in the PR by making changes in qiskit/visualization/text.py

**Comment by ajavadia** [comment] 2020-01-07 05:24
Thanks for bringing up the inconsistency. This was supposed to have been fixed via https://github.com/Qiskit/qiskit-terra/issues/1957. Seems like a regression.

However note that the text drawer is correct here. CU1 is a symmetric gate and thus a typical notation to signify this is to draw control/target the same. So mpl drawer should be fixed.

**Comment by sumitpuri** [comment] 2020-01-07 13:56
Got it, I will fix the MPL Drawer.

**Comment by sumitpuri** [comment] 2020-01-09 12:22
@ajavadia Does this look right?

Also, I am already working on a different bug and have a PR open. Whenever I push my changes for this bug, the changes get tied to that already opened PR. How can I push so that it creates a new PR related to this bug?

![image](https://user-images.githubusercontent.com/6925028/72067335-123b6b80-32a8-11ea-9c9b-35dd94178826.png)

**Comment by 1ucian0** [comment] 2020-01-11 02:37
The results looks correct!

About the git issue, I think the problem is that you have to put different fixes in different branches (all from master). You can create different PRs from them.

**Closed** 2020-02-20 15:37 UTC
Labels: bug, priority: medium
