### ISSUE TITLE
qpy serialization loses tranpilation layout information

### ISSUE THREAD

**Issue by ankit27kh** [Qiskit/qiskit-terra#10203] opened 2023-06-05 10:57 UTC
### Environment

- **Qiskit Terra version**: 0.24.0
- **Python version**: 3.10.10
- **Operating system**: Ubuntu 22.04.02 LTS

### What is happening?

`TranspileLayout` of a transpiled circuit is not saved after `qpy` serialization.

### How can we reproduce the issue?

```
c2 = transpile(c1, backend=backend)

with open(f'temp.qpy', 'wb') as f:
    qpy.dump([c1, c2], f)

with open(f'temp.qpy', 'rb') as f:
    c3, c4 = qpy.load(f)

print(c2.layout)
print(c4.layout)
```

### What should happen?

```
print(c2.layout)
print(c4.layout)
```
both should give the same output

**Comment by jakelishman** [comment] 2023-06-05 11:37
Thanks for the report - this is a duplicate of #10112.

**Closed by jakelishman** 2023-06-05 11:37 UTC
Labels: bug
