### ISSUE TITLE
Add a new QuantumCircuit constructor QuantumCircuit.from_instructions

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#8709] opened 2022-09-08 15:26 UTC
### What should we add?

Creating a QuantumCircuit and appending operations into it is a very common pattern. It would be very convenient to be able to create a QuantumCircuit by directly passing an iterator of operations, something like:
```python
@staticmethod
def from_ops(ops: Iterator[tuple[Instruction, Sequence[Qubit], Sequence[Clbit]]]) -> QuantumCircuit:
    circuit = QuantumCircuit()
    for op in ops:
        circuit.append(*ops)
    return circuit
```
Currently this is not possible as written but it would be if my proposal https://github.com/Qiskit/qiskit-terra/issues/8707 were implemented.

**Comment by jakelishman** [comment] 2022-09-08 15:42
(Just to add: the iterable should probably be of `CircuitInstruction`, not the legacy 3-tuple, since this is a new method with no backwards-compatibility concerns, but otherwise I'm fine with it.)

**Comment by kevinsung** [comment] 2022-09-08 18:11
>We can do this without https://github.com/Qiskit/qiskit-terra/issues/8707

@jakelishman so how should this be done? would you just do `circuit.add_bits(set(qubits) - set(circuit.qubits))` before every append?

**Comment by jakelishman** [comment] 2022-09-08 18:35
Yeah, exactly.  It'd probably be good to do a shade more book-keeping just for efficiency and reproducibility reasons (ensure that bits get added in the order they appear in the operand sequences, make sure condition bits and cregs are respected, and track the sets of what we've already appended internally to avoid recalculation), but those are just minor implementation details.

Similarly, you probably want your constructor to accept `name`, `global_phase` and `metadata` fields like the main constructor.  If you'd like to write a PR to do it, I imagine we can get it merged into 0.22 if you've got time this or next week?

**Comment by kevinsung** [comment] 2022-09-08 18:47
I'm not sure I'll have time, so don't let this block 0.22. Why does `Circuit.qubits` need to be ordered? For this specific purpose it would be better for it to be unordered.

**Comment by jakelishman** [comment] 2022-09-08 18:52
It's not absolutely critical, it was just on my mind because we occasionally have issues testing the circuits produced with the control-flow builder interfaces because they have a non-deterministic ordering (admittedly limited to the arguments of the blocks) - hence the recent #8627.  I think you're probably right that it's not an issue here.

That's fine if you've not got time, no worries.  We can mark it as a "help wanted" - I think it's a good issue for someone in the community to take on.

**Comment by jakelishman** [comment] 2022-09-08 18:59
For a community member wanting to have a go at this, the rough interface would look like
```python
class QuantumCircuit
    @classmethod
    def from_instructions(cls, instructions: Iterable[CircuitInstruction], *, name=None, metadata=None, global_phase=None):
        out = cls(name=name, metadata=metadata, global_phase=global_phase)
        # ...
```
`CircuitInstruction` always contains only `Qubit` and `Clbit` instances, so we'd need to track the bits used in a set, and append them to the circuit before appending the instruction if they're not already there.  We'd also need to take care to ensure that any bits or registers that appear in the `condition` field of an `Instruction` instance are added as well.  For control-flow instructions, the method would need to inspect the `blocks` field (which contains `QuantumCircuit` instances, and ensure any registers in there are also in the top-level circuit.

**Comment by kevinsung** [comment] 2022-09-08 19:10
@jakelishman I meant to ask about the `Circuit.qubits` attribute. It already exists, and it is a `list` and not a `set`. Why is that? Can  we make it a `set` instead?

**Comment by jakelishman** [comment] 2022-09-08 19:13
It's important for it to be a sequence, because it defines the order that bits are applied to it when a circuit is used as an `Instruction` definition, for example - we associate `CircuitInstruction.qubits` with the `QuantumCircuit.qubits` by equal indices in the sequence.  We do actually have the set view already, it's just a private attribute - it's `QuantumCircuit._qubit_indices`, which is a dict.

**Comment by BramDo** [comment] 2022-09-12 18:59
@jakelishman @kevinsung I used the proposed interface for the instruction to circuit class. It has now a fixed 2 qubit size.

```
    @classmethod
    def from_instructions(cls, instructions: Iterable[CircuitInstruction], *, name=None, metadata=None, global_phase=0):
        out = cls(name=name, metadata=metadata, global_phase=global_phase)
        qc = QuantumCircuit(2,2)
        for instruction in instructions:
            qc._append(instruction)
        return qc
```

I tested this function with CircuitInstructions, but these instructions are a bit long for a user. So I should make a more user friendly interface and use add.qubit function?
```
def instructions_bell_circuit():
    instructions_list = []
    instruct_1 = CircuitInstruction(operation=Instruction(name='h', num_qubits=1, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0),), clbits=())
    instruct_2 = CircuitInstruction(operation=Instruction(name='cx', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
    instructions_list.append(instruct_1)
    instructions_list.append(instruct_2)
    return instructions_list
    
circuit = circuit.from_instructions(instructions_bell_circuit())
```

**Comment by kevinsung** [comment] 2022-10-17 01:46
I'll take over this issue, please assign me.

**Closed** 2022-10-28 21:29 UTC
Labels: type: feature request, help wanted
