### ISSUE TITLE
[RFC] Sorted histogram data

### ISSUE THREAD

**Issue by eendebakpt** [Qiskit/qiskit-terra#6684] opened 2021-07-06 08:31 UTC
### What is the expected enhancement?

The output of `Result.get_counts` is a dictionary with no particular order of the keys (although that depends a bit on the type of `Result`). For example the output of a GHZ state simulation is:
```
In [52]: counts = result.get_counts()
    ...: print(counts)
{'1111': 3741, '0110': 36, '1000': 47, '0000': 3772, '0001': 41, '1001': 38, 
'1101': 80, '0111': 40, '0010': 84, '1011': 46, '0100': 36, '1110': 33, '1100':
2, '1010': 2, '0011': 2}
```
A better representation would be to sort the keys. Either according to the key, or according to the value:
```
In [3]: counts = {k: counts[k] for k in sorted(counts.keys())}
   ...: print(counts)
{'0000': 3772, '0001': 41, '0010': 84, '0011': 2, '0100': 36, '0110': 36, '0111': 40, '1000': 47, '1001': 38, '1010': 2, '1011': 46, '1100': 2, '1101': 80, '1110': 33, '1111': 3741}
```
Sorted according to value
```
In [5]: counts = {k: v for k, v in sorted(counts.items(), key=lambda item: -item[1])}
   ...: print(counts)
{'0000': 3772, '1111': 3741, '0010': 84, '1101': 80, '1000': 47, '1011': 46, '0001': 41, '0111': 40, '1001': 38, '0100': 36, '0110': 36, '1110': 33, '0011': 2, '1010': 2, '1100': 2}
```

Some questions: 

* Would it make sense to sort the histogram result by default?
* If so, what is the preferred sorting order. 

The `Statevector` method `sample_counts` returns a dict sorted on the key value. For that reason I would sort according to the key value.
```
In [12]: import numpy as np
    ...: from qiskit.quantum_info import Statevector
    ...: 
    ...: d=np.array([.5, .1, .2, .4])
    ...: s=Statevector(d/np.linalg.norm(d))
    ...: s.sample_counts(4000)
Out[12]: {'00': 2188, '01': 60, '10': 356, '11': 1396}
```

**Comment by Rajan117** [comment] 2021-07-06 09:55
I am a newcomer and recently got into learning QisKit. I would like to attempt fixing this.

**Comment by eendebakpt** [comment] 2021-07-06 11:17
@Rajan117 That would be nice! 

It might be as easy as adding the line at the end of the `get_counts` method of the `Result` class. Another option would be to do the sorted earlier in in processing, but that might be more complex.

**Comment by Rajan117** [comment] 2021-07-07 08:03
I will take a crack at it and see what I can do :) @eendebakpt

**Comment by Rajan117** [comment] 2021-07-07 08:49
Well I am struggling to even get a workable environment setup. When I do 'pip install -e .' in the environment I get this error
![image](https://user-images.githubusercontent.com/77441871/124729530-6c060b80-df08-11eb-9ec7-cf8a4b700283.png). I tried manually setting the owner of that file to my user but it did not work. For reference I am following this official QisKit guide. https://www.youtube.com/watch?v=QjZdvNgYl3s&list=PLOFEBzvs-Vvp2xg9-POLJhQwtVktlYGbY&index=7

**Comment by eendebakpt** [comment] 2021-07-07 09:35
@Rajan117 This error is not related to qiskit. It looks like a problem in your python environment. Can you create a virtual environment to work in? Google for `virtualenv`/`venv`  and have a look at https://docs.python.org/3/library/venv.html

**Comment by Rajan117** [comment] 2021-07-09 07:59
Thank you, I think I am all good now. I tried again today and got no errors (though I will be sure to tread lightly).

**Comment by Rajan117** [comment] 2021-07-09 08:11
@eendebakpt What is the easiest way to recreate your output?

**Comment by eendebakpt** [comment] 2021-07-11 19:09
@Rajan117 A minimal example is:
```
from qiskit import QuantumCircuit
from qiskit.providers.aer import AerSimulator
from qiskit.providers.aer.noise import NoiseModel
from qiskit.providers.aer.noise import pauli_error

p=.1
noise=NoiseModel()
error_gate1 = pauli_error([('X', p), ('I', 1 - p)])
error_gate2 = error_gate1.tensor(error_gate1)
noise.add_all_qubit_quantum_error(error_gate1, ["u1", "u2", "u3"])
noise.add_all_qubit_quantum_error(error_gate2, ["cx"])
    
circ = QuantumCircuit(3)
circ.h(0)
circ.cx(0, 1)
circ.h(2)
circ.measure_all()

simulator = AerSimulator(noise_model=noise)
counts = simulator.run(circ, shots=2000).result().get_counts(circ)
print(counts)
```

**Comment by Rajan117** [comment] 2021-07-12 14:39
Alright, found the Result class and the method. Could not find the 'sample_counts' method in the Statevector class. Where can I find it as I am probably looking in the wrong place. My initial thought to fix this is to just reuse the implementation in the method to keep consistency.

**Comment by Rajan117** [comment] 2021-07-12 15:30
Not sure I can do it in one line. What data type is the key? It seems to be binary but is in quotes?

**Comment by peendebak** [comment] 2021-07-12 15:38
The data type is `str` in the example, but that should not really matter. You can just sort it using the normal python sorting (see the example code on top of the issue)

**Comment by Rajan117** [comment] 2021-07-13 08:41
I may have found an issue. I was editing the code for the return statement that occurs for a dictionary with size greater than 1. But the function returns at the point for a dictionary of size 1.
![image](https://user-images.githubusercontent.com/77441871/125420417-8e51bf20-596a-4d42-8d6a-41027a2af254.png)
![image](https://user-images.githubusercontent.com/77441871/125420450-0fc7c101-73ba-4aa7-8412-f2e6cdc58b0c.png)

**Comment by Rajan117** [comment] 2021-07-13 08:43
@peendebak I tried that but got an AttributeError: 'list' object has no attribute 'keys'. I think I need to reword it for dictionaries.

**Comment by Rajan117** [comment] 2021-07-13 08:49
My bad I misunderstood the code, it is actually outputs of a list of dictionaries also.

**Comment by Rajan117** [comment] 2021-07-13 10:08
I think I may have done it.
![image](https://user-images.githubusercontent.com/77441871/125433832-f30e42e3-d815-4e92-80ec-b301fcfbf9c7.png)
![image](https://user-images.githubusercontent.com/77441871/125433942-8e41aeed-e757-4e41-9b46-a54d80d25b52.png)

**Comment by Rajan117** [comment] 2021-07-13 10:09
The whole time I overlooked how dict_list[0] is a dictionary, so all I needed to do was add '[0]'.

**Comment by Rajan117** [comment] 2021-07-13 10:18
![image](https://user-images.githubusercontent.com/77441871/125434946-f85baefe-3925-4f34-9a2f-0e5a0eae33dd.png)
How do I test my code? The QisKit YouTube tutorial does this but for me I get an error throw. What may I have missed?

**Comment by eendebakpt** [comment] 2021-07-14 19:36
@Rajan117 What do you mean by test? Locally you can run the qiskit tests from the command line with the command `tox -epy37`. If you make a PR tests will automatically be executed.

**Comment by Rajan117** [comment] 2021-07-15 09:28
@eendebakpt The QisKit guide said to run those tests but if they are done automatically then I will do a pull request. Thank you :)

**Comment by Rajan117** [comment] 2021-07-15 09:50
I made a pull request but it says I have to sign the CLA which I did by login into my Git account. However it still says I haven't signed it and that Rajan Rana is not a GitHub user.
![image](https://user-images.githubusercontent.com/77441871/125768288-bf24d19e-4e26-4658-bd4a-cf2655e8a6d8.png)
How do I fix this?

**Comment by Rajan117** [comment] 2021-07-15 09:53
![image](https://user-images.githubusercontent.com/77441871/125768631-7a112cb6-a650-493d-8022-03547e21ad58.png)
How do I sign it for the other me? I cannot see an email to add to my account.

**Comment by jakelishman** [comment] 2021-07-15 13:12
There's a couple of additional things to consider here.  First, the result of `get_counts()` isn't always directly a `dict` instance - sometimes it's an instance of `qiskit.results.counts.Counts` (which subclasses `dict`).  Second, while the order of `dict` entries is typically insertion order, this wasn't a full Python guarantee until 3.7, despite being an implementation detail of CPython 3.6.  So
```python
newdict = {k: v for k, v in sorted(olddict.items())}
```
is not necessarily in sorted order in Python 3.6 if one is not using CPython, though in practice it almost certainly will be.

**Comment by nonhermitian** [comment] 2021-07-15 13:40
I am not sure I see the value here.  Namely there is no algorithmic reason to sort the keys.  In addition, the sort method is somewhat arbitrary, e.g. perhaps I want things sorted by Hamming weight (I personally often do) rather than by int representation.  Why not have a sort method on the `Counts` object itself?

**Comment by eendebakpt** [comment] 2021-07-16 15:13
The value is mainly in printing the results for the user. I agree that the choice of sorting order is arbitrary. But any choice seems better than a random order.

**Comment by nonhermitian** [comment] 2021-07-16 15:39
I guess my point is that, lacking any computational reason for doing so, the sorting should be optional.

**Comment by Rajan117** [comment] 2021-07-20 10:11
I could add a argument to the get counts method that will return a sorted list if used?

**Comment by Rajan117** [comment] 2021-07-20 10:12
My PR failed the windows, mac and linux tests? Any help on that would be appreciated

**Comment by jakelishman** [comment] 2021-07-20 10:50
Adding an optional keyword argument to `get_counts` I think is a fine solution.  There's an advantage to not having the user do it manually themselves, because the return value of `get_counts()` isn't necessarily exactly a `dict`; the natural
```python
counts = dict(sorted(result.get_counts().items()))
```
call would throw away the `dict` subclasses which normally get returned, which is surprising.

It's probably best to avoid sorting by default, and let the user explicitly ask for it, if they want it.  Perhaps accept an argument `sorter: Callable = None`, so the user can pass in an arbitrary function to provide the sort key?

> The `Statevector` method `sample_counts` returns a dict sorted on the key value. For that reason I would sort according to the key value.

This isn't really by design, it's just a side effect of an internal call to `np.unique` on the keys, which happens to return a sorted array.  That doesn't mean it's an invalid choice, just that this is still "arbitrary order", rather than an intentional sort.

Also, while the docstring of `get_counts()` is correct in saying it returns `dict` instances, it might be less surprising if it mentioned that it may also return subclasses. Several places in the tests assume that the output is actually a `Counts` instance, and going off the docstring, you'd not be aware that that was possible.

**Comment by Rajan117** [comment] 2021-07-20 22:17
I will give that a go then. Any idea why my pull request failed the tests? It failed the windows, mac and Linux ones. Not sure why a the code I changed would not effect that.

**Comment by jakelishman** [comment] 2021-07-21 08:07
https://github.com/Qiskit/qiskit-terra/pull/6752#discussion_r673000337

**Comment by Rajan117** [comment] 2021-07-26 07:25
Awesome thanks :) I will see what I can do about allowing the user to provide  an arbitrary sort function or atleast an argument for a basic sort.

**Comment by jlapeyre** [comment] 2021-11-04 18:00
See also #4985

**Comment by jakelishman** [comment] 2023-04-25 16:14
With the discussion above, I'm closing this as "not planned", now.  Qiskit will return the dictionary in arbitrary order to avoid unnecessary performance overhead (especially since sorting has non-linear complexity), since there's several sort orders that might be useful.  Users who would find a particular order more useful themselves can do the sort themselves.

**Closed by jakelishman** 2023-04-25 16:14 UTC
Labels: type: enhancement
