### ISSUE TITLE
labels in snapshot should be added to the draw function.

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-terra#2303] opened 2019-05-05 00:32 UTC
### What is the expected enhancement?

import qiskit.extensions.simulator

qr = qiskit.QuantumRegister(2)
cr = qiskit.ClassicalRegister(2)
circuit = qiskit.QuantumCircuit(qr, cr)
circuit.h(qr[0])
circuit.cx(qr[0], qr[1])
circuit.snapshot('test')
circuit.cx(qr[0], qr[1])
circuit.h(qr[1])

circuit.draw()

```
         ┌───┐      ░           
q3_0: |0>┤ H ├──■───░───■───────
         └───┘┌─┴─┐ ░ ┌─┴─┐┌───┐
q3_1: |0>─────┤ X ├─░─┤ X ├┤ H ├
              └───┘ ░ └───┘└───┘
 c3_0: 0 ═══════════════════════
                                
 c3_1: 0 ═══════════════════════
```

should have test written somewhere.

**Comment by mtreinish** [comment] 2019-05-05 00:50
I think this is a duplicate of: https://github.com/Qiskit/qiskit-terra/issues/1298 I'm going to close it and we can just track it there

**Closed by mtreinish** 2019-05-05 00:50 UTC

**Comment by jaygambetta** [comment] 2019-05-05 00:53
sure but I would close the other or edit it as we dont use load, save, extra. Just snapshot is the one we need.

**Comment by jaygambetta** [comment] 2019-05-05 01:02
I think this issue actually could be close in the other and clearly written as a good first contribution. 

Add snapshot label to circuit.draw() 

@1ucian0 and @mtreinish what do you think?

ps. [Yes it applies to all drawers]

**Comment by mtreinish** [comment] 2019-05-05 01:08
@jaygambetta sure sounds good to me. My only hesitation for a good first contribution label is that for the latex drawer I never actually found a good way to implement the label on top of the barrier in latex because of how we draw barriers it might require qcircuit patches. But, now that I think about it that's probably fine, adding barriers to first qcircuit and then terra was one of my first qiskit contributions.

**Comment by 1ucian0** [comment] 2019-05-05 01:14
Sure! I think it would help the first contributor if there is a clear expected result in advance. Would it be okey to draw snapshot as following (for the case of text)?
```
          ░ snapshot
 q_0: |0>─░──────────
          ░ 
 q_1: |0>─░──────────
          ░ 
 q_2: |0>─░──────────
          ░ 
```
