### ISSUE TITLE
random_circuit fails if conditional=True for large circuits

### ISSUE THREAD

**Issue by ewinston** [Qiskit/qiskit-terra#6994] opened 2021-09-09 01:23 UTC
### Information

- **Qiskit Terra version**: 0.19.0.dev0+07299e1
- **Python version**:
- **Operating system**:

### What is the current behavior?
When attempting to generate a random circuit using `qiskit.circuit.random.utils.random_circuit` with ~60 qubits with mid-circuit conditionals an error is generated;
```
_bounded_integers.pyx in numpy.random._bounded_integers._rand_int64()

ValueError: low >= high
```

### Steps to reproduce the problem
```python
from qiskit.circuit.random.utils import random_circuit
random_circuit(64, 64, conditional=True)
```

**Comment by mtreinish** [comment] 2021-09-09 02:03
The underlying issue here is we're trying to set the condition value as a random number with a max value of 2**n qubits here:

https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/random/utils.py#L150

which we obviously can't do with a numpy int 64 which is what it looks like it's using under the covers. We probably will have to change the random logic to use python's stdlib rng and use a python int instead so we can set the value to > 2**63.

**Comment by mtreinish** [comment] 2021-09-09 02:19
Thinking about it a bit more the other option is to split classical registers up at 63 bits (or split the random values in a larger register for every 63 bits) so we can use a random value generated with the current code.

**Comment by nonhermitian** [comment] 2021-09-09 04:18
Or generate random bitstrings and then convert.

**Comment by Kit-Kate** [comment] 2021-09-09 12:23
Hello! I would like to work on this issue. Can you assign me to it, please? Thank you!

**Comment by deeksha-singh030** [comment] 2022-01-23 17:04
Hey! @Kit-Kate  Are you still working on this issue?

**Comment by 1ucian0** [comment] 2022-01-31 20:27
Since the issues is stalling, do you want to take it @deeksha-singh030 ?

**Comment by deeksha-singh030** [comment] 2022-02-03 11:01
@1ucian0  Yes, I want to work on this issue.

**Comment by 1ucian0** [comment] 2022-02-04 17:11
assigning it to you @deeksha-singh030 ! Thanks!

**Comment by deeksha-singh030** [comment] 2022-03-30 18:48
The error is occurring for all the values of n > 31. So, to figure out the cause I changed the max condition value to number of qubits to verify for numpy int 64 but it is still giving the same error. I'm not able to figure out the issue here. Please help me with it @jakelishman
![6994 issue](https://user-images.githubusercontent.com/88299198/160908831-6a012c08-e16e-4680-912a-a279e42c0e1a.PNG)

**Comment by jakelishman** [comment] 2022-05-26 18:33
Hi, I'm so sorry this fell through.  Probably the best solution here is to not generate an integer directly - we'll always hit an upper limit in Numpy if we try this, either at 31, 63 or 127 qubits.  Instead, let's assume that we can safely generate 16-bit integers (Windows sometimes defaults to 32-bit rather than 64-bit), then we can calculate how many bits we need total, and generate enough integers that we've got enough bits.  For example, if we need a 64-bit integer, we could do
```python
parts = rng.integers(0, 1<<16, size=4)
shift = 0
condition_int = 0
for part in parts:
    condition_int += part << shift
    shift += 16
```

If we don't need an exact multiple of 16, we'd need to mask the last generated integer, but this lets us fairly generate a random integer that's as large as we could ever need.

We probably don't want to swap to using Python's built-in `random` module, because that will make reproducibility a bit harder, since that would use two separate bit generators.

**Comment by 1ucian0** [comment] 2022-06-13 15:32
Hi @deeksha-singh030, did @jakelishman answered your question?

**Comment by akshayp2003** [comment] 2022-07-23 20:40
Hi @1ucian0  I would like to work on this issue. Can you please assign it to me?

**Comment by 1ucian0** [comment] 2022-07-23 20:54
Sure! Assigned!

**Comment by akshayp2003** [comment] 2022-07-29 21:06
I tried the way suggested by @jakelishman and found that the issue gets resolved if we do this:
```python
parts = rng.integers(0, 1<<16, size=4)
shift = 0
condition_int = 0
for part in parts:
     ipart = (int)(part)
     condition_int += ipart << shift
     shift += 16
op.condition = (cr, condition_int)
```
I have done typecasting on parts (numpy int) and created iparts (python int) so that the condition_int value is in int. This ensures that condition_int has no upper limit like Numpy int.

We can see that for num_qubits > 63 (80 in my case) we get no error and the issue is fixed

![image](https://user-images.githubusercontent.com/73956106/181817495-728ca421-f6c8-45eb-a682-2ab3e57d4edf.png)

**Comment by akshayp2003** [comment] 2022-08-04 12:39
According to a suggestion by @mtreinish, I included number of qubits in the code so that the code is not hard coded to generate a random integer:
```python
parts = rng.integers(0, 1<<16, size=int(num_qubits/16))
shift = 0
condition_int = 0
for part in parts:
    ipart = int(part)
    condition_int += ipart << shift
    shift += 16
condition_int = condition_int<<(num_qubits%16)
value_add = rng.integers(0, 1<<(num_qubits%16))
condition_int += int(value_add)
```
Here, for any number of qubits this code generates a random number with maximum value of 2**num_qubits - 1. For example, if num_qubits is 70, then the loop runs 4 times generating a random number upto 2^64 and then that number is shifted bitwise by 6 bits (70-64) and another random number of 6 bits is added to it. Kindly let me know if this approach is correct.

**Closed** 2022-10-28 20:20 UTC
Labels: bug, good first issue
