### ISSUE TITLE
Code to compute concurrence is wrong

### ISSUE THREAD

**Issue by alerog** [Qiskit/qiskit-terra#3366] opened 2019-10-31 00:38 UTC
### Information

- **Qiskit Terra version**:  0.10.0
- **Python version**: 3.7
- **Operating system**: Linux

### What is the current behavior?

The routine 'concurrence' in qiskit/tools/qi/qi.py is wrong, the matrix

A = rho.dot(YY).dot(rho.conj()).dot(YY)

is not necessarily Hermitian but the Hermitian eigensolver is used to get it's eigenvalues. This can produce negative eigenvalues even though the matrix A is positive semidefinte.

### Steps to reproduce the problem

It is sufficient to use an entangled density matrix like

array([[0.20194612+0.j, 0.25967063+0.j, 0.27702504+0.j, 0.13035404+0.j],
       [0.25967063+0.j, 0.33389518+0.j, 0.3562102 +0.j, 0.16761458+0.j],
       [0.27702504+0.j, 0.3562102 +0.j, 0.38001657+0.j, 0.17881667+0.j],
       [0.13035404+0.j, 0.16761458+0.j, 0.17881667+0.j, 0.08414212+0.j]])

and check that the eigenvalues returned by the hermitian eigensolver are

[-0.0971868  -0.08020192 -0.0104574   0.39189013]

### What is the expected behavior?

For the density matrix above the correct eigenvalues are

[0.00000000e+00 0.00000000e+00 6.45239207e-09 4.51712320e-01]

### Suggested solutions

Replace the following 2 lines of the concurrence routine

 w = la.eigh(A, eigvals_only=True)
 w = np.sqrt(np.maximum(w, 0))

with the correct ones

w = la.eigvals(A).real
isort = np.argsort(w)
w = np.sqrt(np.maximum(w[isort[:]],0.))

**Comment by chriseclectic** [comment] 2019-11-01 18:31
Duplicate of #3095 

I just put a PR in to fix these issue sin #3376

**Closed** 2019-11-06 20:56 UTC
Labels: duplicate
