### ISSUE TITLE
BasicAer needs H

### ISSUE THREAD

**Issue by zhangl64** [Qiskit/qiskit-terra#4625] opened 2020-06-27 03:59 UTC
### Information

- **Qiskit Terra version**: 0.19.6  
- **Python version**: 3.7.4
- **Operating system**: Mac OS 10.14.6

### What is the current behavior?

Error message:
```
   result = backend_sim.run(assemble(qc)).result()
  File "/Users/leizhang/opt/miniconda3/envs/Qiskit/lib/python3.7/site-packages/qiskit/providers/basicaer/basicaerjob.py", line 40, in _wrapper
    return func(self, *args, **kwargs)
  File "/Users/leizhang/opt/miniconda3/envs/Qiskit/lib/python3.7/site-packages/qiskit/providers/basicaer/basicaerjob.py", line 95, in result
    return self._future.result(timeout=timeout)
  File "/Users/leizhang/opt/miniconda3/envs/Qiskit/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Users/leizhang/opt/miniconda3/envs/Qiskit/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/leizhang/opt/miniconda3/envs/Qiskit/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/leizhang/opt/miniconda3/envs/Qiskit/lib/python3.7/site-packages/qiskit/providers/basicaer/qasm_simulator.py", line 415, in _run_job
    result_list.append(self.run_experiment(experiment))
  File "/Users/leizhang/opt/miniconda3/envs/Qiskit/lib/python3.7/site-packages/qiskit/providers/basicaer/qasm_simulator.py", line 583, in run_experiment
    raise BasicAerError(err_msg.format(backend, operation.name))
qiskit.providers.basicaer.exceptions.BasicAerError: 'qasm_simulator encountered unrecognized operation "h"'
```

### Steps to reproduce the problem

Run the example in README.md:
```
from qiskit import *
qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0,1], [0,1])
backend_sim = BasicAer.get_backend('qasm_simulator')
result = backend_sim.run(assemble(qc)).result()
print(result.get_counts(qc))
```

### What is the expected behavior?

Should print the output without error.

### Suggested solutions

N/A. 

Many thanks!

**Comment by realistix30** [comment] 2020-06-27 05:20
Hi,
I'm not sure what the difference with Aer and BasicAer.
But I tried to run it using Aer it worked for me. 
![Bug#4625](https://user-images.githubusercontent.com/65805697/85915290-c17cf680-b878-11ea-9422-476e829ac534.PNG)

**Comment by zhangl64** [comment] 2020-06-27 13:56
Awesome, thanks @realistix30 , `Are` works for me, please let me if `BasicAer` works on your side. Cheers~

**Comment by realistix30** [comment] 2020-06-27 14:52
You're welcome! It seems this is just a work around. I'm still not sure about the underlying issue. I asked around slack and they said the BasicAer will be replaced by Aer once Aer is stable. There are also other differences between them. You can check here. https://qiskit.slack.com/archives/C7SJ0PJ5A/p1591566437406400?thread_ts=1591311954.362500&channel=C7SJ0PJ5A&message_ts=1591566437.406400

**Comment by jaygambetta** [comment] 2020-06-29 12:42
the h gate is not defined in basic aer this is why it is not working.

**Comment by zhangl64** [comment] 2020-06-29 13:12
Can the `README.md` file be fixed to reflect this? Thanks.

**Comment by realistix30** [comment] 2020-06-29 14:05
@jaygambetta Thanks for telling us the reason why. I thought it was something more complicated. If that's the case, @zhangl64 suggestion would be enough to prevent this error. Can I update the README.md file to close this issue?

**Comment by jaygambetta** [comment] 2020-06-29 14:14
sure  but  adding just this gate to basic aer will also fix it which might be good as a backup as well. 

adding H here

https://github.com/Qiskit/qiskit-terra/blob/0382d50d309374583071abebc73f889ade08c9e5/qiskit/providers/basicaer/qasm_simulator.py#L510

should fix it as well if basic aer is used (personally I would love to rewrite basic aer to be smarter or remove it all together (this is something we have been discussing. 

```
elif operation.name is "h":
    qubit = operation.qubits[0]
    gate = `add matrix here`
    self._add_unitary(gate, [qubit])
```

**Comment by realistix30** [comment] 2020-06-29 14:21
That's a better option. Will update BasicAer to add H. It will be my first contribution so I'm excited.  Please assign this issue to me and I'll make a pull request to close this issue. Thank you very much for the guidance!

**Comment by jaygambetta** [comment] 2020-06-29 14:23
no problem -- add a test and let me know if you have questions or problems.

**Comment by chriseclectic** [comment] 2020-07-02 00:07
BasicAer supports a set of basis gates `u1, u2, u3, id, cx, unitary`. You should transpile your circuit to its basis gates before running assemble like you would for running on a real backend:

```python
backend_sim = BasicAer.get_backend('qasm_simulator')
result = backend_sim.run(assemble(transpile(qc, backend_sim))).result()
```

I don't see any reason to add H to BasicAer when you can just transpile

**Comment by realistix30** [comment] 2020-07-05 01:28
Hi, what is our agreed fix for this issue? It seems one purpose of adding H is also for convenience? Would it still work the same without transpiling it?

**Comment by jaygambetta** [comment] 2020-07-06 13:29
@chriseclectic because many of the examples have h and we dont need to transpile for them. It does not hurt to over complete it.

**Comment by 1ucian0** [comment] 2020-09-09 18:01
In the [suggested PR adding `H` to BasicAer](https://github.com/Qiskit/qiskit-terra/pull/4759), @ajavadia said:
> Hi @realistix30. I don't think we should add a single gate and do an ad-hoc fix on an issue.
> 
> First, I don't quite understand the original issue, because it is based on running a circuit without transpiling it for the backend. This kind of thing is not a recommended way of running code on any backend. If you transpile, the gates will be translated to the correct basis.
> 
> I'm happy to consider something like this if the issue is that rewriting the circuit in a minimal basis makes certain simulations too slow. But that is not how the original issue is presented. And performance has never really been a consideration in BasicAer (that's why Aer exists). But if we go this route, I think we should add all the gates in the standard library and properly test them. My recommendation is not to do this unless there is a clear case first.

**Comment by 1ucian0** [comment] 2020-09-09 18:03
Removing `bug`, since README was updated in #4954. This is a `discussion` issue now.

**Comment by kevinsung** [comment] 2022-03-14 15:58
According to https://github.com/Qiskit/qiskit-terra/issues/7633#issuecomment-1058586399, this issue will be fixed by addressing https://github.com/Qiskit/qiskit-terra/issues/7670, because then BasicAer will support any gate that has a matrix. @jakelishman is that right?

**Comment by jakelishman** [comment] 2022-03-19 03:34
Yeah, it would thanks.  I suppose in theory we could add `h` to its list of supported gates at that time as well to assist the transpiler, but if BasicAer's logic essentially just becomes `Statevector(circuit)` (with some splitting to handle mid-circuit measurements), it'd support it by default.

Would you prefer to leave this open for tracking in your mentorship project?  If not, we can just close the issue - any discussion on it is stale, and basically covered by #7670 as you say.

**Comment by kevinsung** [comment] 2022-03-19 13:25
I say we leave it open for now since it's technically a separate issue.

**Comment by jakelishman** [comment] 2023-04-19 23:41
As this has staled, and as https://github.com/Qiskit/qiskit-terra/issues/4625#issuecomment-652704975 points out, the failure in the original issue is not a bug, I'm going to close this issue now with the decision that it's not necessary that BasicAer has a `h` instruction.  Its purpose is principally just for testing the provider paths, which require transpilation to the basis set.

If there's more to say on this, please re-open this issue.

**Closed by jakelishman** 2023-04-19 23:41 UTC
Labels: type: discussion

**Comment by 1ucian0** [comment] 2023-09-16 20:45
H, P, and U was added in https://github.com/Qiskit/qiskit/pull/10673
