### ISSUE TITLE
classical_function creates wrong circuits for some cases

### ISSUE THREAD

**Issue by a-matsuo** [Qiskit/qiskit-terra#5666] opened 2021-01-21 13:17 UTC
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.8
- **Operating system**: macOS Catalina

### What is the current behavior?
`classical_function` creates wrong circuits for some cases. I confirmed at least two cases. 

### Steps to reproduce the problem
Case 1) 
```
def expr1(x1: Int1, x2: Int1, x3: Int1) -> Int1:
    return x1

cf = classical_function(expr1)
print(cf.synth())

q_0: ──■──
       │  
q_1: ──┼──
       │  
q_2: ──┼──
     ┌─┴─┐
q_3: ┤ X ├
     └───┘
```

Case 2)
```
def expr2(x1: Int1, x2: Int1, x3: Int1) -> Int1:
    return x1 or x2 or x3

cf = classical_function(expr2)
print(cf.synth())

q_0: ──o────────────
       │            
q_1: ──o────o───────
       │    │       
q_2: ──■────■────■──
     ┌─┴─┐┌─┴─┐┌─┴─┐
q_3: ┤ X ├┤ X ├┤ X ├
     └───┘└───┘└───┘
```
### What is the expected behavior?
Case 1)
The control bit of the CNOT gate should be the most bottom bit. 

As written in the [documentation](https://qiskit.org/documentation/apidoc/classicalfunction.html), following Qiskit’s little-endian bit ordering convention, the left-most bit (x1) is the most significant bit and the right-most bit (x3) is the least significant bit. 
The following code is an example for the correct bit ordering.
```
def expr3(x1: Int1, x2: Int1, x3: Int1) -> Int1:
    return not x1 and x2 and x3

cf = classical_function(expr3)
print(cf.synth())

q_0: ──■──
       │  
q_1: ──■──
       │  
q_2: ──o──
     ┌─┴─┐
q_3: ┤ X ├
     └───┘
```

Case 2)
The circuit does not represent `x1 or x2 or x3`. For example, when (x1, x2, x3) = (001), $q_3$ of the circuit does not become 1.

**Comment by boschmitt** [comment] 2021-02-23 13:12
Case 1 is not a bug.

Indeed, Qiskit's follows little-endian bit ordering convention but this happens __within__ a register, i.e., there will be a difference of between declaring two 1 qubit registers and a register of 2 qubits.  Hence, if you had declared a the function as
```python
def expr1(x: Int3) -> Int1:
    ...
```
then you would get `x` as a register of three bits following the little-endian bit ordering.

Case 2 will be fixed by #5830

**Closed** 2021-03-31 18:11 UTC
Labels: bug
