### ISSUE TITLE
Branch `master` is failing

### ISSUE THREAD

**Issue by pacomf** [Qiskit/qiskit-terra#2031] opened 2019-03-27 17:27 UTC
Trying to build `master` at commit f3a718fbe5d3094b22019d4147330b9980e326bd failed.
More info at: https://travis-ci.com/Qiskit/qiskit-terra/jobs/188199958

**Comment by mtreinish** [comment] 2019-03-27 17:29
This is a duplicate of https://github.com/Qiskit/qiskit-terra/issues/2029 closing so we can track it there.

**Closed by mtreinish** 2019-03-27 17:29 UTC
Labels: master failing
