### ISSUE TITLE
Running pulse schedule smaller than device gives full device width bitstrings.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#4240] opened 2020-04-24 02:36 UTC
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
Running the following on a 20Q device:
```python

qc = QuantumCircuit(5, 5)
qc.h(2)
qc.cx(2,0)
qc.cx(0,3)
qc.cx(2,4)
qc.cx(4,1)
qc.barrier()
qc.measure(range(5), range(5))
qc.draw()

transpiled_circ = transpile(qc, backend)
sch = build_schedule(transpiled_circ, backend)

pulse_job = execute(sch, backend)
```

gives 20bit outputs instead of 5bits like  if the circuit were run directly, e.g.

```
{'00010110011110010111': 1,
 '00010111011110000000': 6,
 '00011111011110000111': 8,
 '00010110011100011011': 1,
 '00011111011110011111': 27,
 '00011110011100001001': 1,
 '00011111011110010001': 8,
}
```

**Comment by taalexander** [comment] 2020-04-24 16:06
This is not a bug and is the expected behavior of the device given Qiskit's current interpretation of the `meas_map`. Future device updates will relax this requirement.

**Comment by nonhermitian** [comment] 2020-04-24 16:08
Is this mentioned anywhere in the docs?

**Comment by taalexander** [comment] 2020-04-24 16:32
Yes in this [notebook doc](https://github.com/lcapelluto/qiskit/blob/708f83a94e97a5655a9f3c4e6fdf7a6145f9fa3e/docs/tutorials/advanced/terra/pulse/adding_measurements.ipynb)

**Comment by jakelishman** [comment] 2023-04-22 14:33
Closing as "not a bug" given the above discussion.

**Closed by jakelishman** 2023-04-22 14:33 UTC
Labels: bug, mod: pulse
