### ISSUE TITLE
IterativeAmplitudeEstimation with Primitives Sampler

### ISSUE THREAD

**Issue by GiuliaFranco** [Qiskit/qiskit-terra#9384] opened 2023-01-18 10:20 UTC
### Environment

- **Qiskit Terra version**:  0.22.3
- **Python version**: 3.9.15
- **Operating system**: Windows 11

### What is happening?

The question regards the use of the IterativeAmplitudeEstimation class (and its methods like estimate or construct_circuit) with the new Sampler paradigm. We conducted several different experiments with different Sampler implementations but were never completely successful.
If we use the formulation with context managers and the qiskit_ibm_runtime Sampler, we get a specific runtime error ERROR Failed to execute program: __init__() missing 1 required positional argument: \'num_ctrl_qubits' that causes the AlgorithmError: 'The job was not completed successfully. ' . However the same code runs just fine using the old QuantumInstance class or even using the sampler from qiskit.primitives without context managers.
The second main experiment was conducted using exactly the setting just described (with the sampler from qiskit.primitives and no context manager) and was executed successfully, but produced wrong results. In particular, the probability of being 0 increases for the objective qubit as k increases, regardless of the rest of the circuit. Again this code runs fine with QauntumInstance and produces the expected results.
Are we missing something? The only significant line of code that was changed is the following:
iae = IterativeAmplitudeEstimation(epsilon, alpha=alpha, quantum_instance=qi)  into
iae = IterativeAmplitudeEstimation(epsilon, alpha=alpha, sampler=sampler)  where sampler = Sampler() for the second experiment

### How can we reproduce the issue?

![image (2)](https://user-images.githubusercontent.com/43806312/213146195-13d67e6e-5301-4eee-9e2a-efcf41d9d829.png)

### What should happen?

If we use the formulation with context managers and the qiskit_ibm_runtime Sampler, we get a specific runtime error ERROR Failed to execute program: __init__() missing 1 required positional argument: \'num_ctrl_qubits' that causes the AlgorithmError: 'The job was not completed successfully. '

**Comment by Cryoris** [comment] 2023-01-18 21:32
Thanks for reporting this @GiuliaFranco! Could you post the entire snippet of the second scenario that produces the wrong results? 🙂

**Comment by GiuliaFranco** [comment] 2023-01-19 10:17
Here some details on expected results:

**_Estimated value with QuantumInstance_**:	0.6651
Confidence interval: 	[0.6480, 0.6822]


**_Estimated value with Sampler Primitive:_** 0.0
Confidence interval: 	[-2.3197, -2.3197]

**Comment by ElePT** [comment] 2023-01-19 10:40
Hi! The root cause of this issue is here: https://github.com/Qiskit/qiskit-terra/issues/9390. I am just about to open a bugfix PR that should solve it.

**Comment by ElePT** [comment] 2023-01-19 11:00
PR: https://github.com/Qiskit/qiskit-terra/pull/9391

**Comment by Cryoris** [comment] 2023-01-19 13:20
And the other bug is caused by a padding of the measurement results with the number of qubits instead of classical bits -- PR follows 🙂

**Comment by woodsp-ibm** [comment] 2023-01-21 16:32
#9391 Fixed the num_ctrl_qubits problem when using the runtime .
#9394 Fixed the incorrect result problem

As such the two problems this issue raised have been fixed so I am closing this as completed. FYI the fixes will be in the imminent 0.23.0 release.

**Closed by woodsp-ibm** 2023-01-21 16:32 UTC
Labels: bug, mod: algorithms
