### ISSUE TITLE
`ecr`- and `cz`-based fake backends do not use `ECRGate` and `CZGate`

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/qiskit-terra#10004] opened 2023-04-20 17:51 UTC
### Environment

- **Qiskit Terra version**: Terra main
- **Python version**: 3.10
- **Operating system**: macOS

### What is happening?

Fake V2 backends (e.g. `FakeSherbrooke`) that use ecr- or cz-based entangling construct opaque gates for those names when building their `Target`.  This causes failures such as #9935.

### How can we reproduce the issue?

```python
from qiskit.providers.fake_provider import FakeSherbrooke
type(FakeSherbrooke().target.operation_from_name("ecr"))
```
```
qiskit.circuit.gate.Gate
```

### What should happen?

Should be `ECRGate`.

**Comment by mtreinish** [comment] 2023-04-20 18:32
This is basically a duplicate of: https://github.com/Qiskit/qiskit-terra/issues/9983 although this issue covers the broader issue in the fake backends (it's more than just `FakePrague`).

**Comment by jakelishman** [comment] 2023-04-20 18:35
Oh so it is - my bad, I'd completely misremembered that issue.  In my head, we were accidentally mapping `cz` to `cx` in that issue - I think I must have just dreamed that!!

**Closed** 2023-04-25 16:23 UTC
Labels: bug
