### ISSUE TITLE
Impossible to use runtime programs with latest Qiskit version `0.34.2`

### ISSUE THREAD

**Issue by rmoyard** [Qiskit/qiskit-terra#7660] opened 2022-02-14 16:08 UTC
### Environment

- **Qiskit Terra version**: 
qiskit                   0.34.2
qiskit-aer               0.10.3
qiskit-aqua              0.7.0
qiskit-ibmq-provider     0.18.3
qiskit-ignis             0.7.0
qiskit-terra             0.19.2

- **Python version**: 
Python 3.8
- **Operating system**: 
Mac OS (intel chip)

### What is happening?

Since last release of Qiskit, I am unable to run Qiskit runtime program. Apparently there is a problem with the `qpy_serialization `function, which creates invalid OPENQASM register name such as \\x01.

Here you can find a part of the error message.

/usr/local/lib/python3.8/site-packages/qiskit/circuit/qpy_serialization.py:1563: UserWarning: The qiskit version used to generate the provided QPY file, 0.19.2, is newer than the current qiskit version 0.19.1. This may result in an error if the QPY file uses instructions not present in this current qiskit version\n
....

File "/usr/local/lib/python3.8/site-packages/qiskit/circuit/register.py", line 103, in __init__\n2022-02-14T15:51:46.917015284Z     raise CircuitError(\n2022-02-14T15:51:46.917032015Z qiskit.circuit.exceptions.CircuitError: \'\\x01 is an invalid OPENQASM register name. See appendix A of https://arxiv.org/pdf/1707.03429v2.pdf.\'\n'

Process finished with exit code 1

### How can we reproduce the issue?

```
from qiskit import QuantumCircuit

qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0, 1], [0, 1])

IBMQ.enable_account(my_token)
provider = IBMQ.get_provider(hub="ibm-q", group="open", project="main")

program_inputs = {'circuits': qc,
                  'optimization_level': 3
                 }
options = {'backend_name': "ibmq_qasm_simulator"}
job = provider.runtime.run(program_id="circuit-runner",
                           options=options,
                           inputs=program_inputs,
                          )
```

### What should happen?

It should run the circuit runner program without problem.

**Comment by Cryoris** [comment] 2022-02-15 10:11
@jyu00 will know more about this, but as far as I know the fix for this in underway 🙂

**Comment by rmoyard** [comment] 2022-02-28 15:54
Hi @Cryoris @jyu00! Are the runtime programs down? Now it does not return any error but the result `job.result()` is empty for any of my programs.

**Comment by jyu00** [comment] 2022-02-28 16:11
@rmoyard Yeah runtime is having an issue right now that's preventing results from being returned. We've identified the cause and are working on a fix, which should be available later today.

**Comment by rmoyard** [comment] 2022-02-28 16:57
@jyu00 Thank you for the update! Is there a place where I can find the status of runtime programs?

**Comment by jyu00** [comment] 2022-03-01 12:57
Runtime was also upgraded to 0.34.2. Closing this issue.

**Closed by jyu00** 2022-03-01 12:57 UTC
Labels: bug
