### ISSUE TITLE
Circuit returned by transpiler returns blank image for circuit.draw(output='latex')

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#2295] opened 2019-05-03 16:29 UTC
### Information

- **Qiskit Terra version**: 0.8
- **Python version**:
- **Operating system**: osx

### What is the current behavior?
```python
qr = QuantumRegister(3,'qr')
cr = ClassicalRegister(3, 'cr')
ghz = QuantumCircuit(qr, cr, name='ghz')

ghz.h(qr[2])
ghz.cx(qr[2], qr[1])
ghz.barrier(qr)
ghz.measure(qr, cr)

device = IBMQ.get_backend('ibmq_16_melbourne')
trans_ghz = transpile(ghz, device)
trans_ghz.draw(output='latex')
```

gives blank image.

### What is the expected behavior?
Should work.  Used to in last version.

**Comment by mtreinish** [comment] 2019-05-03 18:28
So I took a look at this and it's actually a duplicate of #2155 the issue here is the same as in there (which I still haven't had a chance to come up with a fix for) the circuit is causing the pdf output from `pdflatex` to wrap pages and puts the actual circuit diagram on the second page which breaks our conversion from pdf->png. I generated the pdf manually from the `latex_source` output and it is 2 pages: 
[test.pdf](https://github.com/Qiskit/qiskit-terra/files/3143140/test.pdf) I'm closing this and we can continue to track this in #2155

**Closed by mtreinish** 2019-05-03 18:28 UTC
Labels: bug
