### ISSUE TITLE
Param expressions with variables not properly handled by pi_check

### ISSUE THREAD

**Issue by enavarro51** [Qiskit/qiskit-terra#4806] opened 2020-07-26 20:53 UTC
### What is the expected enhancement?
Re: #4611, the display portion of that issue was fixed in #4616, but there are obvious instances of pi that are not being modified to the pi symbol by pi_check.

pi_check should work on any of the numeric values inside the parameter expression.
```
from qiskit.circuit.library.data_preparation import PauliFeatureMap

prep = PauliFeatureMap(2, reps=1, paulis=['ZZ'])
prep.draw('mpl')
```
![image](https://user-images.githubusercontent.com/16268251/88489114-2e061680-cf47-11ea-906a-654e9e76e7e2.png)

**Comment by Cryoris** [comment] 2020-07-27 07:34
This is a duplicate of #4170 🙂

**Comment by enavarro51** [comment] 2020-07-27 11:59
Thanks. Missed that.

**Closed** 2020-08-29 02:44 UTC
Labels: type: enhancement
