### ISSUE TITLE
CompleteMeasFitter incorrectly imported in measurement_error_mitigation.py

### ISSUE THREAD

**Issue by omarshehab** [Qiskit/qiskit-terra#6980] opened 2021-09-03 05:17 UTC
### Information

- **Qiskit Terra version**: 0.18.0
- **Python version**: 3.9.5 (default, May 18 2021, 12:31:01) [Clang 10.0.0 ]
- **Operating system**: Darwin

### What is the current behavior?
I am currently seeing

`QiskitError: 'Unknown fitter <qiskit.ignis.mitigation.measurement.fitters.CompleteMeasFitter object at 0x7fcbcace6c40>'`

error, when I pass an `qiskit.ignis.mitigation.measurement.fitters.CompleteMeasFitter`  object as a value to the parameter `measurement_error_mitigation_cls`  in the constructor of `QuantumInstance` and use the `QuantumInstance` object with `QuantumKernel.evaluate()` . 

### Steps to reproduce the problem

1. Generate the calibration circuits using `complete_meas_cal()`.
2. Execute the calibration circuits on target hardware (for this week ibm_toronto).
3. Calculate the calibration matrix using CompleteMeasFitter().
4. Pass the calibration matrix calculated in step # 3 as a value for the parameter `measurement_error_mitigation_cls`while creating an instance of QuantumInstance . For simplicity, I am not overriding the default values for `cals_matrix_refresh_period` and `measurement_error_mitigation_shots`.
5. Use the QuantumInstance  object in the standard QSVM pipeline.

### What is the expected behavior?
It should not throw any runtime error.

### Suggested solutions
`CompleteMeasFitter` incorrectly imported in `measurement_error_mitigation.py`. At line # 141 of [measurement_error_mitigation.py](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/utils/measurement_error_mitigation.py), `CompleteMeasFitter` should be imported from `qiskit.ignis.mitigation.measurement.fitters` instead of `qiskit.ignis.mitigation.measurement`.

**Comment by TheGupta2012** [comment] 2021-09-03 06:57
May I work on this @omarshehab ?

**Comment by ShellyGarion** [comment] 2021-09-03 07:50
I think that the following PR should handle this issue: #6867 
(note that `qiskit-ignis` is going to be deprecated)

**Comment by TheGupta2012** [comment] 2021-09-03 08:18
Okayy 👍

**Comment by ShellyGarion** [comment] 2021-09-03 16:22
PR #6867 is part of the next release 0.19: https://github.com/Qiskit/qiskit-terra/milestone/18

**Comment by woodsp-ibm** [comment] 2021-09-03 16:52
Can you check with the latest version of qiskit - 0.18.1 (you say you have 0.18.0). The issue you describe was fixed

See https://qiskit.org/documentation/release_notes.html#bug-fixes

> Fixed an issue where the QuantumInstance class would potentially try to use the CompleteMeasFitter class before it was imported resulting in an error. Fixed #6774

**Comment by omarshehab** [comment] 2021-09-04 17:57
@woodsp-ibm , I received the same error with Qiskit Terra 0.18.1.

**Comment by jakelishman** [comment] 2021-09-04 20:14
It sounds like you're passing an instance, but the documentation says it should be the actual class (i.e. pass `CompleteMeasFitter` directly). The error you reported is consistent with the import having succeeded, but the wrong value having been passed.

(by the way, for reproducibility, it's easier for us if you can provide a minimal complete block of code to read and copy/paste, rather than trying to interpret text)

**Comment by omarshehab** [comment] 2021-09-04 20:55
@jakelishman , I have attached the MWE code here.

[qsvm-readout-error-mitigation-mwe.ipynb.zip](https://github.com/Qiskit/qiskit-terra/files/7110511/qsvm-readout-error-mitigation-mwe.ipynb.zip)

**Comment by jakelishman** [comment] 2021-09-04 22:19
That's [not exactly a MWE](https://stackoverflow.com/help/minimal-reproducible-example), but I can see you are setting `measurement_error_mitigation_class` to an _instance_ of `CompleteMeasFitter`, but it's meant to be the class (type).  You need to pass `CompleteMeasFitter` to construct `QuantumInstance`, not a constructed instance of it.

**Comment by woodsp-ibm** [comment] 2021-09-05 00:00
If an example would be helpful for how to use it see this tutorial https://qiskit.org/documentation/tutorials/algorithms/03_vqe_simulation_with_noise.html#Performance-with-noise-and-measurement-error-mitigation

**Comment by omarshehab** [comment] 2021-09-05 12:33
@woodsp-ibm , I modified the statement to create QuantumInstance as follows.

```
noise_model = NoiseModel.from_backend(backend)
adhoc_backend = QuantumInstance(backend, shots=1024,
                                seed_transpiler=seed, optimization_level = 3, noise_model=noise_model, measurement_error_mitigation_cls=CompleteMeasFitter)
```

Currently, I am getting the following error.
```
QiskitError: "The noise model is not supported on the selected backend ibmq_quito (<AccountProvider for IBMQ(hub='ibm-q-internal', group='deployed', project='default')>) only certain backends, such as Aer qasm simulator support noise."````

**Comment by ShellyGarion** [comment] 2021-09-05 12:42
@omarshehab - you cannot have a noise model with ibmq backend, only with Aer simulator: 
`backend = Aer.get_backend('aer_simulator')`
the ibmq devices already have noise inside them :) 
so, you should either choose an ibmq backend, or Aer simulator with a noise model
please look again at the tutorial suggested above.

**Comment by jakelishman** [comment] 2021-12-14 17:11
I'm closing this now, because I think that if there was a bug, it was fixed, and the other issues were due to problems with the usage.  Please feel free to re-open this or another issue if that's not the case.

**Closed by jakelishman** 2021-12-14 17:11 UTC
Labels: bug
