### ISSUE TITLE
translation_method='synthesis' fails on gate blocks of length 1, due to ConsolidateBlocks

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#6073] opened 2021-03-24 00:59 UTC
```py
from qiskit import QuantumCircuit, transpile

circuit = QuantumCircuit(2)
circuit.iswap(0, 1)

out = transpile(circuit, basis_gates=['u', 'cx'], translation_method='synthesis')
```
does not change the circuit at all.

The reason is that the "ConsolidateBlock" pass has some logic around ignoring blocks of length 1. I'm not sure why that's there. If I simply add an H gate to qubit 0, then the block size becomes 2 and the pass does indeed consolidate that into a Unitary, and the rest of the basis translation works as expected.

**Comment by mtreinish** [comment] 2021-03-24 01:22
Closing as this is a duplicate of #5967 and #5203, it is being fixed by #6024

**Closed by mtreinish** 2021-03-24 01:22 UTC
Labels: bug
