### ISSUE TITLE
transpile() hung up when running with multiple circuits and custom pass manager

### ISSUE THREAD

**Issue by itoko** [Qiskit/qiskit-terra#3925] opened 2020-03-04 07:28 UTC
### What is the current behavior?
On Mac OS machine, `transpile()` hung up in `parallel_map` when it runs with multiple circuits and custom pass manager. 

### Steps to reproduce the problem
```
from qiskit import QuantumCircuit, Aer, transpile
from qiskit.transpiler.coupling import CouplingMap
from qiskit.transpiler.pass_manager_config import PassManagerConfig
from qiskit.transpiler.preset_passmanagers import level_0_pass_manager

qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)

backend = Aer.get_backend('qasm_simulator')

pm_conf = PassManagerConfig(
    initial_layout=None,
    basis_gates=['u1', 'u2', 'u3', 'cx'],
    coupling_map=CouplingMap([[0, 1]]),
    backend_properties=None,
    seed_transpiler=1
)
pm = level_0_pass_manager(pm_conf)

transpiled = transpile([qc, qc],
                       backend=backend,
                       pass_manager=pm)
```
Note: No problem in the single circuit case `transpile(qc, backend=backend, pass_manager=pm)` or when specifying the same preset pass manager via optimization_level `transpile([qc, qc], backend=backend, optimizaton_level=0)`.

**Comment by nonhermitian** [comment] 2020-03-04 09:25
Are you importing matplotlib anywhere when this happens?  That is a known mpl issue.

**Comment by kdk** [comment] 2020-03-04 15:36
I got the following warnings prior to the hang when I tried to replicate this from master with python 3.5 on osx 10.14.
```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.5/multiprocessing/queues.py", line 234, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/anaconda3/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'level_0_pass_manager.<locals>._choose_layout_condition'
Traceback (most recent call last):
  File "/anaconda3/lib/python3.5/multiprocessing/queues.py", line 234, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/anaconda3/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'level_0_pass_manager.<locals>._choose_layout_condition'
```

**Comment by mtreinish** [comment] 2020-03-04 15:58
This looks like it could be related to: https://github.com/Qiskit/qiskit-terra/issues/3808

**Comment by nonhermitian** [comment] 2020-03-04 16:54
I think this is a bit different.  It seems that `choose_layout_condition` can simply not be pickled.  The other is the mpl issue that is to be resolved in v3.3

**Comment by 1ucian0** [comment] 2020-03-04 17:20
callables and parallelization not always play well together. Let me have a look...

**Comment by 1ucian0** [comment] 2020-03-05 15:07
The problem with the pickled callable from @kdk in https://github.com/Qiskit/qiskit-terra/issues/3925#issuecomment-594607628 is because Python 3.5 (do we still support it?) In Python 3.7 the hanging up from @itoko is reproducible.

**Comment by 1ucian0** [comment] 2020-03-05 15:47
hold on.. sometimes in python 3.7 I'm also getting the unpickleble issue...

**Closed** 2020-03-25 15:02 UTC
Labels: bug, status: pending PR
