### ISSUE TITLE
Specifying the 'U_error' noise parameter runs into an error

### ISSUE THREAD

**Issue by gautierronan** [Qiskit/qiskit-terra#783] opened 2018-08-16 15:03 UTC
### Informations

- **Qiskit Terra version**: 0.5.6
- **Python version**: 3.6.2
- **Operating system**: Windows 10

### What is the current behavior?
The following program runs into the error `QISKitError: 'No counts for circuit "None"`:
```python
from qiskit import *
q = QuantumRegister(2)
c = ClassicalRegister(2)
circ = QuantumCircuit(q, c)
circ.h(q[0])
circ.cx(q[0], q[1])
circ.measure(q[0], c[0])

config = {
    'noise_params': {
        'U': {
            'U_error': [
                [[1, 0], [0, 0]],
                [[0, 0], [0.998, 0.002]]
                ]
            }
        }
    }

sim = 'local_qasm_simulator_cpp'
job = execute(circ, sim, config)
result = job.result()
result.get_counts()
```

**Two additional questions:** is there a way to specify simulator noise parameters for each qubit? Which config noise parameter does "Gate error" correspond to? I am trying to replicate the ibmqx4 noise using a simulator.

Many thanks.

**Comment by chriseclectic** [comment] 2018-08-16 18:02
I expect the simulation isn't running because your `U_error` matrix is not unitary (`U.U^dagger[1,1] = 0.996008 !=1` ).  If you change your unitary to use a phase angle like this it should work (and you can also enter the unitary as a complex numpy array)

```python
config = {
    'noise_params': {
        'U': {
            'U_error': np.array([[1, 0], [0, np.exp(1j * 0.05)]])
            }
        }
    }
```

For your other questions there is no way currently to specify noise parameters for each qubit. This is something to look forward to when we release the Qiskit-Aer simulator package later in the year.

If you are trying to model the performance of a device for now you can use the average noise parameters for the qubits and specify it using the "X90", "CX", and "measure" gate errors as described [here](https://github.com/Qiskit/qiskit-terra/tree/master/src/qasm-simulator-cpp#gate-errors).

The difference between the U single-qubit gate error model and the X90 single-qubit gate error model is that the former applies the same error parameters to all single qubit gates, while the later applies the error parameter only to X90 gates in the decomposition of single qubit gates into X90 pulses and Z-rotations (and this is how they are implemented on the actual devices).

**Comment by ajavadia** [comment] 2018-08-17 02:37
@gautierronan see here:
https://github.com/Qiskit/qiskit-backend-information/tree/master/backends/tenerife/V1

At the bottom of the page it says how the error rates are calculated:
> Reported gate errors are measured using simultaneous randomized benchmarking (RB)[^fn2]. RB gives the average error per Clifford gate, which we convert to error per gate according to the set of primitive gates used on QX2.
>[^fn2]: Jay M. Gambetta, A. D. Córcoles, S. T. Merkel, B. R. Johnson, John A. Smolin, Jerry M. Chow, Colm A. Ryan, Chad Rigetti, S. Poletto, Thomas A. Ohki, Mark B. Ketchen, and M. Steffen, Characterization of Addressability by Simultaneous Randomized Benchmarking, Phys. Rev. Lett. 109, 240504.

I'm closing this since the original issue seems to be resolved. Thanks @chriseclectic.

**Comment by gautierronan** [comment] 2018-08-17 10:46
The solution provided by @chriseclectic seemed to work at first. But I am actually running into a very strange phenomenon. 

When running the code provided in my first post, using the config provided by @chriseclectic, I will sometimes get the right result, and sometimes run into an error.
So, for instance, if I run the exact same code 10 times in a row, it will work as expected about 5 times (return `result.get_counts()`), and run into the following error about 5 times : `JSONDecodeError: Expecting value: line 1 column 1 (char 0)`.

I am using a Jupyter notebook, on Windows 10, and QISKit 0.5.6.

Here is the program I use, and the log of the error:
```python
from qiskit import *
q = QuantumRegister(2)
c = ClassicalRegister(2)
circ = QuantumCircuit(q, c)
circ.h(q[0])
circ.cx(q[0], q[1])
circ.measure(q[0], c[0])

config = {
    'noise_params': {
        'U': {
            'U_error': np.array([[1, 0], [0, np.exp(1j * 0.05)]])
            }
        }
    }

sim = 'local_qasm_simulator_cpp'
job = execute(circ, sim, config)
result = job.result()
result.get_counts()
```

```python
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-70-3b2d17aa38b5> in <module>()
     17 sim = 'local_qasm_simulator_cpp'
     18 job = execute(circ, sim, config)
---> 19 result = job.result()
     20 result.get_counts()

~\Anaconda3\lib\site-packages\qiskit\backends\local\localjob.py in result(self, timeout)
     55             concurrent.futures.CancelledError: if job cancelled before completed.
     56         """
---> 57         return self._future.result(timeout=timeout)
     58 
     59     def cancel(self):

~\Anaconda3\lib\concurrent\futures\_base.py in result(self, timeout)
    403                 raise CancelledError()
    404             elif self._state == FINISHED:
--> 405                 return self.__get_result()
    406             else:
    407                 raise TimeoutError()

~\Anaconda3\lib\concurrent\futures\_base.py in __get_result(self)
    355     def __get_result(self):
    356         if self._exception:
--> 357             raise self._exception
    358         else:
    359             return self._result

~\Anaconda3\lib\concurrent\futures\thread.py in run(self)
     53 
     54         try:
---> 55             result = self.fn(*self.args, **self.kwargs)
     56         except BaseException as e:
     57             self.future.set_exception(e)

~\Anaconda3\lib\site-packages\qiskit\backends\local\qasm_simulator_cpp.py in _run_job(self, qobj)
     77     def _run_job(self, qobj):
     78         self._validate(qobj)
---> 79         result = run(qobj, self._configuration['exe'])
     80         return Result(result)
     81 

~\Anaconda3\lib\site-packages\qiskit\backends\local\qasm_simulator_cpp.py in run(qobj, executable)
    221                          cerr.decode())
    222         sim_output = cout.decode()
--> 223         return json.loads(sim_output, cls=QASMSimulatorDecoder)
    224 
    225     except FileNotFoundError:

~\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    365     if parse_constant is not None:
    366         kw['parse_constant'] = parse_constant
--> 367     return cls(**kw).decode(s)

~\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

~\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by gautierronan** [comment] 2018-08-17 10:52
Just to add to this issue. I am running into the same phenomenon with the following config file (only specifying 'p_depol'):
```python
config = {
    'noise_params': {
        'U': {
            'p_depol':0.5
            }
        }
    }
```
So the issue does not come from the U_error matrix I believe.

**Comment by ajavadia** [comment] 2018-08-17 11:14
Ok reopening the issue.

I actually cannot reproduce the error. I run on MacOS. Tried with Qiskit 0.5.6, 0.5.7, and master. They all run successfully, with both of the configs you provided.

Might be a Windows issue. Can someone with Windows please try this code? Tagging @nonhermitian @atilag

**Comment by chriseclectic** [comment] 2018-08-17 13:26
@gautierronan can you find the life `qiskit/backends/local/qasm_simulator_cpp.py` and in the `run` function add a print statement for the raw simulator output (around line 221) and tell us what you see when you get the error.

Change:

```python
sim_output = cout.decode()
return json.loads(sim_output, cls=QASMSimulatorDecoder)
```

to something like

```python
sim_output = cout.decode()
print("*********")
print("DEBUG SIMULATOR OUTPUT:")
print(sim_output)
print("*********")
return json.loads(sim_output, cls=QASMSimulatorDecoder)
```

**Comment by gautierronan** [comment] 2018-08-17 13:55
If the code runs into the error, I am getting this:
```
*********
DEBUG SIMULATOR OUTPUT:
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

*********
```

If the code doesn't run into an error, I am getting this:
```python
*********
DEBUG SIMULATOR OUTPUT:
{'00': 508, '01': 516}

{
    "backend": "qasm_simulator_cpp",
    "cpp_simulator_kernel": "qasm_simulator_cpp",
    "id": "66213dd5-2cc9-4a12-9a3f-a02ebd1ee645",
    "result": [{
        "data": {
            "counts": {
                "00": 508,
                "01": 516
            }
        },
        "name": "circuit2",
        "noise_params": {
            "U": {
                "U_error": [[[1.0, 0.0], [0.0, 0.0]], [[0.0, 0.0], [0.9987502603949663, 0.04997916927067833]]]
            }
        },
        "seed": 4070141082,
        "shots": 1024,
        "status": "DONE",
        "success": true,
        "threads_shot": 4,
        "time_taken": 0.004145
    }],
    "status": "COMPLETED",
    "success": true,
    "time_taken": 0.004172
}

*********
```

**Comment by chriseclectic** [comment] 2018-08-17 14:14
Sounds like somethings up with the windows BLAS library, @atilag @nonhermitian do you have any ideas?

**Comment by cruzpmmq** [comment] 2018-08-18 10:12
You can you try installing [OpenBlas](http://www.openblas.net/) and check if it fixes the problem.

**Comment by nonhermitian** [comment] 2018-08-18 11:36
It seems like this is an issue with spawning openmp threads at the same time that blas wants to create threads. I would try specifying a single openmp thread only for the solver and see if it works. 

On Windows the solver is currentlybuilt against openblas, and there are some openblas solutions to this problem:

https://github.com/xianyi/OpenBLAS/wiki/faq#allocmorebuffers

**Comment by gautierronan** [comment] 2018-08-20 08:48
Thank you for your answer. Could you elaborate on how to achieve this?

**Comment by ajavadia** [comment] 2018-08-20 12:39
@gautierronan try this in your command line interface:
`set OMP_NUM_THREADS=1`

**Comment by gautierronan** [comment] 2018-08-20 13:25
I have tried running the command `set OMP_NUM_THREADS=1` in my cmd before opening Jupyter with the command `jupyter notebook`, and it doesn't seem to make any difference.

I have also tried setting this parameter directly in python with `os.environ["OMP_NUM_THREADS"] = "1"`, both before importing and after importing, but it doesn't work either.

**Comment by nonhermitian** [comment] 2018-08-20 14:42
@chriseclectic can correct me if I am wrong but adding `"max_threads_shot": 1` to the config should do the trick.

**Comment by chriseclectic** [comment] 2018-08-20 14:53
@gautierronan as @nonhermitian said, you need to set it in the config. Try adding `"max_threads_shot": 1,  "max_threads_gate": 1` to the config and let us know how that goes.

If this turns out to be the problem we should figure out how to limit the BLAS operations to use a single thread rather than limit OpenMP. The BLAS operations are only used small matrix multiplications for combining noise operations, while OpenMP is used for all the actual state update functions.

**Comment by gautierronan** [comment] 2018-08-20 14:57
Thank you for your answers. Unfortunately, this does not seem to solve the problem though.

Here is the code and config I am currently using, which still works sometimes and runs into errors sometimes:
```python
q = QuantumRegister(2)
c = ClassicalRegister(2)
circ = QuantumCircuit(q, c)
circ.h(q[0])
circ.cx(q[0], q[1])
circ.measure(q[0], c[0])

config = {
    "shots": 1024,
    "max_threads_shot": 1,
    'max_threads_gate':1,
    'noise_params': {
        'U': {
            'U_error': np.array([[1, 0], [0, np.exp(1j * 0.05)]])
            }
        }
    }

sim = 'local_qasm_simulator_cpp'
job = execute(circ, sim, config)
result = job.result()
result.get_counts()
```

It may be worth noting that if I specify `'shots'=1` instead of `'shots' = 1024`, I do not seem to be running into errors anymore.

**Comment by ajavadia** [comment] 2018-09-06 18:47
Not sure if a fix is available for this, or if anyone is thinking about it? @chriseclectic if you feel this can be resolved through other methods, please jump in. otherwise i think we should close the issue.

**Comment by jaygambetta** [comment] 2018-12-15 06:48
closing as all noise is moving to aer

**Closed** 2018-12-15 06:47 UTC
Labels: type: bug
