### ISSUE TITLE
Two qubit gates don't show the parameter when using matplotlib. 

### ISSUE THREAD

**Issue by toural** [Qiskit/qiskit-terra#4563] opened 2020-06-10 18:19 UTC
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Parametric two qubit gates don't show the parameter when using matplotlib however the parameter is shown when using ASCII representation of the circuit.
Parametric single qubit gates show the parameter properly.

For instance 
RXX gate

### Steps to reproduce the problem

```
from qiskit import *
import numpy as np
circuit = QuantumCircuit(2)
circuit.rxx(np.pi,0,1)
circuit.rx(np.pi,0)
circuit.draw('mpl')
```
![image](https://user-images.githubusercontent.com/19472520/84303509-600a1780-ab57-11ea-837f-880be81d4ff0.png)

![image](https://user-images.githubusercontent.com/19472520/84303566-83cd5d80-ab57-11ea-8264-f0dd757d6212.png)

### What is the expected behavior?

It is expected that the parameter is shown as it is in the single qubit gate 

### Suggested solutions

Include the parameter in the gate representation when using matplotlib

**Comment by 1ucian0** [comment] 2020-06-10 23:27
I'm not fully sure about the expected result. @ajavadia @nonhermitian ?

**Comment by ajavadia** [comment] 2020-06-11 00:04
I think it should. It’s just one angle. In cases where the number of parameters are too many then I think it makes sense to just show the gate name.

**Comment by enavarro51** [comment] 2020-06-11 15:32
Except for the gates with matrices as parameters, all the gates that have parameters display them below the name of the gate in the mpl drawer. To be consistent with other gates, the name should be capital R with subscript xx. This goes for Ryy and Rzx as well.

**Comment by metacubestormerxii12** [comment] 2020-06-11 15:51
Yes I agree. One short param like that definitely should be displayed

**Comment by PaulMcElligott** [comment] 2020-06-15 15:54
Hey @metacubestormerxii12 and @toural, This looks like a good first issue for me. Can I take a look? It's format is close to @aasfaw's Episode 7 https://tinyurl.com/y8yhvg5z.

**Comment by metacubestormerxii12** [comment] 2020-06-15 21:28
I have already fixed this issue, it is just pending review from one of the code owners.

**Comment by metacubestormerxii12** [comment] 2020-06-15 22:11
But yeah ur free to work on it if you would like.

**Comment by Raviraj26** [comment] 2020-07-28 19:43
I would like to work on this if it is still open for some changes

**Comment by Raviraj26** [comment] 2020-07-28 20:32
WEll the problem is solved

**Comment by 1ucian0** [comment] 2020-09-09 21:22
Closing as solved! Thanks

**Closed by 1ucian0** 2020-09-09 21:22 UTC
Labels: bug, good first issue, priority: low, status: pending PR
