### ISSUE TITLE
mpl failure when no label

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4610] opened 2020-06-24 13:51 UTC
Simple matplotlib drawer fails due to labels:

```py
from qiskit.circuit.library import QuantumVolume
qv = QuantumVolume(6, 6, seed=1)
qv.draw('mpl')
```

`AttributeError: 'Instruction' object has no attribute 'label'`

**Comment by Cryoris** [comment] 2020-06-24 14:03
Duplicate of #4439, addressed in the draft PR #4389.

**Closed** 2020-06-24 15:45 UTC
Labels: bug
