### ISSUE TITLE
`transpile` raises `UserWarning` with custom `basis_gates`

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-terra#6744] opened 2021-07-14 05:54 UTC
### What is the expected enhancement?

Information:
- **Qiskit Terra version**: latest
- **Python version**: 3.8.11
- **Operating system**: macOS 11.4

When I executed the following code, the warning message asks me to report it.
The transpilation result looks correct. I don't think it has to raise a warning.

```python
from qiskit import QuantumCircuit, transpile

qc = QuantumCircuit(1)
qc.h(0)
qc2 = transpile(qc, basis_gates=['rx', 'rz', 'h'])
print(qc2)
```

output
```
/Users/ima/tasks/1_2021/qiskit/terra/qiskit/transpiler/runningpassmanager.py:166: UserWarning: Resynthesized [<qiskit.dagcircuit.dagnode.DAGNode object at 0x12f78cd00>] and got global phase: π/2
      ┌─────────┐┌─────────┐┌─────────┐
qr_0: ┤ Rx(π/2) ├┤ Rz(π/2) ├┤ Rx(π/2) ├
      └─────────┘└─────────┘└─────────┘, but the original was native and the new value is longer.  This indicates an efficiency bug in synthesis.  Please report it by opening an issue here: https://github.com/Qiskit/qiskit-terra/issues/new/choose
  new_dag = pass_.run(dag)
     ┌───┐
q_0: ┤ H ├
     └───┘
```

**Comment by kdk** [comment] 2021-08-02 22:12
Closing as duplicate of #6848 .

**Closed by kdk** 2021-08-02 22:12 UTC
Labels: bug, type: enhancement
