### ISSUE TITLE
Draw labels the qubits wrong, when registers are used in QuantumCircuit()

### ISSUE THREAD

**Issue by HTransistor** [Qiskit/qiskit-terra#4046] opened 2020-03-30 12:34 UTC
### Information

- **qiskit-terra 0.12.0**:
- **Python 3.8.2 64-bit**:
- **5.4.28-1-Manjaro**:

### What is the current behavior?
Using Registers in QuantumCircuit(), all qubit labels in the plot done with draw() get the exection number (how many times draw was run) inside the label. 
![register_bug_minimal_example](https://user-images.githubusercontent.com/43704364/77912372-ba067b00-7292-11ea-8f19-8cf0a7c45895.png)

### Steps to reproduce the problem
See explanation screenshot.

### What is the expected behavior?
No execution number in qubit labels, so just q_0, q_1, ...
In the documentation the use of Registers in QuantumCircuit is even shown (is expected to work).
![qcirc_register](https://user-images.githubusercontent.com/43704364/77912716-503aa100-7293-11ea-80e1-1e3d01dad0f4.png)

**Comment by kdk** [comment] 2020-03-30 13:57
Hi @HTransistor , this looks like the expected behavior. Both `QuantumRegister ` and `ClassicalRegister` accept a  `size` and an optional `name`. If the name is empty, it will default to `qN` or `cN` where `N` is an increasing integer (so if you re-build a register, the name will change each time).

To get consistent register names, you can use e.g. `qr = QuantumRegister(2, 'q')`. This doesn't presently show up in the documentation of the `Register` classes, so leaving this open as a documentation bug.

**Comment by 1ucian0** [comment] 2020-04-20 01:58
Closing this as `expected behavior`. Feel free to reopen if disagree to continue the discussion here.

**Closed by 1ucian0** 2020-04-20 01:58 UTC
Labels: bug, type: documentation
