### ISSUE TITLE
Mock Backend options do not get passed to the simulators

### ISSUE THREAD

**Issue by awstasiuk** [Qiskit/qiskit-terra#6754] opened 2021-07-15 19:20 UTC
### Information

- **Qiskit Terra version**: 0.18.0
- **Python version**: 3.9.5
- **Operating system**: Windows 10

### What is the current behavior?
Mock backends, such as `FakeMelbourne` can have their options set via `set_options`, but the instantiated simulator only sees these options if they are passed via kwarg through the `run` method

### Steps to reproduce the problem
Instantiate a mock backend, set options to change number of shots to 100. Running a circuit will then result in the default number of shots (1024).

### What is the expected behavior?
I would hope (and expect) setting the options on a backend would result in the instantiated simulator sharing the same options.

### Suggested solutions
Make simulator backends generated by mock backends share the same options (in particular number of shots) as the backend which instantiates them

**Comment by mtreinish** [comment] 2021-07-15 19:59
Thanks for opening an issue on this, but it's a duplicate of https://github.com/Qiskit/qiskit-terra/issues/6741 which has already been fixed on the `main` branch and backported to the stable branch for an upcoming 0.18.1 release. I'm going to close this accordingly, but please feel free to reopen it if I'm mistaken or there is more to discuss.

**Comment by awstasiuk** [comment] 2021-07-15 20:26
I am aware of the kwarg fix, stumbled into myself while debugging. However, I believe the following is not addressed by the kwarg fix:
```
from qiskit import *
from qiskit.test.mock import FakeMelbourne
backend = FakeMelbourne()

N = 6
qc = QuantumCircuit(N)
qc.x(range(0, N))
qc.h(range(0, N))
for kk in range(N//2, 0, -1):
    qc.ch(kk, kk-1)
for kk in range(N//2, N-1):
    qc.ch(kk, kk+1)
qc.measure_all()

backend.set_options(shots=100)

raw_counts = execute(qc, backend).result().get_counts()

sum(raw_counts.values())
```

I would expect the above code to run the circuit with 100 shots, but I am fairly certain that it will still use the default number of shots, even though `backend.options` would indicate that `shots=100`.

**Comment by mtreinish** [comment] 2021-07-15 20:46
Ah, I misread the issue (based on the title mostly). That's actually a more general issue with `execute` and not isolated to the fake backends or simulators. I actually have a fix proposed for this issue here: https://github.com/Qiskit/qiskit-terra/pull/6693 I'll reopen this and target that PR as fixing this.

**Closed** 2021-08-11 23:02 UTC
Labels: bug
