### ISSUE TITLE
Add conjugate support for QuantumCircuit

### ISSUE THREAD

**Issue by lironmo** [Qiskit/qiskit-terra#8555] opened 2022-08-16 16:26 UTC
### What should we add?

Is it possible to add the conjugate option for QuantumCircuit?

Relatively simple feature, first implementaion gate conjugate for each gate(some gates are symmetric simpley  inverse), then expose conjugate  through the class of the QuantumCircuit(similar to the inverse)

**Comment by jakelishman** [comment] 2022-08-16 18:42
There's been some previous discussion on this here: #7701.  I would say that it's actually quite a bit of work, because all `Instruction` (or at least `Gate`) instances in the circuit library would need to gain `conjugate` methods, which might be tricky for opaque gates.

In the interests of keeping discussion in one place I'll close this as a duplicate, but please feel free to comment on #7701.

**Comment by jakelishman** [comment] 2022-08-16 18:43
Duplicate of #7701

**Closed by jakelishman** 2022-08-16 18:43 UTC
Labels: type: feature request

**Comment by lironmo** [comment] 2022-08-17 08:22
+1
