### ISSUE TITLE
Classical conditions misalign in both ASCII and MPL output

### ISSUE THREAD

**Issue by rootEnginear** [Qiskit/qiskit-terra#7532] opened 2022-01-17 15:27 UTC
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**:  3.7.12
- **Operating system**: Ubuntu 18.04.5 LTS (Google Colab)

### What is happening?

I was testing my automatic code generation for Qiskit, and apparently the ~cphase~ controlled U1 gate with a classical condition will make the circuit misaligns in both of ASCII output and MPL output.

Screenshots:
```
q2_0: ─■───────■───────■───────■───────■───────■───────■───────■───────■──────»
       │U1(0)  │U1(0)  │U1(0)  │U1(0)  │U1(0)  │U1(0)  │U1(0)  │U1(0)  │U1(0) »
q2_1: ─■───────■───────■───────■───────■───────■───────■───────■───────■──────»
       ║       ║       ║       ║       ║       ║       ║       ║       ║      »
q2_2: ─╫───────╫───────╫───────╫───────╫───────╫───────╫───────╫───────╫──────»
      ┌╫─╨──┐ ┌╫─╨──┐ ┌╫─╨──┐ ┌╫─╨──┐ ┌╫─╨──┐ ┌╫─╨──┐ ┌╫─╨──┐ ┌╫─╨──┐ ┌╫─╨───┐»
c2: 5/╡║0x1 ╞═╡║0x3 ╞═╡║0x5 ╞═╡║0x7 ╞═╡║0x9 ╞═╡║0xb ╞═╡║0xd ╞═╡║0xf ╞═╡║0x11 ╞»
      └╫────┘ └╫────┘ └╫────┘ └╫────┘ └╫────┘ └╫────┘ └╫────┘ └╫────┘ └╫─────┘»
«                                                                         »
«q2_0: ─■───────■───────■───────■───────■───────■───────■───────────■─────»
«       │U1(0)  │U1(0)  │U1(0)  │U1(0)  │U1(0)  │U1(0)  │U1(0) ┌────┴────┐»
«q2_1: ─■───────■───────■───────■───────■───────■───────■──────┤ U2(0,0) ├»
«       ║       ║       ║       ║       ║       ║       ║      └────╥────┘»
«q2_2: ─╫───────╫───────╫───────╫───────╫───────╫───────╫───────────╫─────»
«      ┌╫─╨───┐┌╫─╨───┐┌╫─╨───┐┌╫─╨───┐┌╫─╨───┐┌╫─╨───┐┌╫─╨───┐  ┌──╨──┐  »
«c2: 5/╡║0x13 ╞╡║0x15 ╞╡║0x17 ╞╡║0x19 ╞╡║0x1b ╞╡║0x1d ╞╡║0x1f ╞══╡ 0x2 ╞══»
«      └╫─────┘└╫─────┘└╫─────┘└╫─────┘└╫─────┘└╫─────┘└╫─────┘  └─────┘  »
«                                                                        »
«q2_0: ─────■──────────■──────────■──────────■──────────■──────────■─────»
«      ┌────┴────┐┌────┴────┐┌────┴────┐┌────┴────┐┌────┴────┐┌────┴────┐»
«q2_1: ┤ U2(0,0) ├┤ U2(0,0) ├┤ U2(0,0) ├┤ U2(0,0) ├┤ U2(0,0) ├┤ U2(0,0) ├»
«      └────╥────┘└────╥────┘└────╥────┘└────╥────┘└────╥────┘└────╥────┘»
«q2_2: ─────╫──────────╫──────────╫──────────╫──────────╫──────────╫─────»
«        ┌──╨──┐    ┌──╨──┐    ┌──╨──┐    ┌──╨──┐    ┌──╨──┐    ┌──╨──┐  »
«c2: 5/══╡ 0x3 ╞════╡ 0x6 ╞════╡ 0x7 ╞════╡ 0xa ╞════╡ 0xb ╞════╡ 0xe ╞══»
«        └─────┘    └─────┘    └─────┘    └─────┘    └─────┘    └─────┘  »
«                                                                        »
«q2_0: ─────■──────────■──────────■──────────■──────────■──────────■─────»
«      ┌────┴────┐┌────┴────┐┌────┴────┐┌────┴────┐┌────┴────┐┌────┴────┐»
«q2_1: ┤ U2(0,0) ├┤ U2(0,0) ├┤ U2(0,0) ├┤ U2(0,0) ├┤ U2(0,0) ├┤ U2(0,0) ├»
«      └────╥────┘└────╥────┘└────╥────┘└────╥────┘└────╥────┘└────╥────┘»
«q2_2: ─────╫──────────╫──────────╫──────────╫──────────╫──────────╫─────»
«        ┌──╨──┐    ┌──╨───┐   ┌──╨───┐   ┌──╨───┐   ┌──╨───┐   ┌──╨───┐ »
«c2: 5/══╡ 0xf ╞════╡ 0x12 ╞═══╡ 0x13 ╞═══╡ 0x16 ╞═══╡ 0x17 ╞═══╡ 0x1a ╞═»
«        └─────┘    └──────┘   └──────┘   └──────┘   └──────┘   └──────┘ »
«                                       ┌───────────┐┌───────────┐       »
«q2_0: ─────■──────────■──────────■─────┤ U3(0,0,0) ├┤ U3(0,0,0) ├───X───»
«      ┌────┴────┐┌────┴────┐┌────┴────┐└─────┬─────┘└─────┬─────┘   │   »
«q2_1: ┤ U2(0,0) ├┤ U2(0,0) ├┤ U2(0,0) ├──────■────────────■─────────■───»
«      └────╥────┘└────╥────┘└────╥────┘      ║            ║         │   »
«q2_2: ─────╫──────────╫──────────╫───────────╫────────────╫─────────X───»
«        ┌──╨───┐   ┌──╨───┐   ┌──╨───┐    ┌──╨───┐     ┌──╨───┐  ┌──╨──┐»
«c2: 5/══╡ 0x1b ╞═══╡ 0x1e ╞═══╡ 0x1f ╞════╡ 0x15 ╞═════╡ 0x17 ╞══╡ 0x2 ╞»
«        └──────┘   └──────┘   └──────┘    └──────┘     └──────┘  └─────┘»
«                                                           
«q2_0: ───X──────X──────X──────X───────X───────X───────X────
«         │      │      │      │       │       │       │    
«q2_1: ───■──────■──────■──────■───────■───────■───────■────
«         │      │      │      │       │       │       │    
«q2_2: ───X──────X──────X──────X───────X───────X───────X────
«      ┌──╨──┐┌──╨──┐┌──╨──┐┌──╨───┐┌──╨───┐┌──╨───┐┌──╨───┐
«c2: 5/╡ 0x3 ╞╡ 0xa ╞╡ 0xb ╞╡ 0x12 ╞╡ 0x13 ╞╡ 0x1a ╞╡ 0x1b ╞
«      └─────┘└─────┘└─────┘└──────┘└──────┘└──────┘└──────┘
```

![image](https://user-images.githubusercontent.com/7108662/149796254-a6c64c72-0664-467a-8154-5b69959289ed.png)

### How can we reproduce the issue?

Using the source code below:

```python3
from numpy import pi, e as euler
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
from qiskit.circuit.library.standard_gates import SdgGate, TdgGate, SXGate, RXGate, RYGate, RZGate, U1Gate, U2Gate, U3Gate, SwapGate, XGate, YGate, ZGate, HGate, PhaseGate, SGate, TGate

qr = QuantumRegister(3)
cr = ClassicalRegister(5)
qc = QuantumCircuit(qr, cr)

qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 1)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 3)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 5)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 7)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 9)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 11)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 13)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 15)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 17)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 19)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 21)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 23)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 25)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 27)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 29)
qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 31)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 2)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 3)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 6)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 7)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 10)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 11)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 14)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 15)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 18)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 19)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 22)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 23)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 26)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 27)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 30)
qc.append(U2Gate(0, 0).control(1), [0, 1]).c_if(cr, 31)
qc.append(U3Gate(0, 0, 0).control(1), [1, 0]).c_if(cr, 21)
qc.append(U3Gate(0, 0, 0).control(1), [1, 0]).c_if(cr, 23)
qc.append(SwapGate().control(1), [1, 0, 2]).c_if(cr, 2)
qc.append(SwapGate().control(1), [1, 0, 2]).c_if(cr, 3)
qc.append(SwapGate().control(1), [1, 0, 2]).c_if(cr, 10)
qc.append(SwapGate().control(1), [1, 0, 2]).c_if(cr, 11)
qc.append(SwapGate().control(1), [1, 0, 2]).c_if(cr, 18)
qc.append(SwapGate().control(1), [1, 0, 2]).c_if(cr, 19)
qc.append(SwapGate().control(1), [1, 0, 2]).c_if(cr, 26)
qc.append(SwapGate().control(1), [1, 0, 2]).c_if(cr, 27)

qc.draw() # For ASCII output
# qc.draw('mpl') # For MPL output
```

### What should happen?

They should align in a vertical manner.

**Comment by jakelishman** [comment] 2022-01-17 15:49
There is special handling in each of the drawers for certain names in `ControlledGate`, so it's likely that the bug comes in there somewhere.  Notably, `u1` and `p` are handled specially, but `u2` is not; this seems to match with the output images up top.

For ease, a more minimal reproducer:
```python
In [15]: from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
    ...: from qiskit.circuit.library import U1Gate
    ...:
    ...: qr = QuantumRegister(3)
    ...: cr = ClassicalRegister(5)
    ...: qc = QuantumCircuit(qr, cr)
    ...:
    ...: qc.append(U1Gate(0).control(1), [1, 0]).c_if(cr, 1)
    ...: qc.draw()
```
```text
Out[15]:

q1_0: ─■──────
       │U1(0)
q1_1: ─■──────
       ║
q1_2: ─╫──────
      ┌╫─╨──┐
c1: 5/╡║0x1 ╞═
      └╫────┘
```

**Comment by enavarro51** [comment] 2022-01-19 14:56
Oddly enough, I think these two problems are unrelated. The 'mpl' problem seems to be related to a miscalculation in the code that deals with folding. Since the 'text' problem appears with only 1 gate, it can't relate to that. I think it might have to do with the U1/P code as suggested, since it looks like the gate is aligned differently than the condition.

**Comment by enavarro51** [comment] 2022-02-15 15:58
@1ucian0, @javabster The mpl version of this was fixed with #7545. The text issue, which is a very different problem, seems to have existed as far back as I can tell. Apparently cp and rzz gates with conditions are rare. Anyway the fundamental problem is that the sidetext gates, including the label, are centered in the layer, which means the bullet is not aligned with the bullet on the condition, so you get
```
         ┌───┐        
qr_0: ───┤ X ├────────
         └───┘   ┌───┐
qr_1: ─■─────────┤ X ├
       │P(3.333) └───┘
qr_2: ─■──────────────
       ║              
cr_0: ═╬══════════════
       ║   ║          
cr_1: ═╬═══■══════════
       ║          
```
You could move the whole gate over so it's centered on the bullet, but looking around at this, I haven't seen an easy way to do that yet. But then you have the problem of the label pushing the x(1) gate layer over and that also seems non-trivial, but I assume doable.

This all brings up the question of whether these sidetext gates are really necessary. Is this really so bad?
```
q_0: ─────■──────
     ┌────┴─────┐
q_1: ┤ P(3.333) ├
     └──────────┘
```
It would eliminate a lot of messy code and solve #6877 as well. Just a thought.

**Comment by enavarro51** [comment] 2022-02-16 22:51
Ok. @jakelishman @javabster. So is this acceptable if there's a condition? Creates a lot of whitespace, but at least things are lined up and centered. The other two drawers line up the bullets in the layer and then print the text to the right, rather than centering bullets plus text like the text drawer currently does.
```
             ┌───┐            
qr_0: ───────┤ X ├────────────
             └───┘       ┌───┐
qr_1: ─────────■─────────┤ X ├
               │P(3.333) └───┘
qr_2: ─────────■──────────────
               ║              
cr_0: ═════════╬══════════════
               ║              
cr_1: ═════════■══════════════
               
```
We then have a choice of leaving these gates as is for no condition,
```
         ┌───┐        
qr_0: ───┤ X ├────────
         └───┘   ┌───┐
qr_1: ─■─────────┤ X ├
       │P(3.333) └───┘
qr_2: ─■──────────────
                      
cr_0: ════════════════
                      
cr_1: ════════════════
```
or centering all the sidetext gates like the other drawers do.
```
             ┌───┐            
qr_0: ───────┤ X ├────────────
             └───┘       ┌───┐
qr_1: ─────────■─────────┤ X ├
               │P(3.333) └───┘
qr_2: ─────────■──────────────
                           
cr_0: ════════════════════════
                     
cr_1: ════════════════════════
               
```
Let me know which way you want to go, and I'll do a PR.

**Comment by javabster** [comment] 2022-02-18 21:19
I think the first option is fine, if there is a way to fix it so there is less whitespace that would be the best option but if it is too complex I am happy to push this through to at least fix the bug and we can try fix the whitespacing at a later date. In other words: first priority is to fix the bug, and adjusting to have less whitespace would be a nice to have but not essential.

For the other options I would prefer to leave the gates as is with less whitespace. So in this case preserving existing user experience takes precedence over being consistent with the conditional gate style.

Hope my reasoning makes sense! Thanks for addressing this 😄

**Comment by enavarro51** [comment] 2022-02-18 22:02
That was my most likely conclusion as well, so that's what I did in #7673.

**Closed** 2022-02-26 21:56 UTC
Labels: bug
