### ISSUE TITLE
Missing tweedledum as required package

### ISSUE THREAD

**Issue by wagnersj** [Qiskit/qiskit-terra#6333] opened 2021-04-29 20:41 UTC
### Information

- **Qiskit Terra version**: 0.17.0
- **Python version**: 3.8.8
- **Operating system**: linux

### What is the current behavior?
`qiskit.circuit.classicalfunction.BooleanExpression` fails with message that the `tweedledum` library is required. However, `tweedledum` is not listed a requirement for the `qiskit-terra` package.

### Steps to reproduce the problem
Use API's that instantiate the `BooleanExpression` class. E.g.
```
from qiskit.circuit.library import PhaseOracle
oracle = PhaseOracle('x & ~y')  
```
Leads to error:
```
Traceback (most recent call last):
  File "<ipython-input-97-28069418327a>", line 3, in <module>
    oracle = PhaseOracle('x & ~y')               # previous API: qiskit.aqua.components.oracles.LogicalExpressionOracle
  File "/opt/conda/lib/python3.8/site-packages/qiskit/circuit/library/phase_oracle.py", line 55, in __init__
    expression = BooleanExpression(expression)
  File "/opt/conda/lib/python3.8/site-packages/qiskit/circuit/classicalfunction/boolean_expression.py", line 39, in __init__
    raise MissingOptionalLibraryError(
MissingOptionalLibraryError: "The 'tweedledum' library is required to use 'BooleanExpression compiler'. You can install it with 'pip install tweedledum'."
```

### What is the expected behavior?

No error about missing library should happen.

### Suggested solutions

Add `tweedledum` to `./requirements.txt`.

Related to #5853 and #5830 where `tweedledum` is present in `./requirements-dev.txt`, but not added to `./requirements.txt`

**Comment by mtreinish** [comment] 2021-04-29 20:53
Tweedledum is an optional dependency, mostly because it hasn't fully stabilized the python api yet and also because there are some packaging issues for some of our supported platforms. However, it is correctly listed in the setup.py: 

https://github.com/Qiskit/qiskit-terra/blob/main/setup.py#L108

which enables you to install terra with tweedledum using:

```
pip install 'qiskit-terra[classical-function-compiler]'
```

This is also documented, albeit not very clearly worded, in the documentation for the class: https://qiskit.org/documentation/stubs/qiskit.circuit.classicalfunction.BooleanExpression.html#qiskit.circuit.classicalfunction.BooleanExpression

**Comment by peendebak** [comment] 2021-05-03 08:38
@mtreinish I get a similar error message when running tests locally with the command `tox --epy37`. I can install `tweedledum` locally, but that doesn't solve the error message inside the `tox` environment.

**Comment by mtreinish** [comment] 2021-05-04 11:52
> @mtreinish I get a similar error message when running tests locally with the command `tox --epy37`. I can install `tweedledum` locally, but that doesn't solve the error message inside the `tox` environment.

Did you have an existing tox venv created? If you did and it had an old version of tweedledum installed tox may not have pulled in the new requirement on subsequent runs and updated the venv. (this was a longstanding bug in tox with requirements files that I learned recently has been fixed and will be included in the upcoming tox 4.0 release). You can try rebuilding the venv with `tox -epy37 -r` which tells tox to rebuild the virtualenv.

**Comment by peendebak** [comment] 2021-05-04 19:02
@mtreinish I did rebuild with the `-r` option and the problem remained. But I cannot reproduce this now (tests work locally at the moment), so I am not sure what happened.

**Closed** 2021-07-01 14:46 UTC
Labels: bug

**Comment by alvinbengeorge** [comment] 2023-08-17 11:10
`pip install tweedledum` doesn't work, what do I do about this?
