### ISSUE TITLE
Latex drawer does not respect barriers

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#1453] opened 2018-12-07 19:00 UTC
### Informations

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: OSX

### What is the current behavior?
```python
q = QuantumRegister(5,name='q')
c = ClassicalRegister(5, name='c')
qc_bad = QuantumCircuit(q3, c3)

qc_bad.x(q[4])
for kk in range(5):
    qc_bad.h(q[kk])
qc_bad.barrier(q)
qc_bad.cx(q[2], q[4])
qc_bad.cx(q[3], q[4])

qc_bad.barrier(q)
qc_bad.cx(q[2], q[0])
qc_bad.h(q[2])
qc_bad.h(q[0])
qc_bad.cx(q[2], q[0])
qc_bad.h(q[2])
qc_bad.h(q[0])
qc_bad.cx(q[2], q[0])

qc_bad.draw(output='latex')
```
<img width="609" alt="screen shot 2018-12-07 at 1 59 05 pm" src="https://user-images.githubusercontent.com/1249193/49667194-59fa1e80-fa28-11e8-9e26-3b53e10fd2df.png">

vs mpl:

<img width="609" alt="screen shot 2018-12-07 at 1 59 17 pm" src="https://user-images.githubusercontent.com/1249193/49667199-5f576900-fa28-11e8-9090-a80d382f48c5.png">

**Comment by ajavadia** [comment] 2018-12-07 19:04
I think duplicate of https://github.com/Qiskit/qiskit-terra/issues/1124

**Comment by mtreinish** [comment] 2018-12-10 15:52
Yes, this is a duplicate of https://github.com/Qiskit/qiskit-terra/issues/1124 I'm closing this and we can track that there.

**Closed by mtreinish** 2018-12-10 15:52 UTC
Labels: type: bug
