### ISSUE TITLE
Running Grover's algorithm fails with `"aer_simulator_statevector"` backend

### ISSUE THREAD

**Issue by jond01** [Qiskit/qiskit-terra#7558] opened 2022-01-23 17:23 UTC
### Environment

- **Qiskit Terra version**: 0.19.1
- **Python version**: 3.8.5 (probably irrelevant)
- **Operating system**: macOS 12.1

### What is happening?

Running Grover's algorithm fails with the latest version of `qiskit` (with `"aer_simulator_statevector"` backend):
```
  File ".../python3.8/site-packages/qiskit/algorithms/amplitude_amplifiers/grover.py", line 242, in amplify
    max_amplitude_idx = np.where(circuit_results == max_amplitude)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

### How can we reproduce the issue?

The following minimal example is adapted from:
https://github.com/Qiskit/qiskit-terra/blob/a2b9a9b13ab76974cd5509ff6f693c5dec9cc351/test/python/algorithms/test_grover.py#L258-L265
The main change is in setting the backend to `"aer_simulator_statevector"`.

```python
from qiskit import Aer
from qiskit.algorithms import AmplificationProblem, Grover
from qiskit.circuit.library import PhaseOracle

backend = Aer.get_backend("aer_simulator_statevector")

oracle = PhaseOracle("x1 & x2 & (not x3)")
problem = AmplificationProblem(oracle, is_good_state=oracle.evaluate_bitstring)
grover = Grover(quantum_instance=backend, iterations=2)
result = grover.amplify(problem)  # fails here
assert result.oracle_evaluation
assert "011" == result.top_measurement
```

### What should happen?

The code should work as in the previous versions (`qiskit` 0.33.0, `qiskit-terra` 0.19.0).

### Any suggestions?

The problem is in the `Grover.amplify` method:
https://github.com/Qiskit/qiskit-terra/blob/a2b9a9b13ab76974cd5509ff6f693c5dec9cc351/qiskit/algorithms/amplitude_amplifiers/grover.py#L228
`circuit_results` is sometimes a `numpy.ndarray` object (as in the tests) and sometimes a `qiskit`'s `Statevector` object, but the code doesn't differentiate between these cases, and when it is a `Statevector` it fails here:
https://github.com/Qiskit/qiskit-terra/blob/a2b9a9b13ab76974cd5509ff6f693c5dec9cc351/qiskit/algorithms/amplitude_amplifiers/grover.py#L241-L242

**Comment by Cryoris** [comment] 2022-01-24 12:09
I cannot reproduce this error with Terra 0.19.1 and Aer 0.9.0. What version of Qiskit Aer do you have installed?

**Comment by jond01** [comment] 2022-01-24 12:40
My `qiskit-aer` version is 0.10.2 (the latest release)

**Comment by jakelishman** [comment] 2022-01-24 13:49
It's caused by Aer 0.10 - that changed the type saved by `save_statevector` etc to the `qiskit.quantum_info` classes, with a compatibility layer that mostly should have meant that they behaved like Numpy arrays.  In this case, though, the `Statevector.__eq__` method returns a single Boolean, rather than broadcasting like general Numpy arrays.  It's a simple fix - we just need to cast the output of `get_statevector` to a Numpy array if we want to use it with guaranteed Numpy semantics.

**Comment by woodsp-ibm** [comment] 2023-07-12 17:43
I believe #7560 sorted this. In any case QuantumInstance usage by Grover is now deprecated and soon to be removed in favor of using a Sampler primitive. Since I believe this is well outdated I am going to close it.

**Closed** 2023-07-12 18:16 UTC
Labels: bug, mod: algorithms

**Comment by woodsp-ibm** [comment] 2023-07-12 18:51
Seems I got distracted and ended up not closing this despite saying I was! 🤦‍♂️
