### ISSUE TITLE
csdg roundtrip in OpenQASM 2 broken

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#9723] opened 2023-03-03 21:13 UTC
@ryahill1 notices that roundtrip in OpenQASM2 for several gates is broken (Originally posted in https://github.com/Qiskit/qiskit-terra/issues/9559#issuecomment-1424824806)

One of those cases is `qiskit.circuit.library.CSdgGate`:

```python
import qiskit

qc = qiskit.QuantumCircuit(3)
gate = qiskit.circuit.library.CSdgGate()
qc.append(gate, qargs=qc.qubits)

qasm = qc.qasm()
print(qasm)
qc_from_qasm = qiskit.QuantumCircuit.from_qasm_str(qasm)
print(qc_from_qasm)
```
```
qiskit.qasm.exceptions.QasmError: "Cannot find gate definition for 'csdg', line 4 file "
```

**Comment by jakelishman** [comment] 2023-03-03 22:24
Duplicate of #9559

**Closed by jakelishman** 2023-03-03 22:24 UTC
Labels: help wanted
