### ISSUE TITLE
Error when adding gate after circuit.initialize method

### ISSUE THREAD

**Issue by wyqian1027** [Qiskit/qiskit-terra#8954] opened 2022-10-19 15:26 UTC
### Environment

- **Qiskit Terra version**: 0.19.2
- **Python version**: 3.9.6
- **Operating system**: Windows 11

### What is happening?

Failure to run quantum circuit after circuit.initialize() method and any gate, using either statevector or qasm simulator.

The circuit runs when only having an initialize method. But it fails when more gates are appended after the initialization.

### How can we reproduce the issue?

```python3
beta = 0.3
alpha = np.sqrt(1 - abs(beta)**2)
qc = QuantumCircuit(1)
qc.initialize([alpha, beta], 0)
qc.h(0)
qc.measure_all()
qc.draw()
```

![download](https://user-images.githubusercontent.com/42972544/196734170-b8dfa52d-f4a1-4fbe-809e-558060b4cb57.png)

```python3
sv_sim = Aer.get_backend('statevector_simulator')
qasm_sim = Aer.get_backend('qasm_simulator')
execute(qc, qasm_sim).result().get_counts()
```
![image](https://user-images.githubusercontent.com/42972544/196734414-23edb38f-6edb-424c-accd-dcaf68e9c20a.png)
...
![image](https://user-images.githubusercontent.com/42972544/196734476-2a53d6a5-b4dc-4515-9e9d-f68861bc56f3.png)

### What should happen?

I would imagine we can initialize a state and apply any gate we want to it. Here, this code block should get a Python dictionary of measurement counts.

### Any suggestions?

The second param of initialize() method can also be a bit misleading, causing ambiguity when reading the doc, since one may natively think "qubits" as the number of qubits. But I think I get the intention now.

![image](https://user-images.githubusercontent.com/42972544/196735038-9f81da05-e330-46d2-809b-3bb871bb14fa.png)

**Comment by jakelishman** [comment] 2022-10-19 15:37
Could you try upgrading your version of Terra, and seeing if the bug persists?  You've got a pretty old version (0.19.2) compared to the current 0.22.0.

(For what it's worth, I ran this:
```python
from qiskit import QuantumCircuit, Aer, execute

beta = 0.3
alpha = np.sqrt(1 - abs(beta)**2)
qc = QuantumCircuit(1)
qc.initialize([alpha, beta], 0)
qc.h(0)
qc.measure_all()
qc.draw()

sv_sim = Aer.get_backend('statevector_simulator')
qasm_sim = Aer.get_backend('qasm_simulator')
execute(qc, qasm_sim).result().get_counts()
```
with Terra 0.22.0 and Aer 0.11.0 and got
```text
{'1': 197, '0': 827}
```
which looks about right to me.)

**Comment by wyqian1027** [comment] 2022-10-19 15:41
> Could you try upgrading your version of Terra, and seeing if the bug persists? You've got a pretty old version (0.19.2) compared to the current 0.22.0.
> 
> (For what it's worth, I ran this:
> 
> ```python
> import numpy as np
> from qiskit import QuantumCircuit, Aer, execute
> 
> beta = 0.3
> alpha = np.sqrt(1 - abs(beta)**2)
> qc = QuantumCircuit(1)
> qc.initialize([alpha, beta], 0)
> qc.h(0)
> qc.measure_all()
> qc.draw()
> 
> sv_sim = Aer.get_backend('statevector_simulator')
> qasm_sim = Aer.get_backend('qasm_simulator')
> execute(qc, qasm_sim).result().get_counts()
> ```
> 
> with Terra 0.22.0 and Aer 0.11.0 and got
> 
> ```
> {'1': 197, '0': 827}
> ```
> 
> which looks about right to me.)

Thanks a million, I will do so right away!

**Comment by jakelishman** [comment] 2022-10-19 15:57
Glad to hear it!  Let us know if it works (or doesn't) so we can close the issue / fix the bug as appropriate.

**Comment by wyqian1027** [comment] 2022-10-19 16:05
> Glad to hear it! Let us know if it works (or doesn't) so we can close the issue / fix the bug as appropriate.

Thanks. I have tried upgrading my qiskit to the version that is suggested but it did not work. Then I created a new Conda environment, and installed from scratch. It still did not work, with the same error message, as above, complaining about the reset instruction.

![image](https://user-images.githubusercontent.com/42972544/196744794-5c34ac09-800e-4edd-936a-30c7b55b0001.png)

I have also attached the results from %qiskit_version_table
![image](https://user-images.githubusercontent.com/42972544/196744932-6ee0b115-5ee1-44db-975e-99f93dd44f67.png)

**Comment by jakelishman** [comment] 2022-10-19 17:05
Something looks odd here - the files / line numbers in your traceback are consistent with Terra 0.19.2 still, not 0.22.0, despite what the version table says.  I think somewhere along the lines, your environments must have got mixed up, or perhaps you're using both pip and conda somehow?  At any rate, right now, it looks like the issue is with your local Python setup somehow or another, which isn't something I can massively help with, sorry.

**Comment by wyqian1027** [comment] 2022-10-19 19:54
> Something looks odd here - the files / line numbers in your traceback are consistent with Terra 0.19.2 still, not 0.22.0, despite what the version table says. I think somewhere along the lines, your environments must have got mixed up, or perhaps you're using both pip and conda somehow? At any rate, right now, it looks like the issue is with your local Python setup somehow or another, which isn't something I can massively help with, sorry.

Thanks for the help regardless. I was using conda to create an environment, then pip to install qiskit and related packages. I can try use venv to create an environment instead and see how that goes.

**Comment by wyqian1027** [comment] 2022-10-19 21:33
At this point, I am not sure why. I followed the official installation https://qiskit.org/documentation/stable/0.39/getting_started.html

My Ubuntu machine works fine, but the Windows machine does not work. At least one of them is working.

Ubuntu (python 3.10.6): "conda list":
![image](https://user-images.githubusercontent.com/42972544/196808668-53141c43-21f9-425c-a6ce-ee7b25d3619c.png)

Windows (python 3.8.13): "conda list":
![image](https://user-images.githubusercontent.com/42972544/196808606-acaf967b-11ba-4902-8998-32f56ff8cf96.png)

**Closed** 2022-10-23 15:24 UTC
Labels: bug
