### ISSUE TITLE
credentials failed for qiskit ver 0.6.1

### ISSUE THREAD

**Issue by balewski** [Qiskit/qiskit-terra#1098] opened 2018-10-14 17:13 UTC
### Informations

- **Qiskit Terra version**: 0.6.1
- **Python version**: 3.7.0
- **Operating system**:MAC OSX 10.13.6 

### What is the current behavior?
After I acquired fresh token from https://quantumexperience.ng.bluemix.net/qx/account/advanced
IBMQ.load_accounts() fails.

### Steps to reproduce the problem
```
from qiskit import IBMQ
myToken='b6abe11442c9a...'
IBMQ.save_account(myToken)
IBMQ.load_accounts()
```
Results with
```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/qiskit/backends/ibmq/ibmqsingleprovider.py", line 71, in _authenticate
    credentials.verify)
  File "/anaconda3/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 478, in __init__
    self.req = _Request(token, config=config, verify=verify)
  File "/anaconda3/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 253, in __init__
    ntlm_credentials=self.ntlm_credentials)
  File "/anaconda3/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 95, in __init__
    self.obtain_token(config=self.config)
  File "/anaconda3/lib/python3.7/site-packages/IBMQuantumExperience/IBMQuantumExperience.py", line 159, in obtain_token
    raise CredentialsError('error during login: %s' % error_message)
IBMQuantumExperience.IBMQuantumExperience.CredentialsError: error during login: Wrong user or password, check your credentials.
```

### What is the expected behavior?
Would be better if  IBMQ.load_accounts() accepted me. All worked well w/ ver 0.5.

**Comment by jaygambetta** [comment] 2018-10-14 18:30
Can you try enable_account or regenerating a token.

**Comment by pacomf** [comment] 2018-10-15 13:17
I cant reproduce the bug, i regenerate my APIToken and it works fine using qiskit terra... is it still happening? Can you send me more details?

**Comment by jaygambetta** [comment] 2018-10-15 13:30
It happened for about 5 hours on the weekend. However, @nonhermitian could run at the same time and then it started working again.

**Comment by pacomf** [comment] 2018-10-15 13:31
Mmmm, maybe an issue in IBM Cloud... we will investigate it

**Comment by nonhermitian** [comment] 2018-10-15 13:47
I will add that, when it happened to me, I could log into some accounts and not others.

**Comment by balewski** [comment] 2018-10-16 17:45
Hi @jaygambetta,
your tip helped. IBMQ.stored_accounts() has returned some  old token, not the new one.
Looks like IBMQ.save_account(myToken) is unable to replace token if it exist - I leave it to you to decide if it is a bug or a feature.
My hack around it is to execute first: IBMQ.delete_accounts()
to clear my old token. So this sequence always works:
`
IBMQ.delete_accounts()
myToken='b6abe11442c9a...'
IBMQ.save_account(myToken)
IBMQ.load_accounts()
`
I can move on, closing thus ticket.
Thanks for help
Jan

**Comment by ajavadia** [comment] 2018-10-16 17:59
Let's leave this open and investigate whether there's a bug with `IBMQ.save_account()` re-writing old tokens.
@diego-plan9 can you please have a look?

**Comment by balewski** [comment] 2018-10-23 12:58
From external user perspective:

It happens rather often  that the ibmq_16_melbourne or even sometimes ibmqx4 does not accept the job, throws some 'general error', despite your web-page says both hardwares are operational.
Then, it is natural to (wrongly?) guess perhaps my token is invalid.
Then, I'd ask for a new token and try to use it - hoping it will help.
For such train of though  the natural solution  is assume 'user knows what he wants'. If user wants to replace the token by calling save_account(), just replace it. You can issue a warning that there was an old token (still valid), but why not just replace token each time user calls IBMQ.save_account(myToken) ?
Would this have any negative effect on your end? 
Thanks
Jan

**Comment by jaygambetta** [comment] 2018-11-03 14:40
@ajavadia is there an update.

**Comment by balewski** [comment] 2018-11-10 01:54
Hi,
there is some inconsistency between the devices status you show here:
https://quantumexperience.ng.bluemix.net/qx/account/advanced
and actual avaliability.
At this moment, both ibmqx4 and ibmq_16_melbourne are reported to work.

However,. when I try to submit my circuit using  Qiskit ver: 0.6.1 I get the error below for either.

Got a 400 code response to https://quantumexperience.ng.bluemix.net/api/Jobs?access_token=VCgYWnMUUBaYeT5gSmGO14cX93Foo4rccsLUVvIjf3bwYEZNjxlDcRmPArS2wZ25: {"error":{"status":400,"message":"Generic error","code":"GENERIC_ERROR"}}

Note, my token is correct, because I can submit the circuit to your simulator
 'backend': 'ibmq_qasm_simulator',
 'jobId2': '1814808',
 'startTime': '2018-11-09 17:53:28'}

Can you have a look ?
Thanks
Jan

**Comment by ajavadia** [comment] 2018-11-19 08:29
@balewski the "GENERIC ERROR" you see is intermittent behavior on the cloud API, I think. You don't see it consistently right? It should be unrelated to the original issue. 

The original issue about overwriting old credentials is addressed in PR #1295.

**Closed** 2018-11-19 12:57 UTC
Labels: priority: high, type: bug

**Comment by yriyat** [comment] 2020-01-31 23:05
Hi guys - I think I am having a similar issue, and I can't tell from what is written above whether or not this was finally resolved. This is my code:

`from qiskit import IBMQ
IBMQ.save_account('0b...')
provider = IBMQ.load_account()`

And here is the error:
`Credentials already present. Set overwrite=True to overwrite.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/session.py in request(self, method, url, bare, **kwargs)
    206             response = super().request(method, final_url, **kwargs)
--> 207             response.raise_for_status()
    208         except RequestException as ex:

~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 401 Client Error: Unauthorized for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken

The above exception was the direct cause of the following exception:

RequestsApiError                          Traceback (most recent call last)
<ipython-input-4-7f025286a27c> in <module>
      1 from qiskit import IBMQ
      2 IBMQ.save_account('0b813e58115d8ca7f13ce0da4bc56e2bcfd5384450581999dffc80a92d47900b5f2a1fed7558de1bcb6fbcc156e2ef65222fae8afec7fe43c38e814a47dc2308')
----> 3 provider = IBMQ.load_account()

~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/ibmqfactory.py in load_account(self)
    149             self.disable_account()
    150 
--> 151         self._initialize_providers(credentials)
    152 
    153         # Prevent edge case where no hubs are available.

~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/ibmqfactory.py in _initialize_providers(self, credentials)
    350         auth_client = AuthClient(credentials.token,
    351                                  credentials.base_url,
--> 352                                  **credentials.connection_parameters())
    353         service_urls = auth_client.current_service_urls()
    354         user_hubs = auth_client.user_hubs()

~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/clients/auth.py in __init__(self, api_token, auth_url, **request_kwargs)
     40 
     41         self.client_auth = Auth(RetrySession(auth_url, **request_kwargs))
---> 42         self.client_api = self._init_service_clients(**request_kwargs)
     43 
     44     def _init_service_clients(self, **request_kwargs: Any) -> Api:

~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/clients/auth.py in _init_service_clients(self, **request_kwargs)
     52         """
     53         # Request an access token.
---> 54         access_token = self._request_access_token()
     55         # Use the token for the next auth server requests.
     56         self.client_auth.session.access_token = access_token

~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/clients/auth.py in _request_access_token(self)
     74         """
     75         try:
---> 76             response = self.client_auth.login(self.api_token)
     77             return response['id']
     78         except RequestsApiError as ex:

~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/rest/auth.py in login(self, api_token)
     37         """
     38         url = self.get_url('login')
---> 39         return self.session.post(url, json={'apiToken': api_token}).json()
     40 
     41     def user_info(self) -> Dict[str, Any]:

~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/requests/sessions.py in post(self, url, data, json, **kwargs)
    579         """
    580 
--> 581         return self.request('POST', url, data=data, json=json, **kwargs)
    582 
    583     def put(self, url, data=None, **kwargs):

~/Desktop/Anaconda/anaconda3/envs/qiskit/lib/python3.7/site-packages/qiskit/providers/ibmq/api/session.py in request(self, method, url, bare, **kwargs)
    224                 self._modify_chained_exception_messages(ex)
    225 
--> 226             raise RequestsApiError(message) from ex
    227 
    228         return response

RequestsApiError: '401 Client Error: Unauthorized for url: https://auth.quantum-computing.ibm.com/api/users/loginWithToken. Login failed., Error code: 3446.'`

When I use the workaround delete_accounts mentioned above, I also get an error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-427d46ad1ea4> in <module>
----> 1 IBMQ.delete_accounts()
      2 myToken='0b813e58115d8ca7f13ce0da4bc56e2bcfd5384450581999dffc80a92d47900b5f2a1fed7558de1bcb6fbcc156e2ef65222fae8afec7fe43c38e814a47dc2308'
      3 IBMQ.save_account(myToken)
      4 IBMQ.load_accounts()

AttributeError: 'IBMQFactory' object has no attribute 'delete_accounts'`

**Comment by yriyat** [comment] 2020-01-31 23:12
I read up on #1295. Am I supposed to add 'overwrite=true' as code somewhere? I was not clear on how to add that parameter. Thank you.

**Comment by balewski** [comment] 2020-01-31 23:33
yes, do this once (comment out for the 2nd and later executions of the same script):
IBMQ.save_account(myToken,overwrite=True)
where myToken is this long authorization string
Jan
