### ISSUE TITLE
Cannot build a circuit from qasm with an ecr gate

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5536] opened 2020-12-16 11:15 UTC
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
In trying to build a circuit from qasm using an ecr gate:

```python
['OPENQASM 2.0;',
 'include "qelib1.inc";',
 'gate ecr q0, q1 { U(3*pi/2, pi, pi) q0; U(pi/2, pi/2, 3*pi/2) q1; CX q0, q1; }',
 'qreg q[2];',
 'creg meas[2];',
 'h q[0];',
 'ecr q[0],q[1];',
 'barrier q[0],q[1];',
 'measure q[0] -> meas[0];',
 'measure q[1] -> meas[1];',
 '']

QuantumCircuit.from_qasm_str(qasm_str)
```

I get the following error:
```
 File "/opt/conda/lib/python3.7/site-packages/qiskit/converters/ast_to_dag.py", line 401, in _gate_rules_to_qiskit_circuit
    op = self._create_op(child_op.name, params=eparams)
AttributeError: 'UniversalUnitary' object has no attribute 'name'
```

**Comment by kdk** [comment] 2020-12-16 23:09
Looks like `.name` is never set for the built-in `Cnot` and `UniversalUnitary` classes (so, this works if `U`/`CX` are replaced with `u`/`cx`). Any idea why @1ucian0 ?

**Comment by francabrera** [comment] 2020-12-18 12:39
in addition to that, should this gate be included in the `qelib1.inc` https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qasm/libs/qelib1.inc being a basis gate?

**Comment by 1ucian0** [comment] 2021-06-15 12:46
I think the problem is about scoping. The following works:
```
qasm_str = '\n'.join(['OPENQASM 2.0;',
                      'include "qelib1.inc";',
                      'qreg q[2];',
                      'U(3*pi/2, pi, pi) q[0];',
                      'CX q[0], q[1];',
                      ''])

print(QuantumCircuit.from_qasm_str(qasm_str))
```

**Comment by 1ucian0** [comment] 2021-06-15 12:48
> in addition to that, should this gate be included in the `qelib1.inc` https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/qasm/libs/qelib1.inc being a basis gate?

We are moving towards leaving `qelib1.inc` fixed, following the paper definition. See #4312 and #6125

**Closed** 2023-05-09 16:24 UTC
Labels: bug
