### ISSUE TITLE
Cannot call to_gate() if circuit contains (unitary) Instruction instance

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-terra#4011] opened 2020-03-24 15:20 UTC
### Information

- **Qiskit Terra version**: 0.12.0
- **Python version**: 3.7.5
- **Operating system**: macOS catalina

### What is the current behavior?

If a circuit contains an `Instruction` instance it cannot be converted to a `Gate` even if all instructions are unitary. This is important to also enable e.g. `control()` or `power()` on a circuit, which are currently only supported for `Gate` types.

### Steps to reproduce the problem

```python
>>> circuit = QuantumCircuit(1)
>>> circuit.x(0)
>>> other.append(circuit.to_instruction(), [0])
>>> other.to_gate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jul/Work/Qiskit/qiskit-terra/qiskit/circuit/quantumcircuit.py", line 601, in to_gate
    return circuit_to_gate(self, parameter_map)
  File "/Users/jul/Work/Qiskit/qiskit-terra/qiskit/converters/circuit_to_gate.py", line 51, in circuit_to_gate
    raise QiskitError('One or more instructions in this instruction '
qiskit.exceptions.QiskitError: 'One or more instructions in this instruction cannot be converted to a gate'
```

### What is the expected behavior?

A circuit should be castable to a gate if all operations are unitary, independent of whether they are wrapped in a `Instruction`.

### Suggested solutions

When a circuit is converted to a gate the instructions should be unrolled to check whether they are unitary.

**Comment by mantcep** [comment] 2020-05-24 16:35
Hi, I would like to try solving this as my first contribution, would that be fine? And if I could pick this up, could you let me know what would be the best way to unroll the instructions and check whether they are unitary?

**Comment by Cryoris** [comment] 2020-05-26 10:09
Hi @mantcep, great that you're interested! 

I had a look at this issue during another project, my current solution tries to unroll the instructions in the circuit until only `Gate` types are left, or raises an error if an instruction cannot be further decomposed. It looks like this:
```python
    unrolled_definition = []
    to_process = circuit.data[::-1]  # reverse to always pop from the end
    while len(to_process) > 0:
        inst, qargs, _ = to_process.pop(-1)  # get the next instruction
        if isinstance(inst, Gate):  # append if Gate
            unrolled_definition.append([inst, qargs, []])
        else:  # otherwise try unrolling
            if inst.definition is not None:
                to_process += inst.definition
            else:
                raise QiskitError(('One or more instructions cannot be converted to'
                                   ' a gate. "{}" is not a gate instruction').format(inst.name))
```
Is this something similar to what you had in mind?

My main concern here is performance though, I'm not sure if this could affect current code because we potentially do more unrolling. @mtreinish what do you think? Is it possible to run performance tests on PR branches (referring to the airspeed graphs).

**Comment by mantcep** [comment] 2020-05-27 18:41
Hi @Cryoris!

To be honest, I am quite new to Qiskit, so I did not really have a solution in mind. I wanted to start contributing to Qiskit by fixing issues and this issue just seemed really interesting to me. I was hoping I could get some guidance or figure it out when going into the details. Could I still contribute to it in some way even with limited knowledge? Also, since you already worked on this issue, is it already on the pipeline to be implemented by you? If not, I would be more than glad to try applying the solution you suggested and seeing how far I could get with that. Let me know if I could contribute in some way.

**Comment by Cryoris** [comment] 2020-05-28 14:24
You certainly can contribute! All issues labeled as [good first issue](https://github.com/Qiskit/qiskit-terra/labels/good%20first%20issue) are potential candidates if you want to start contributing. Your time is probably better invested in a new issue, than this one so we're not doing duplicate work 🙂 
How about this one for example: https://github.com/Qiskit/qiskit-terra/issues/4349 ? I don't think this is actively being worked on.

**Comment by mantcep** [comment] 2020-05-28 17:24
Thank you very much for guidance and for pointing me to the other issue! I will pick that one up instead then 🙂

**Comment by ezerc** [comment] 2021-01-29 11:48
Hello everyone, has this issue been solved? I just happened to stumble upon it while trying to build a modular adder gate

**Comment by abdi-alasow** [comment] 2021-02-21 11:13
I have similar issue, is there any solution or suggestion about this issue ?

**Comment by Cryoris** [comment] 2021-02-22 07:42
We haven't yet started working on this issue, however there are two workarounds. To understand these, note that to Qiskit everything that is of type `Gate` is unitary and thus allows for operations like `power`, `control`, `inverse` but anything that is of the `Instruction` type is not guaranteed to be unitary and doesn't allow these operations.

1. Avoid casting unitary operations to `Instruction`, but make sure they're `Gate` types. E.g.
```python
# unitary operation that we want to put into a larger circuit
sub = QuantumCircuit(2)
sub.x(0)
sub.cx(0, 1)

# explicitly cast to gate so that append doesn't cast it to instruction
sub_gate = sub.to_gate()  

circuit = QuantumCircuit(5)
circuit.append(sub_gate, [2, 4])

# alternatively we can use compose, this copies the operations directly (X and CX)
circuit.compose(sub, [2, 4], inplace=True)
```

2. If you know your circuit is unitary, you can transpile it to unitary gates, then the circuit will be unitary.
```python
sub = QuantumCircuit(2)
sub.x(0)
sub.cx(0, 1)

circuit = QuantumCircuit(5)
# now we have an instruction (non-unitary) in the circuit!
circuit.append(sub, [2, 4])

# transpile to unitary gates 
gates = ['u', 'p', 'x', 'y', 'z', 'h', 'rx', 'ry', 'rz', 's', 'sdg', 't', 'tdg', 'sx', 'sxdg', 'cx']
unitary = transpile(circuit, basis_gates=gates, optimization_level=0)
```

**Comment by Cryoris** [comment] 2021-04-01 12:12
Outcome of the discussion on a possible (but now abandoned) PR: `Instruction` should have a `to_gate` method. https://github.com/Qiskit/qiskit-terra/pull/4520#issuecomment-638360555

**Comment by jakelishman** [comment] 2023-04-19 23:18
In the interests of closing issues, I'm going to close this as "not a bug".  Calling `to_instruction` on an object is explicitly saying that you want it treated as a non-unitary operation.  It's correct and type-safe for subsequent attempts to treat it as unitary to fail with an error.

If there's more discussion to be had around having a method for potentially raising an `Instruction` to gate (if allowable), please feel free to continue that in a new issue.

**Closed by jakelishman** 2023-04-19 23:18 UTC
Labels: bug
