### ISSUE TITLE
plot_gate_map and plot_circuit_layout don't work for backend 'ibmq_16_melbourne'

### ISSUE THREAD

**Issue by mbuchberger1967** [Qiskit/qiskit-terra#3692] opened 2020-01-06 22:12 UTC
the visualization functions plot_gate_map  and plot_circuit_layout do not draw an image if you select 'ibmq_16_melbourne' as the backend. They work correctly for other backends.

`from qiskit.visualization import plot_histogram, plot_gate_map, plot_circuit_layout`
`from qiskit.tools.monitor import job_monitor`
`import matplotlib.pyplot as plt`
`%matplotlib inline`
`backend = provider.get_backend('ibmqx2')`
`plot_gate_map(backend, plot_directed=True)`

draws
![plot_gate_map_ibmqx2](https://user-images.githubusercontent.com/25125667/71852219-86271980-30d8-11ea-9ebe-2321f32f60aa.png)

`backend = provider.get_backend('ibmq_16_melbourne')`
draws
![plot_gate_map_ibm_16_melbourne](https://user-images.githubusercontent.com/25125667/71852473-0fd6e700-30d9-11ea-960e-ba555f829b46.png)

The same issue for 
`from qiskit.compiler import transpile`
`new_circ_lv0 = transpile(circuit, backend=provider.get_backend('ibmqx2'), optimization_level=0)`
`plot_circuit_layout(new_circ_lv0, backend)`
draws
![plot_circuit_layout_ibmqx2](https://user-images.githubusercontent.com/25125667/71852644-7fe56d00-30d9-11ea-9f38-518cd621804b.png)
and `provider.get_backend('ibm_16_melbourne')` draws
![plot_circuit_layout_ibm_16_melbourne](https://user-images.githubusercontent.com/25125667/71852691-a1deef80-30d9-11ea-93aa-25d67760ebbb.png)

**Comment by mtreinish** [comment] 2020-01-06 22:19
This is a known issue caused by a recent change in the coupling map of melbourne (adding a 15th qubit). It has been fixed on master with https://github.com/Qiskit/qiskit-terra/pull/3677 and has been backported to `stable/0.11` (see https://github.com/Qiskit/qiskit-terra/pull/3679) and will be included in a 0.11.1 bugfix release.

I'm going to close this issue since it has already been fixed. If I'm missing something please feel free to reopen.

**Closed by mtreinish** 2020-01-06 22:19 UTC

**Comment by mbuchberger1967** [comment] 2020-01-06 22:20
I just wanted to add my version info
{'qiskit-terra': '0.11.0',
 'qiskit-aer': '0.3.4',
 'qiskit-ignis': '0.2.0',
 'qiskit-ibmq-provider': '0.4.4',
 'qiskit-aqua': '0.6.1',
 'qiskit': '0.14.0'}

thank you. I'll wait for the fix.
