### ISSUE TITLE
RuntimeWarning: Could not import the Aer provider

### ISSUE THREAD

**Issue by ThePrez** [Qiskit/qiskit-terra#3183] opened 2019-10-02 21:35 UTC
### Information

- **Qiskit Terra version**: 0.9.0
- **Python version**: 3.6.8
- **Operating system**: IBM i

### What is the current behavior?
```
python3 -c 'import qiskit'
/QOpenSys/pkgs/lib/python3.6/site-packages/qiskit/__init__.py:56: RuntimeWarning: Could not import the Aer provider from the qiskit-aer package. Install qiskit-aer or check your installation.
  RuntimeWarning)
```

### Steps to reproduce the problem
`python3 -c 'import qiskit'`

### What is the expected behavior?
successful import without warnings

### Suggested solutions
`__init.py__` is out of sync with the new Aer provider name and this needs to be corrected

**Comment by mtreinish** [comment] 2019-10-02 22:36
Please see my comment on your PR: https://github.com/Qiskit/qiskit-terra/pull/3184#issuecomment-537708855 this was intended to be aer. For more background information you can also refer to the PR which added this here: https://github.com/Qiskit/qiskit-terra/pull/2842 (and the multiple issues that reference it later). The real fix for this warning is to abandon namespace packaging for qiskit. But that is larger in scope than just terra and effects all the qiskit packages so it's being tracked in the meta-repository here: https://github.com/Qiskit/qiskit/issues/559

I'm going to close this accordingly, but please feel free to reopen this issue if you think that I'm missing something or there is more to discuss on this.

**Closed by mtreinish** 2019-10-02 22:36 UTC
