### ISSUE TITLE
transpile fails with delays

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#10393] opened 2023-07-06 12:19 UTC
### Environment

- **Qiskit Terra version**:  latest
- **Python version**: 
- **Operating system**: 

### What is happening?

```python

delay_in_dt = int(1125000.0)

qc = QuantumCircuit(127, name='hello')
qc.delay(delay_in_dt, range(127))

out = transpile(qc, backend, optimization_level=0)
```

gives:

TranspilerError: 'The input circuit None is not scheduled. Call one of scheduling passes before running the ConstrainedReschedule pass.'

### How can we reproduce the issue?

run above on a 127 backend

### What should happen?

it should work

**Comment by jakelishman** [comment] 2023-07-06 12:32
Duplicate of #8985

**Closed by jakelishman** 2023-07-06 12:32 UTC
Labels: bug
