### ISSUE TITLE
Terra tests fail if Aqua installed.

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3863] opened 2020-02-19 10:55 UTC
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?
We have seen this before, but I thought it was fixed.  

```
qiskit.aqua.aqua_error.AquaError: 'A qubit or int is expected for the control.'
```

**Comment by Cryoris** [comment] 2020-02-19 11:59
This is due to the multicontrolled gates being in both elements. I'll open a PR to remove them.

**Comment by Cryoris** [comment] 2020-03-02 16:17
This should be fixed, @nonhermitian do you mind testing if the issue is resolved for you as well?

**Comment by Cryoris** [comment] 2020-04-18 16:20
Closing this as it seems to be resolved.

**Closed by Cryoris** 2020-04-18 16:20 UTC
Labels: bug
