### ISSUE TITLE
Efficiency Bug

### ISSUE THREAD

**Issue by anormanhogan** [Qiskit/qiskit-terra#7352] opened 2021-12-03 16:30 UTC
### Environment

- **Qiskit Terra version**:  0.18.3
- **Python version**:  3.8
- **Operating system**:  Mac OS Monterey 12.0.1

### What is happening?

My quantum circuit's gates are inefficiently transpiling, causing my x sx gates to become rz sx rz gates. This brings my gates from 2->3 introducing noise
![image](https://user-images.githubusercontent.com/94230896/144637361-23433162-8934-465d-8224-e4be4ff69256.png)

### How can we reproduce the issue?

```
    qc.barrier()
    qc.cx(0, 1)
    qc.barrier()

    qc.x(0)

    qc.sx(0)

    qc.barrier()
    qc.cx(0, 2)
    qc.barrier()
```

### What should happen?

The transpiler should see if there is a more efficient way to create the circuit (if possible)

**Comment by levbishop** [comment] 2021-12-03 17:26
Thanks for the report. In this case the warning was overzealous and we muted it with #7124 
For most hardware (eg IBM platforms) rz.sx.rz is actually preferable to x.sx because rz is an instantaneous frame-update (which introduces no error) as opposed to x and sx which actually cause drive pulses to be emitted and these do introduce error.
There ongoing work to more properly handle tolerances and noise for 1-qubit gates in #7084 and once that merges we will likely re-enable a corrected version of the check that produced the warning you saw.

Closing as duplicate of #7224 but re-open if I missed something.

**Comment by anormanhogan** [comment] 2022-02-11 16:44
Hey! I'm following up on this since the error seems to have come back. Is there a way to mute it, as the output for long circuits greatly increases run time?

**Comment by jakelishman** [comment] 2022-02-16 16:54
Do you have a reproducer for the new error?  As far as I know, nothing new should have changed in the 0.19.2 release that happened right before you wrote your comment, so it'd be good to know what's causing it.  Are you using the latest version of Terra?

**Comment by anormanhogan** [comment] 2022-02-17 13:02
Hi Jake,

I just checked and I am actually not running the latest version like I thought; I’m actually on version 0.18.3.

As far as what causes the error, I think its when I use the sx gate just before an x gate, which ends up transpiling to rz sx rz reguardless of what backend is chosen. It’s hard to tell exactly where it’s happening since I am randomizing the placement of Pauli gates in a circuit containing an sx gate, but I am fairly certain it is that exact combination that causes it, since the message outputs for every occurrence of this in the circuit.

Thank you for your response!

Best,

Norman Hogan
Research Assistant
Fermilab Theory Division
***@***.*** | +1 (262) 496-2743

**Comment by jakelishman** [comment] 2022-02-17 14:04
Ok, in that case I think it's the same situation we were in before - Terra 0.19 should no longer be issuing those warnings, which hopefully should fix your immediate run-time issues. Please let us know if that's not the case by opening a new issue, since that would be a new bug.

What Lev said before about RZ and Z being effectively error-free on all hardware (that I can think of) still holds true - they're essentially equivalent to adding some phase offsets into the control fields, which is just a numerical trick on the classical side.  In theory, the transpiler should be correct from a noise standpoint to do what it's currently doing.

I'm not certain what the status of the work on making the synthesis cleverer about noise in non-standard cases here is - #7084 seems to have stalled for the time being on performance grounds, but I don't know if there's something else in the works.  For now, I'll re-close this, because we're tracking the same issue in #7033 (contains exactly the same circuit as yours) and #7042 - it's just helpful to keep stuff in fewer places.

**Closed by jakelishman** 2022-02-17 14:04 UTC
Labels: bug, status: duplicate
