### ISSUE TITLE
Add informative error message when the argument "shots" passed to the execute function is not of type int

### ISSUE THREAD

**Issue by siddharthdangwal** [Qiskit/qiskit-terra#4878] opened 2020-08-06 07:51 UTC
### What is the expected enhancement?
execute(circuit, backend = Aer.get_backend('qasm_simulator), shots = "1024") doesn't give an informative error message (Issue number 842 in qiskit-aer). Add an informative error message.

This isssue was posted in qiskit-aer which is a wrong place for it. Creating a new issue at qiskit-terra (which is relevant to it) and creating a pull request for a solution

**Comment by coder-mtv** [comment] 2020-08-12 15:26
Can I work on this?

**Comment by taalexander** [comment] 2020-08-12 20:25
Certainly, assigning to you.

**Comment by coder-mtv** [comment] 2020-08-13 11:58
Hey, I just looked through the problem. Can someone specify more precisely what the problem. I am new to this and help would be much appreciated, thanks!

**Comment by coder-mtv** [comment] 2020-08-13 13:35
@taalexander , @siddharthdangwal  Hey can you help me out, in specifying the error. Is it because the value for shots is entered as a string and an error message should be displayed for that?

**Comment by taalexander** [comment] 2020-08-13 14:47
@coder-mtv, I would start by trying the example @siddharthdangwal posted above and seeing where the error is raised. I think a proper error should be added somewhere around here https://github.com/Qiskit/qiskit-terra/blob/995ac92376cfa632b124e171023c779bd2f3119b/qiskit/compiler/assemble.py#L216.

**Comment by coder-mtv** [comment] 2020-08-13 20:48
Hey @taalexander , I have fixed the issue, I believe. I will upload it shortly. If there is still an error, could you please reassign it to me?

**Comment by coder-mtv** [comment] 2020-08-13 21:00
I will be uploading the fix around 10 hours later. It would be great, if you could merge by the 14th itself!

**Comment by taalexander** [comment] 2020-08-14 13:17
Hello, @coder-mtv it seems like @siddharthdangwal had made a PR #4880 and we missed this.

**Comment by coder-mtv** [comment] 2020-08-14 13:58
Ok, I can still work on this, right?

**Comment by coder-mtv** [comment] 2020-08-14 13:59
Hey @taalexander , so is the issue fixed, or can I still do it? I didn't it properly

**Comment by taalexander** [comment] 2020-08-14 14:09
I'm sorry @coder-mtv, it seems like there is already a solution that is mostly done. I don't think it would be a good use of time to continue on this, I am sorry for causing you to waste your time. Would you like me to to help find another good issue to work on?

**Comment by taalexander** [comment] 2020-08-14 14:10
You could also help review #4880 and compare it with your solution.

**Comment by coder-mtv** [comment] 2020-08-14 14:12
@taalexander but I encountered the error that was referred to in this issue, so is it fixed yet actually?

**Comment by coder-mtv** [comment] 2020-08-14 14:13
@taalexander Is there any way, I could do this issue, as I'm applying for the advocates program and a contribution would help!

**Comment by taalexander** [comment] 2020-08-21 03:20
@coder-mtv the fix is here https://github.com/Qiskit/qiskit-terra/pull/4880. If it is not updated by @siddharthdangwal in about a weeks time, I will reassign.

**Comment by tgag17** [comment] 2020-09-03 17:30
Hi! Is this problem still open?

**Comment by 1ucian0** [comment] 2020-09-16 22:55
@siddharthdangwal got unresponsive. Do you want to work on this @coder-mtv ? 

Feel free to continue the code in #4880. If you do, make sure you respect the original authorship as co-author. Otherwise, you can restart a new PR.

If @coder-mtv is not responding in the coming week. Is @tgag17 interested?

**Comment by coder-mtv** [comment] 2020-09-17 14:07
I will work on it @taalexander

**Comment by Arijit02** [comment] 2020-10-01 06:32
Hey, is this issue still open? Can I work on it?

**Comment by Arijit02** [comment] 2020-10-01 08:11
@taalexander could you please assign this issue to me? I want to try this out.

**Comment by tgag17** [comment] 2020-10-01 08:18
> @siddharthdangwal got unresponsive. Do you want to work on this @coder-mtv ?
> 
> Feel free to continue the code in #4880. If you do, make sure you respect the original authorship as co-author. Otherwise, you can restart a new PR.
> 
> If @coder-mtv is not responding in the coming week. Is @tgag17 interested?

I am interested if the issue is still open

**Comment by Arijit02** [comment] 2020-10-01 08:57
@taalexander I think I have solved this issue.

**Closed** 2020-12-04 05:24 UTC
Labels: good first issue, type: enhancement
