### ISSUE TITLE
Autocomplete lists Qiskit modules twice

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5220] opened 2020-10-13 08:24 UTC
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
This only occurs for Qiskit modules:

<img width="380" alt="Screen Shot 2020-10-13 at 04 21 04" src="https://user-images.githubusercontent.com/1249193/95835069-c375a300-0d0b-11eb-9683-8d48d106e6e2.png">

<img width="282" alt="Screen Shot 2020-10-13 at 04 22 11" src="https://user-images.githubusercontent.com/1249193/95835086-c7092a00-0d0b-11eb-9e3e-3371a5e6eb83.png">

**Comment by mtreinish** [comment] 2020-10-13 18:39
I assume jupyter (well actually more likely ipython) is using jedi for tab completion. Which version of jedi do you have installed? Although there hasn't been a recent release of jedi in a while so it might not be that.

I'm thinking this might be an issue with jupyter. At least for me locally with jedi-vim and ipython I'm not able to reproduce this:

![Screenshot_2020-10-13_14-34-47](https://user-images.githubusercontent.com/2447371/95901652-a4a1fb80-0d61-11eb-869d-a3524bc88a47.png)

but I see the same behavior in jupyter as you are.

**Comment by nonhermitian** [comment] 2020-10-13 20:47
Yeah I have the latest Jedi. There is a definite level of compatibility with jedi. Ipython great, notebooks good, lab iffy.

**Comment by jakelishman** [comment] 2021-12-14 18:15
This seems to be specifically when tab completing modules in import statements, such as `from qiskit.<tab>` - I can't reproduce with `qiskit.compiler.<tab>`, and similarly to Matthew, it only happens in Jupyter.

**Comment by jakelishman** [comment] 2021-12-15 11:32
Actually, it's just a Jupyter Notebook issue as best as I can tell - I made a simple package with no content at all other than submodules called `a` and `b`, and was able to reproduce the duplication, but only in `jupyter notebook` and not in `jupyter lab`.  So this is an old notebook issue, and since Jupyter are generally moving towards deprecation of that in favour of JupyterLab, I'll close this.

**Closed by jakelishman** 2021-12-15 11:32 UTC
Labels: bug
