### ISSUE TITLE
`assign_parameters` method is not working for controlled-U gate

### ISSUE THREAD

**Issue by SimoneGasperini** [Qiskit/qiskit-terra#9763] opened 2023-03-09 14:08 UTC
### Environment

- **Qiskit Terra version**: 0.23.1
- **Python version**: 3.10.8

### What is happening?

The [`QuantumCircuit.assign_parameters()`](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.assign_parameters.html) method does not work properly with the parametric controlled-U gate. The values passed to be assigned to the parameters seem just to be ignored (in both cases with `inplace=False` or `inplace=True`).

### How can we reproduce the issue?

```
from qiskit.circuit import QuantumCircuit, Parameter

chi = Parameter('$\\chi$')
theta = Parameter('$\\theta$')
phi = Parameter('$\\phi$')
lam = Parameter('$\\lambda$')
gamma = Parameter('$\\gamma$')

qc = QuantumCircuit(2)
qc.rx(chi, 1)
qc.cu(theta, phi, lam, gamma, 0, 1)

values = [4.68, 5.13, 1.06, 3.81, 3.83]
qc.assign_parameters(values, inplace=True)

qc.draw('mpl')
```
![output](https://user-images.githubusercontent.com/71086758/224049623-d6303cd5-9330-467b-b2d3-55921ab42a30.png)

### What should happen?

Each parameter of the controlled-U gate should be correctly bounded to the corresponding value passed to `assign_parameters()`, as it happens for any other parametric gate (Rx in the example above).

**Comment by jakelishman** [comment] 2023-03-09 14:38
Thanks for the report - this is a known issue (#7326), so I'll just close this as duplicate.  There's a potential fix available (#9118) that I need to review properly.

The root cause is mostly that `CUGate` is a badly behaved subclass of `ControlledGate`, and really, it's not even _really_ the controlled version of `UGate` (because it's got an extra parameter).

**Comment by jakelishman** [comment] 2023-03-09 14:38
Duplicate of #7326

**Closed by jakelishman** 2023-03-09 14:38 UTC
Labels: bug

**Comment by SimoneGasperini** [comment] 2023-03-09 14:47
Yes, there is the extra `gamma` parameter serving as global phase.
Thank you and sorry for the duplicate, I didn't see that there was already an open issue on this.

**Comment by jakelishman** [comment] 2023-03-09 15:05
No worries - it's really our fault that the issue's been open for so long.
