### ISSUE TITLE
Cannot get calibrations from job.qobj() using disassemble

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#5917] opened 2021-02-27 00:58 UTC
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
Retrieving a circuit with pulse gates does not return the inserted calibrations.  There is only an empty dict.

### Steps to reproduce the problem
Try to use `disassemble` on a Qobj from a job with circuits containing pulse gates.

**Comment by taalexander** [comment] 2021-02-27 11:15
Closing as duplicate of #5348. Will be resolved by #5661.

**Closed by taalexander** 2021-02-27 11:15 UTC
Labels: bug
