### ISSUE TITLE
Snapshot definition not included in generated qasm

### ISSUE THREAD

**Issue by maddy-tod** [Qiskit/qiskit-terra#2195] opened 2019-04-24 14:52 UTC
### What is the current behavior?
If a circuit includes snapshots, the qasm produced by `circuit.qasm()` cannot be used to create a new circuit as the relevant gate definition is not included.

### Steps to reproduce the problem
```
from qiskit import *
import qiskit.extensions.simulator
q = QuantumRegister(1)
c = ClassicalRegister(1)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.snapshot('1')

qcc = QuantumCircuit.from_qasm_str(qc.qasm())
```
This raises a `QasmError` as the gate definition for snapshot cannot be found.

**Comment by jaygambetta** [comment] 2019-05-02 03:34
it should not be included. We actually need to remove circuit.qasm() and replace with an export and things in the the circuit that are no quasi should just be ignored.

**Comment by 1ucian0** [comment] 2019-12-20 15:08
Shall we close this issue @maddy-tod

**Comment by maddy-tod** [comment] 2020-01-02 10:26
I think this problem needs to be addressed, but we can open a separate issue for it if that makes more sense.

**Comment by 1ucian0** [comment] 2021-09-19 12:09
It seems to me that raising in warning when a non-qasm instruction is being ignored as part of the generating QASM is a good compromise.

**Comment by jakelishman** [comment] 2021-09-20 17:04
Of note: at the moment, `qc.qasm()` currently throws a TypeError on this example, because `snapshot` does not define `Instruction.definition`:
```python
In [1]: import qiskit.extensions.simulator
   ...: qc = qiskit.QuantumCircuit(1, 1)
   ...: qc.snapshot('1')
   ...: qc.qasm()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-206b1a73ba8d> in <module>
      2 qc = qiskit.QuantumCircuit(1, 1)
      3 qc.snapshot('1')
----> 4 qc.qasm()

~/code/qiskit/terra/qiskit/circuit/quantumcircuit.py in qasm(self, formatted, filename, encoding)
   1569
   1570                     existing_composite_circuits.append(instruction)
-> 1571                     _add_sub_instruction_to_existing_composite_circuits(
   1572                         instruction, existing_gate_names, existing_composite_circuits
   1573                     )

~/code/qiskit/terra/qiskit/circuit/quantumcircuit.py in _add_sub_instruction_to_existing_composite_circuits(instruction, existing_gate_names, existing_composite_circuits)
   4032     instruction to existing_composite_circuit list.
   4033     """
-> 4034     for sub_instruction, _, _ in instruction.definition:
   4035         if (
   4036             sub_instruction.name not in existing_gate_names

TypeError: 'NoneType' object is not iterable
```
so we also need to fix either the handling in `QuantumCircuit.qasm` or that instruction.

**Comment by fs1132429** [comment] 2021-12-14 05:26
### Update for GoGP
✅ Issue reproducible in the latest version of terra!
```
from qiskit import *
import qiskit.extensions.simulator
q = QuantumRegister(1)
c = ClassicalRegister(1)
qc = QuantumCircuit(q, c)

qc.h(q[0])
qc.snapshot('1')

qcc = QuantumCircuit.from_qasm_str(qc.qasm())
```
Output:

>TypeError                                 Traceback (most recent call last)
/var/folders/6q/5vy060nd70n18078bjnxwpjr0000gn/T/ipykernel_11605/1172236089.py in <module>
      8 qc.snapshot('1')
      9 
---> 10 qcc = QuantumCircuit.from_qasm_str(qc.qasm())
<br/><br/>
~/opt/anaconda3/envs/QiskitDevenv/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py in qasm(self, formatted, filename, encoding)
   1437 
   1438                     existing_composite_circuits.append(instruction)
-> 1439                     _add_sub_instruction_to_existing_composite_circuits(
   1440                         instruction, existing_gate_names, existing_composite_circuits
   1441                     )
<br/><br/>
~/opt/anaconda3/envs/QiskitDevenv/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py in _add_sub_instruction_to_existing_composite_circuits(instruction, existing_gate_names, existing_composite_circuits)
   3012     instruction to existing_composite_circuit list.
   3013     """
-> 3014     for sub_instruction, _, _ in instruction.definition:
   3015         if (
   3016             sub_instruction.name not in existing_gate_names
<br/><br/>
TypeError: 'NoneType' object is not iterable


```
import qiskit.extensions.simulator
qc = qiskit.QuantumCircuit(1, 1)
qc.snapshot('1')
qc.qasm()
```
Output:

> TypeError                                 Traceback (most recent call last)
/var/folders/6q/5vy060nd70n18078bjnxwpjr0000gn/T/ipykernel_11605/3987447273.py in <module>
      2 qc = qiskit.QuantumCircuit(1, 1)
      3 qc.snapshot('1')
----> 4 qc.qasm()
<br/><br/>
~/opt/anaconda3/envs/QiskitDevenv/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py in qasm(self, formatted, filename, encoding)
   1437 
   1438                     existing_composite_circuits.append(instruction)
-> 1439                     _add_sub_instruction_to_existing_composite_circuits(
   1440                         instruction, existing_gate_names, existing_composite_circuits
   1441                     )
<br/><br/>
~/opt/anaconda3/envs/QiskitDevenv/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py in _add_sub_instruction_to_existing_composite_circuits(instruction, existing_gate_names, existing_composite_circuits)
   3012     instruction to existing_composite_circuit list.
   3013     """
-> 3014     for sub_instruction, _, _ in instruction.definition:
   3015         if (
   3016             sub_instruction.name not in existing_gate_names
<br/><br/>
TypeError: 'NoneType' object is not iterable

**Comment by jakelishman** [comment] 2023-04-19 22:17
With the updates to the OpenQASM 2 parser in #9953, the issue as originally presented is fixed.

It's unclear to me that `snapshot` should have been allowed to be exported at all (since it's a non-unitary `Instruction`) - imo that should be an error in OpenQASM 2 as the circuit is unrepresentable - but that's a separate issue (see #7351, #7750).  I'm going to close this as "somewhat fixed" now, and to leave coverage of my other concern to other open issues.

**Closed by jakelishman** 2023-04-19 22:17 UTC
Labels: bug, qasm
