### ISSUE TITLE
Using simulator instructions crashes the latex drawer

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1019] opened 2018-10-03 18:15 UTC
### Informations

- **Qiskit Terra version**: latest master
- **Python version**: 3.7
- **Operating system**: linux

### What is the current behavior?

Attempting to use the latex drawer to render a circuit with simulator instructions stack traces in the dagunroller. For example:

```
Traceback (most recent call last):
  File "test_qiskit.py", line 67, in <module>
    visualization.generate_latex_source(qc, filename='out.tex')
  File "/tmp/qiskit/qiskit-terra/qiskit/tools/visualization/_circuit_visualization.py", line 354, in generate_latex_source
    json_circuit = transpile(dag_circuit, basis_gates=basis, format='json')
  File "/tmp/qiskit/qiskit-terra/qiskit/transpiler/_transpiler.py", line 346, in transpile
    dag = dag_unroller.expand_gates()
  File "/tmp/qiskit/qiskit-terra/qiskit/unroll/_dagunroller.py", line 86, in expand_gates
    not self.dag_circuit.gates[current_node["name"]]["opaque"]:
KeyError: 'snapshot'
```
It looks like it's trying to treat the snapshot instruction as a gate (which it's not) and that's causing things to crash.

### Steps to reproduce the problem

I've been running:

```
import qiskit.extensions.simulator
from qiskit import *
from qiskit.tools import visualization

q = QuantumRegister(2)
c = ClassicalRegister(1)
qc = QuantumCircuit(q, c)

qc.x(q[0])
qc.snapshot(slot=3)
qc.x(q[1])
qc.h(q[0])
qc.barrier()
qc.measure(q[0], c[0])

visualization.generate_latex_source(qc, filename='out.tex')
```
Also replacing snapshot() with save(), load(), and noise()

### What is the expected behavior?

This should draw a circuit (the barriers won't be drawn for the simulator instructions, that's what I was working on adding when I encountered this) and not stack trace.

### Suggested solutions

Fix the crash.

**Comment by delapuente** [comment] 2018-10-04 07:52
This is a duplicate of #732.

**Closed by delapuente** 2018-10-04 07:52 UTC
Labels: status: duplicate, type: bug
