### ISSUE TITLE
Deepcopy of a job results in model validation error

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3793] opened 2020-02-04 21:01 UTC
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

import copy
copy.deepcopy(job)
```
yields:
```
ModelValidationError: "{'dtm': ['Missing data for required field.'], 'dt': ['Missing data for required field.'], 'rep_times': ['Missing data for required field.']}"
```

**Comment by 1ucian0** [comment] 2020-02-14 20:04
I could not reproduce this issue. I probably missing some specifics...

The following test passes. 
```
    def test_deepcopy_qobj(self):
        backend = FakeProvider().get_backend('fake_openpulse_2q')
        qr = QuantumRegister(3)
        circuit = QuantumCircuit(qr)
        circuit.h(qr)
        qobj = assemble(circuit, shots=1024, seed=88, backend=backend)
        qobj_copy = copy.deepcopy(qobj)
        self.assertEqual(qobj, qobj_copy)
```

**Comment by nonhermitian** [comment] 2020-02-25 09:37
It is deep copy of a Job, not Qobj:

```python

import copy
from qiskit import *

qc = QuantumCircuit(1,1)
qc.measure(0, 0)

backend = Aer.get_backend('qasm_simulator')

job = execute(qc, backend)

copy.deepcopy(job)
```

**Comment by chris-n-self** [comment] 2020-03-04 16:27
I think it is maybe the backend stored in job that is the issue. I get this same error just from trying to deep copy the backend object.

**Comment by arunraja-hub** [comment] 2020-06-18 19:57
@nonhermitian 
I am keen to work on this as one of my first issues. I ran the exact code in your last comment which resulted in the following error for me:
```
TypeError: can't pickle _thread.RLock objects
```
May I know in which python version did you get the ModelValidationError?

**Comment by nonhermitian** [comment] 2020-06-18 20:15
It was probably 3.7

**Comment by arunraja-hub** [comment] 2020-06-18 20:31
Ok I used 3.7 but I am not getting ModelValidationError, I am only getting the TypeError
Could you help to run your code snippet above and see if you still get ModelValidationError?

**Comment by mtreinish** [comment] 2020-06-19 10:54
`ModelValidationError` has been removed from qiskit-terra master when marshmallow was removed from all these objects so you won't see that as the error anymore. The problem back then was opened was likely that there was a mix of marshmallow and non-marshmallow objects mixing in an unexpected way on the reconstruction side of the deepcopy causing marshmallow to fail validation on construction of one of it's objects. If there is a still a problem with this now that marshmallow has been removed I expect that this is going to be similar to #4550 but in the case of job it's an object contained in the job object (like the backend, etc) instead of the job itself.

The `TypeError: can't pickle _thread.RLock objects` error is coming from local simulators that are forcing themselves to try and act async by wrapping the execution in `futures` objects. Deepcopy can't pickle  RLock objects as part of the deepcopy and fails.

**Comment by arunraja-hub** [comment] 2020-06-20 19:11
Thank you @mtreinish. Could you give me some suggestions for me to get started solving this issue?

**Comment by mtreinish** [comment] 2021-04-23 21:02
@arunraja-hub  Sorry I missed your question until just now. I don't really have a good suggestion. The issue is that the `AerJob` class contains a `ThreadpoolExecutor` object that it wraps the actual simulation in (so it doesn't block while the simulation is running): https://github.com/Qiskit/qiskit-aer/blob/master/qiskit/providers/aer/aerjob.py#L79 This object is not pickleable (because it represents a handle to a thread which is bound to the current python process (and doesn't make sense outside the context of the current python process). My only suggestion would be maybe to deepcopy the result object returned by `job.result()` instead of the job. This will contain all the result data from the job but not have any issues with deepcopying (because it doesn't have the threadpool executor instance.

I'm going to close this issue though, I don't think there is anything we can do here as long as we have `AerJob` as async we won't be able to deepcopy jobs. If there is more to discuss here please feel free to reopen this. Or alternatively open an issue with qiskit-aer (as this is specifically an issue with the AerJob class and how it does async execution).

**Closed by mtreinish** 2021-04-23 21:02 UTC
Labels: bug
