### ISSUE TITLE
loading V2 backend is very slow

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#8360] opened 2022-07-18 05:23 UTC
### Environment

- **Qiskit Terra version**: master
- **Python version**: 
- **Operating system**: 

### What is happening?

Something seems broken in V2 backends, in that making a Target out of them takes an extremely long time.

```py
from qiskit.providers.fake_provider import *

FakeWashington().configuration().coupling_map  # takes milliseconds

FakeWashingtonV2().coupling_map  # killed after 5 minutes
```

### How can we reproduce the issue?

code above

### What should happen?

Killing this process shows that loading backend defaults (presumably lots of pulse shapes) is what is taking so long. But that should be a lazy load and not needed for accessing some other device properties. And also it should be based on parametric pulses so it's not so slow to load in the first place.

**Comment by ajavadia** [comment] 2022-07-18 14:51
Ok yeah seems similar. I searched for an issue but couldn't find. Feel free to close it if it's being tracked elsewhere.

**Comment by jakelishman** [comment] 2022-08-15 13:02
Duplicate of #7914.

**Closed by jakelishman** 2022-08-15 13:02 UTC
Labels: bug, mod: fake_provider
