### ISSUE TITLE
Imports: Speed improvement for importing subpackages

### ISSUE THREAD

**Issue by drewrisinger** [Qiskit/qiskit-terra#5100] opened 2020-09-22 12:34 UTC
#### IMPORT SPEED of top-level ``qiskit/__init__.py``

Inspired by @mtreinish in #4958 .

Currently, it takes on the order of seconds to import just the base ``qiskit`` package, and that doesn't improve if you only import subpackages (e.g. ``qiskit.pulse``) due to the top-level import of heavy packages in [``./qiskit/__init__.py``](https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/pulse/__init__.py), e.g. ``qiskit.providers.ibmq`` which are always imported.

Here, I am mostly looking in this issue at import speed improvements in ``qiskit/__init__.py``.

### Possible Import Improvements

I see a few possible solutions, ranked in order of more breaking changes:
1. (low-hanging fruit): defer [``matplotlib.animation`` import in ``qiskit.visualization.transition_visualization``](https://github.com/mtreinish/qiskit-core/blob/717ccc74177ef11b97f02a10ac58fc6d3929a277/qiskit/visualization/transition_visualization.py#L23) to the [animation function](https://github.com/mtreinish/qiskit-core/blob/717ccc74177ef11b97f02a10ac58fc6d3929a277/qiskit/visualization/transition_visualization.py#L132-L164)
2. (low-hanging fruit): defer ``networkx`` import in ``qiskit.circuit.equivalence`` to the [``draw()``](https://github.com/Qiskit/qiskit-terra/blob/1aadb2078a66d008ae472ffeadb95baa2808f592/qiskit/circuit/equivalence.py#L162) and [``_build_basis_graph()`` (only used in ``draw()``)](https://github.com/Qiskit/qiskit-terra/blob/1aadb2078a66d008ae472ffeadb95baa2808f592/qiskit/circuit/equivalence.py#L190) functions so this isn't on the critical path every import.
2. Add an environment variable on the [Aer & IBMQ provider imports](https://github.com/Qiskit/qiskit-terra/blob/1aadb2078a66d008ae472ffeadb95baa2808f592/qiskit/__init__.py#L56-L75) to optionally disable them
3. Add an environment variable on the [``qiskit.circuit`` imports](https://github.com/Qiskit/qiskit-terra/blob/1aadb2078a66d008ae472ffeadb95baa2808f592/qiskit/__init__.py#L30-L34) to optionally disable them. (e.g. ``QISKIT_DONT_IMPORT_TOP_LEVEL``)

#### Import Time visualization
This can be checked visually with:

```bash
pip install tuna
pip install qiskit-terra qiskit-ibmq-provider
python -X importtime -c "import qiskit.pulse" 2> import_pulse.log
tuna import_pulse.log
```

Which yields (``qiskit-terra==0.15.1, qiskit-ibmq-provider==0.8.0``):
![image](https://user-images.githubusercontent.com/10198051/93879606-fba83980-fca9-11ea-95c5-914ba45a03f5.png)

which is similar to that in #4958 (I must have a slower computer/not be running on SSD):
![image](https://user-images.githubusercontent.com/2447371/90779632-0f880680-e2cc-11ea-85b6-34ec8b0af6a7.png)

We see that import ``qiskit.pulse`` ends up importing the top-level ``qiskit`` init file anyways. As a side note, I'd really prefer not to spend ~3 seconds importing ``qiskit-terra`` every time.

**Comment by mtreinish** [comment] 2020-09-22 12:55
This a good direction, I've done similar analysis in the past and agree we can do better. For your proposed steps:

1. Lets just do this asap, it's straightforward and will be good to get in before 0.16.0. It's a good catch.
2. This actually will just shift the path, networkx gets used in the coupling map which is a core construct. The equivalence library drawer is just being imported first in your example. I have an outstanding todo to migrate the coupling map to retworkx, but there are some feature gaps in retworkx that need to be closed. (for the drawer though we could do something like #5087 to avoid the networkx import there altogether).
3. Even with this we'll still end up importing them. The issue will just shift those imports to be in `version.py` to get `qiskit.__qiskit_version__` set it imports all the elements to grab the `__version__` attribute.
4. I don't know if this would solve an import performance issue. Even if we optional don't re-export the `QuantumCircuit` class other things we do import in the top level will pull in the `circuits` subpackage. For example, everything in `transpile` depends on `circuit` (to get bits, registers, etc). The same is true with `dagcircuit` and `visualization`.

The other thing which I think we can do here which was going to be a follow-up from #4958 as a multi-step process is to move matplotlib to not be imported at import time. The problem is which I found during #4958 is that doing this as I did there removes `qiskit.visualization` from the core import which was problematic for backwards compat. Then the other way to move the import is to make `matplotlib` a run time import everywhere, but this had issues because we export `HAS_MATPLOTLIB` and have for some time (and other projects may rely on this, I think ignis might). Either way it's used a lot of places in terra. So to do this we'll have to first deprecate `HAS_MATPLOTLB` and untangle the `HAS_MATPLOTLIB` usage everywhere. Then after that deprecation cycle we can migrate to run time matplotlib imports.

**Comment by drewrisinger** [comment] 2020-09-22 18:52
This isn't a top priority, but I found another leaf import that could potentially be removed/delayed. ``scipy.stats`` seems to only be used once in the repository 
https://github.com/Qiskit/qiskit-terra/blob/19bf1a7b8d75616bd587f927a71f9b2eb8041dd4/qiskit/quantum_info/operators/random.py#L19
, and takes >= 0.1s of the import time (~8%). This could be solved with a similar approach as in #5102.

**Comment by mariuskava** [comment] 2020-10-07 05:40
Did you consider using lazy imports? Sometimes it can make troubleshooting more tricky. But the behaviour could be controlled by env variable.

**Comment by mtreinish** [comment] 2020-10-19 18:37
@drewrisinger yeah, `scipy.stats` was a good call. I pushed a PR to make that change in: https://github.com/Qiskit/qiskit-terra/pull/5258

I really want to push one to move matplotlib to be a lazy runtime import too. It'll probably meaning breaking anyone who is relying on `qiskit.visualization.HAS_MATPLOTLIB` today. Which might be a fair tradeoff, but after we drop python3.6 support (which the process for starts in #5189 ) we can use a module level getattr functions (which was added in 3.7) to do this more gracefully. So I'm a bit torn on whether to make the breaking change or just wait 6 months from the next release.

**Comment by mtreinish** [comment] 2020-10-19 18:38
Also, we should be able to remove networkx from the import path (which is surprisingly not cheap either) after #5183 merges which will speed things up a bit more

**Comment by mtreinish** [comment] 2020-12-08 15:37
After #5471 and #5485 the import performance here is a lot better. The only 2 things after #5485 is finished and merges that will be good to do is remove the fastjsonschema import time compilation (which is deprecated and is just a matter of time) and then something for `__qiskit_version__`. `__qiskit_version__` is a bit more involved to do lazily because it's defined as a module attribute that's a dict. So the hack I used for `HAS_MATPLOTLIB` won't work because there is no hidden method being called when it's accessed. We won't have module `__getattr__` on modules until Python 3.7 is the minimum supported version.

**Comment by drewrisinger** [comment] 2021-02-03 13:44
Thanks @mtreinish for being responsive and the tedious work that goes into this!

**Comment by mtreinish** [comment] 2021-02-05 18:57
ok, I'm going to close this as all 3 of those PRs have merged now. To wrap it I just ran an importtime profile of `import qiskit` with all optional dependencies and all the qiskit components installed and this is what it returned:

![Screenshot_2021-02-05_13-50-35](https://user-images.githubusercontent.com/2447371/107076381-5ce42b80-67b9-11eb-9db5-7e85d552cafb.png)

which I think is a good enough improvement to go from ~1.1 sec to ~0.49 sec.

With all the jsonschema usage currently being deprecated, >=3 months after 0.17.0's release when we remove the jsonschema bits we'll shave another ~0.05 sec off the import time. There is also cvxpy in there which is only used in one place and takes ~0.06 sec to import. But both of those times seem pretty minor. We can open up follow up issues or PRs if they get to be a bottleneck for people.

**Closed by mtreinish** 2021-02-05 18:57 UTC
Labels: performance, type: enhancement
