### ISSUE TITLE
Preset pass manager fails when passed multiple circuits

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-terra#8538] opened 2022-08-15 12:07 UTC
### Environment

- **Qiskit Terra version**: 82c85d859be00659b0ab0214bee89456a9cee195
- **Python version**: 3.9.7
- **Operating system**: RHEL 8.6

### What is happening?

Preset pass manager with optimization level 3 fails when passed multiple circuits.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager

circuit = QuantumCircuit(1)
pass_manager = generate_preset_pass_manager(3)
pass_manager.run([circuit, circuit])
```
```
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib64/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/kevinsung/projects/qiskit-terra/qiskit/tools/parallel.py", line 105, in _task_wrapper
    return task(value, *task_args, **task_kwargs)
  File "/home/kevinsung/projects/qiskit-terra/qiskit/transpiler/passmanager.py", line 238, in _in_parallel
    running_passmanager = dill.loads(pm_dill)._create_running_passmanager()
  File "/home/kevinsung/.local/share/virtualenvs/qiskit-terra-rZn7sWYf/lib/python3.9/site-packages/dill/_dill.py", line 327, in loads
    return load(file, ignore, **kwds)
  File "/home/kevinsung/.local/share/virtualenvs/qiskit-terra-rZn7sWYf/lib/python3.9/site-packages/dill/_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/kevinsung/.local/share/virtualenvs/qiskit-terra-rZn7sWYf/lib/python3.9/site-packages/dill/_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
  File "/home/kevinsung/projects/qiskit-terra/qiskit/quantum_info/synthesis/two_qubit_decompose.py", line 130, in <lambda>
    cls.__new__ = lambda cls, *a, fidelity=None, **k: TwoQubitWeylDecomposition.__new__(
TypeError: __new__() missing 1 required positional argument: 'unitary_matrix'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-1-d045259e7fb5> in <module>
      4 circuit = QuantumCircuit(1)
      5 pass_manager = generate_preset_pass_manager(3)
----> 6 pass_manager.run([circuit, circuit])

~/projects/qiskit-terra/qiskit/transpiler/passmanager.py in run(self, circuits, output_name, callback)
    509     ) -> Union[QuantumCircuit, List[QuantumCircuit]]:
    510         self._update_passmanager()
--> 511         return super().run(circuits, output_name, callback)

~/projects/qiskit-terra/qiskit/transpiler/passmanager.py in run(self, circuits, output_name, callback)
    225         if len(circuits) == 1:
    226             return self._run_single_circuit(circuits[0], output_name, callback)
--> 227         return self._run_several_circuits(circuits, output_name, callback)
    228 
    229     def _create_running_passmanager(self) -> RunningPassManager:

~/projects/qiskit-terra/qiskit/transpiler/passmanager.py in _run_several_circuits(***failed resolving arguments***)
    258         del callback
    259 
--> 260         return parallel_map(
    261             PassManager._in_parallel, circuits, task_kwargs={"pm_dill": dill.dumps(self)}
    262         )

~/projects/qiskit-terra/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
    174             # Otherwise just reset parallel flag and error
    175             os.environ["QISKIT_IN_PARALLEL"] = "FALSE"
--> 176             raise error
    177 
    178         Publisher().publish("terra.parallel.finish")

~/projects/qiskit-terra/qiskit/tools/parallel.py in parallel_map(task, values, task_args, task_kwargs, num_processes)
    164                 future = executor.map(_task_wrapper, param)
    165 
--> 166             results = list(future)
    167             Publisher().publish("terra.parallel.done", len(results))
    168 

/usr/lib64/python3.9/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    557     careful not to keep references to yielded objects.
    558     """
--> 559     for element in iterable:
    560         element.reverse()
    561         while element:

/usr/lib64/python3.9/concurrent/futures/_base.py in result_iterator()
    606                     # Careful not to keep a reference to the popped future
    607                     if timeout is None:
--> 608                         yield fs.pop().result()
    609                     else:
    610                         yield fs.pop().result(end_time - time.monotonic())

/usr/lib64/python3.9/concurrent/futures/_base.py in result(self, timeout)
    436                     raise CancelledError()
    437                 elif self._state == FINISHED:
--> 438                     return self.__get_result()
    439 
    440                 self._condition.wait(timeout)

/usr/lib64/python3.9/concurrent/futures/_base.py in __get_result(self)
    388         if self._exception:
    389             try:
--> 390                 raise self._exception
    391             finally:
    392                 # Break a reference cycle with the exception in self._exception

TypeError: __new__() missing 1 required positional argument: 'unitary_matrix'
```

### What should happen?

It should work.

### Any suggestions?

Passing circuits individually works, so the issue seems to be with parallelization. Lower optimization levels seem to work fine.

**Comment by jakelishman** [comment] 2023-03-03 15:26
I think this was fixed by #7333.  At any rate, I can't reproduce it any more, so I'll close it but feel free to re-open if it's still an issue.

**Closed by jakelishman** 2023-03-03 15:26 UTC
Labels: bug
