### ISSUE TITLE
Alternate example for plot_bloch_multivector

### ISSUE THREAD

**Issue by mrvee-qC** [Qiskit/qiskit-terra#7420] opened 2021-12-16 10:25 UTC
### Environment

- **Qiskit Terra version**: 0.19.1

### What is happening?

The example for the plot_bloch_multivector doc looks broken - https://qiskit.org/documentation/stubs/qiskit.visualization.plot_bloch_multivector.html#qiskit.visualization.plot_bloch_multivector

The example is trying to visualize a bell state and the entanglement isn't clearly visualizable with bloch sphere and hence there are 2 blank bloch spheres that may not depict the idea of the function clearly!

![Screenshot from 2021-12-16 15-38-27](https://user-images.githubusercontent.com/61380731/146354927-ada94920-20d9-46da-91fc-98e4f4d8336e.png)

### How can we reproduce the issue?

The issue can be checked out here! https://qiskit.org/documentation/stubs/qiskit.visualization.plot_bloch_multivector.html#qiskit.visualization.plot_bloch_multivector

LIne in docs - 
https://github.com/Qiskit/qiskit-terra/blob/4301fc47c73507e489dbafc7bae490ab29736daa/qiskit/visualization/state_visualization.py#L263-L277

### What should happen?

An example that clearly depicts a use case for the `plot_bloch_multivector` for people checking out the documentation

### Any suggestions?

Since the examples are uniform across all the sections of https://qiskit.org/documentation/apidoc/visualization.html#counts-and-state-visualizations, contributor may have to take into consideration that if at all this example is to be modified, the subsection docs `plot_histogram` , `plot_state_city`, `plot_state_hinton`, `plot_state_paulivec` and `plot_state_qsphere `may have to be similarly accommodated since currently all seem to be using the same example across to depict the visualisation ideas uniformly in their respective sections.

**Comment by nonhermitian** [comment] 2021-12-16 10:43
Actually the entanglement is "visible" in that plot because it is tracing over qubits and giving the maximally mixed state which is just a point at the origin of the sphere.  That is to say it is showing what it is supposed to show in that example.

**Comment by mrvee-qC** [comment] 2021-12-16 10:54
> Actually the entanglement is "visible" in that plot because it is tracing over qubits and giving the maximally mixed state which is just a point at the origin of the sphere. That is to say it is showing what it is supposed to show in that example.

Totally agreed! :smile: It may not be something that would immediately strike as an example use case for new qiskitters referring to the example in my opinion. A state which has a clear visible plot could be much quicker for a viewer to get an idea as to what the function offers! :smile:

**Comment by iuliazidaru** [comment] 2021-12-20 11:01
May I take this issue?

**Comment by jakelishman** [comment] 2021-12-20 15:13
Sure, I'll assign this one to you so people know you're working on it.

**Comment by MaxMinerva123** [comment] 2022-01-02 13:15
Hey so I think I found the issue. The only problem is I have no idea why it works.
So, apparently, if you interchange the position of the qubits in qc.cx, it works.

that is, instead of qc.cx(0,1)
you type, qc.cx(1,0)



from qiskit import QuantumCircuit 

from qiskit.visualization import plot_bloch_multivector 
%matplotlib inline 
  
qc = QuantumCircuit(2) 
qc.h(0) 
qc.cx(1, 0) 
  
state = Statevector.from_instruction(qc) 
plot_bloch_multivector(state, title="New Bloch Multivector", reverse_bits=False) 



I have no idea if this is what you were looking for, but this is what I found.

**Comment by jakelishman** [comment] 2022-01-04 12:07
This works because `h(0); cx(1, 0)` maps `|00>` to `|01>`, whereas the previous way maps `|00>` to `(|00> + |11>)/sqrt(2)`; swapping the operands of `cx` doesn't create an entangled state, and the issue is that you can't visualise entangled states using separate Bloch spheres.

**Comment by MaxMinerva123** [comment] 2022-01-04 13:03
Oh I see. I'm really new to Qiskit and Quantum Computing in general but yeah I didn't know swapping the operands of cx doesn't create an entangled state
Thanks!

**Closed** 2022-01-04 13:57 UTC
Labels: bug, good first issue
