### ISSUE TITLE
Transpilation error with the basis_gates set on optim level 2

### ISSUE THREAD

**Issue by LenaPer** [Qiskit/qiskit-terra#5665] opened 2021-01-21 11:36 UTC
### Information

- **Qiskit Terra version**: 0.16.1
- **Python version**: 3.8.5
- **Operating system**: macOS BigSur 11.1

### What is the current behavior?
When I transpile a circuit at optimization_level = 2 on all those backends : 
ibmqx2, imbq_16_melbourne, ibmq_athens, ibmq_santiago, ibmq_rome, ibmq_manhattan, ibmq_toronto, ibmq_bogota, ibmq_montreal, ibmq_sydney
that all have now the new set of basis_gates ['id', 'rz', 'sx', 'x', 'cx'], there is u1 gates appearing on the new transpiled circuit, which should not be here because the basis_gates come from the backends, which have all the new set, without u2.

### Steps to reproduce the problem
I have the error on all the backends listed above, example for Melbourne : 
```
from qiskit import QuantumCircuit, IBMQ
from qiskit.compiler import transpile

IBMQ.load_account()
provider = IBMQ.get_provider(group = 'open')

backend = provider.get_backend('ibmq_16_melbourne')

qc = QuantumCircuit(5)
qc.h([0,2,3])
qc.i(0)
qc.cx(0,1)
qc.cx(2,1)
qc.cx(3,4)
qc.x([4,1])
qc.cz(2,0)
qc.cz(3,2)
qc.z([1,2,3])
qc.cx(0,3)
qc.cx(2,4)
qc.cx(3,0)
qc.measure_all()

trans = transpile(qc, backend, seed_transpiler = 2303, optimization_level = 2)
print("The depth of the transpiled circuit is : ", trans.depth())
print("Optim = 2 : ", trans.count_ops())
```
We get this result :
The depth of the transpiled circuit is :  25
Optim = 2 :  OrderedDict([('cx', 17), ('rz', 12), ('sx', 7), ('measure', 5), ('u1', 2), ('x', 2), ('id', 1), ('barrier', 1)])

### What is the expected behavior?
There should not be this u1 here.

**Comment by mtreinish** [comment] 2021-01-21 12:41
So I took a quick look to dig into this issue this morning. The issue is the `CommutativeCancellation` transpiler pass isn't basis gate aware and only knows how to use the U1 gates for z rotations: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/transpiler/passes/optimization/commutative_cancellation.py

To fix this we probably either need to update the pass to basis aware, or update the default level2 pass manager to run basis translation in the fixed point loop after we run commutative cancellation.

**Comment by mtreinish** [comment] 2021-01-21 14:48
This is a duplicate of #5644 (missed that before) so I'm going to close this and we'll track this in #5644

**Closed by mtreinish** 2021-01-21 14:48 UTC
Labels: bug
