### ISSUE TITLE
pulse namespaces

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#4109] opened 2020-04-08 15:35 UTC
the namespace `pulse.pulse_lib.pulse` is a bit confusing and if you're not careful, you might collide the outer pulse with inner pulse. is there a better name for that inner one?

**Comment by taalexander** [comment] 2020-04-08 15:47
Closed as duplicate of #4074.

**Closed by taalexander** 2020-04-08 15:47 UTC
Labels: type: enhancement
