### ISSUE TITLE
QuantumCircuit.draw() does not draw circuit in terminal

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-terra#3720] opened 2020-01-16 15:31 UTC
### Information

- **Qiskit Terra version**: master
- **Python version**:
- **Operating system**:

### What is the current behavior?

Currently returns a `<qiskit.visualization.text.TextDrawing>`.  However, it should print to the terminal because it is an explicit command to draw the circuit.

**Comment by yesodharan1892** [comment] 2020-01-16 17:47
hi, can you share the code to replicate the problem , i would like to look into it if you are okay with it

**Comment by nonhermitian** [comment] 2020-01-16 18:03
Anything really:
```python
from qiskit import *
qc = QuantumCircuit(2, 2)
qc.h(0)
qc.cx(0, 1)
qc.measure([0,1], [0,1])
qc.draw()
```

**Comment by yesodharan1892** [comment] 2020-01-16 20:44
i just checked in my jupyter lab, its perfectly working, may i recommend updating qiskit through pip 

![Untitled](https://user-images.githubusercontent.com/57726155/72561347-0450a080-38cf-11ea-8ade-944c4d060a76.png)

**Comment by nonhermitian** [comment] 2020-01-16 20:52
From the terminal, not Jupyter:

<img width="574" alt="Screen Shot 2020-01-16 at 3 51 31 PM" src="https://user-images.githubusercontent.com/1249193/72561870-23701380-3878-11ea-92d0-f468e839721c.png">

**Comment by mohfaz** [comment] 2020-01-17 10:54
Try:
print(qc.draw(output='text'))

**Comment by 1ucian0** [comment] 2020-01-17 11:29
Hi @mohfaz, you are right, the possibility is there. However, the issue is about the representation of the object in the terminal. Basically, implementing your work around as the `__repr__`. 

I just PRed a possible fix to this issue.

**Comment by yesodharan1892** [comment] 2020-01-17 22:22
hi @mohfaz , your method does work on the terminal , however i believe adding the __repr__ function to the source text should avoid any further issues without using commands like print and directly calling circuit.draw.
thanks

**Closed** 2020-02-06 12:49 UTC
Labels: status: pending PR, type: enhancement

**Comment by namandoctor** [comment] 2020-03-21 08:35
I got this error:
C:\Users\naman\Anaconda3\envs\qiskit_programming\lib\site-packages\qiskit\visualization\circuit_visualization.py:263: UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-GUI backend, so cannot show the figure.
  image.show()

I am using Atom Editor, so temporarily I was able to solve the problem by installing the hydrogen extension, and running the code with it. 

![qiskit_hydrogen](https://user-images.githubusercontent.com/55620213/77222826-3db7bd80-6b57-11ea-8a5f-bd8759066b98.png)

**Comment by kdk** [comment] 2020-03-23 21:01
Hi @namandoctor , this looks like a different issue. Can you raise this on the qiskit slack or stack exchange? (Also, did you run `%matplotlib inline` in this notebook?)

**Comment by ismetshn** [comment] 2021-03-02 02:55
In this way, no problem!
[01](https://user-images.githubusercontent.com/30768399/109589604-a48d7700-7b1b-11eb-9ab0-0a8857ffb543.jpeg)
