### ISSUE TITLE
UnboundLocalError: local variable 'grid_data' referenced before assignment

### ISSUE THREAD

**Issue by ryan-woo** [Qiskit/qiskit-terra#7451] opened 2021-12-29 16:51 UTC
### Environment

- **Qiskit Terra version**: Custom fork, but I do see this error is possible in the main branch
- **Python version**: 3.8
- **Operating system**: MacOS

### What is happening?

```
Traceback (most recent call last)
<ipython-input-10-fe09d7b7de3e> in <module>
----> 1 plot_error_map(backend)

~/tmp/bronn/qiskit-terra/.venv/lib/python3.8/site-packages/qiskit/visualization/gate_map.py in plot_error_map(backend, figsize, show_title)
    815     if num_qubits <= 5:
    816         qubit_size = 20
--> 817     plot_gate_map(
    818         backend,
    819         qubit_color=q_colors,

~/tmp/bronn/qiskit-terra/.venv/lib/python3.8/site-packages/qiskit/visualization/gate_map.py in plot_gate_map(backend, figsize, plot_directed, label_qubits, qubit_size, line_width, font_size, qubit_color, qubit_labels, line_color, font_color, ax, filename)
    349     coupling_map = config.coupling_map
    350     qubit_coordinates = qubit_coordinates_map.get(num_qubits)
--> 351     return plot_coupling_map(
    352         num_qubits,
    353         qubit_coordinates,

~/tmp/bronn/qiskit-terra/.venv/lib/python3.8/site-packages/qiskit/visualization/gate_map.py in plot_coupling_map(num_qubits, qubit_coordinates, coupling_map, figsize, plot_directed, label_qubits, qubit_size, line_width, font_size, qubit_color, qubit_labels, line_color, font_color, ax, filename)
    464             return fig
    465 
--> 466     x_max = max(d[1] for d in grid_data)
    467     y_max = max(d[0] for d in grid_data)
    468     max_dim = max(x_max, y_max)
```

### How can we reproduce the issue?

This is using a staging IQX backend which is only available to me.

### What should happen?

If the backend is not reporting some information then maybe a more helpful error?

**Comment by kdk** [comment] 2023-06-20 20:52
Closing as this looks like expected behavior in the current model (currently, `plot_gate_map` and friends require qubit locations to be available in Qiskit for a given backend family). https://github.com/Qiskit/qiskit-terra/issues/10080 proposes moving this description to be provided by the backend.

**Closed by kdk** 2023-06-20 20:52 UTC
Labels: bug

**Comment by mtreinish** [comment] 2023-06-20 21:03
That's not actually 100% true `plot_gate_map` will fall back to an algorithmic layout based on `rustworkx.spring_layout` if there is no hard coded layout available. This is being changed in #10208 to use graphviz instead for better layouts at larger scale. I actually want to move to remove the hard-coded layouts following #10208 and then if/when #10080 is implemented the backend can specify an alternative default layout.
