### ISSUE TITLE
TypeError: '>' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by praveentn** [Qiskit/qiskit-terra#4963] opened 2020-08-20 18:06 UTC
### Informations

- **Qiskit version**: 0.20.0
- **Python version**: 3.7.8
- **Operating system**: posix

### What is the current behavior?
`---------------------------------------------------------------------------`
`TypeError                                 Traceback (most recent call last)`
`<ipython-input-13-20ee4434b30d> in <module>`
`      5 array_to_latex(psi, pretext="|\\psi\\rangle =")`
`      6 # Show it on a Bloch sphere`
`----> 7 plot_bloch_multivector(psi)`

`/opt/conda/lib/python3.7/site-packages/qiskit/util.py in wrapper(*args, **kwargs)`
`    108             if kwargs:`
`    109                 _rename_kwargs(func.__name__, kwargs, kwarg_map)`
`--> 110             return func(*args, **kwargs)`
`    111         return wrapper`
`    112     return decorator`

`/opt/conda/lib/python3.7/site-packages/qiskit/visualization/state_visualization.py in plot_bloch_multivector(state, title, figsize, rho)`
`    269                           'matplotlib".')`
`    270     # Data`
`--> 271     bloch_data = _bloch_multivector_data(state)`
`    272     num = len(bloch_data)`
`    273     width, height = plt.figaspect(1/num)`

`/opt/conda/lib/python3.7/site-packages/qiskit/visualization/utils.py in _bloch_multivector_data(state)`
`    311     for i in range(num):`
`    312         paulis = PauliTable(np.zeros((3, 2 * (num - 1)), dtype=np.bool)).insert(`
`--> 313             i, pauli_singles, qubit=True)`
`    314         bloch_state = [np.real(np.trace(np.dot(mat, rho.data))) for mat in paulis.matrix_iter()]`
`    315         bloch_data.append(bloch_state)`

`/opt/conda/lib/python3.7/site-packages/qiskit/quantum_info/operators/symplectic/pauli_table.py in insert(self, ind, value, qubit)`
`    323 `
`    324         # Column insertion`
`--> 325         if ind > self.num_qubits:`
`    326             raise QiskitError("Index {} is greater than number of qubits"`
`    327                               " in the PauliTable ({})".format(ind, self.num_qubits))`

`TypeError: '>' not supported between instances of 'int' and 'NoneType'`

### Steps to reproduce the problem

`# Create random 1-qubit state`
`psi = random_state(1)`

`# Display it nicely`
`array_to_latex(psi, pretext="|\\psi\\rangle =")`
`# Show it on a Bloch sphere`
`plot_bloch_multivector(psi)`

### What is the expected behavior?

No exceptions

**Comment by kdk** [comment] 2020-08-20 19:38
Thanks for reporting @praveentn . This looks like a duplicate of #4941 . Feel free to re-open if not.

**Closed by kdk** 2020-08-20 19:38 UTC
