### ISSUE TITLE
Statevector draw with latex:

### ISSUE THREAD

**Issue by dyukha** [Qiskit/qiskit-terra#9646] opened 2023-02-24 08:29 UTC
I'm using IPython in Google Colab (Python 3.8.10). `qiskit[visualization]` version is 0.41.0.

The following code
```
import qiskit
from qiskit.quantum_info import Statevector
circuit = qiskit.QuantumCircuit(1, 0)
sv = Statevector.from_instruction(circuit)
sv.draw('latex')
```
produces the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-820a68dc8a3d>](https://localhost:8080/#) in <module>
      3 circuit = qiskit.QuantumCircuit(1, 0)
      4 sv = Statevector.from_instruction(circuit)
----> 5 sv.draw('latex')

5 frames
[/usr/local/lib/python3.8/dist-packages/qiskit/quantum_info/states/statevector.py](https://localhost:8080/#) in draw(self, output, **drawer_args)
    183         from qiskit.visualization.state_visualization import state_drawer
    184 
--> 185         return state_drawer(self, output=output, **drawer_args)
    186 
    187     def _ipython_display_(self):

[/usr/local/lib/python3.8/dist-packages/qiskit/visualization/state_visualization.py](https://localhost:8080/#) in state_drawer(state, output, **drawer_args)
   1480 
   1481         draw_func = drawers["latex_source"]
-> 1482         return Latex(f"$${draw_func(state, **drawer_args)}$$")
   1483 
   1484     if output == "repr":

[/usr/local/lib/python3.8/dist-packages/qiskit/visualization/state_visualization.py](https://localhost:8080/#) in state_to_latex(state, dims, convention, **args)
   1263     is_qubit_statevector = len(operator_shape.dims_r()) == 0 and set(operator_shape.dims_l()) == {2}
   1264     if convention == "ket" and is_qubit_statevector:
-> 1265         latex_str = _state_to_latex_ket(state._data, **args)
   1266     else:
   1267         latex_str = array_to_latex(state._data, source=True, **args)

[/usr/local/lib/python3.8/dist-packages/qiskit/visualization/state_visualization.py](https://localhost:8080/#) in _state_to_latex_ket(data, max_size, prefix)
   1365         nonzero_indices[max_size // 2] = None
   1366     else:
-> 1367         latex_terms = _numbers_to_latex_terms(data[nonzero_indices], max_size)
   1368 
   1369     latex_str = ""

[/usr/local/lib/python3.8/dist-packages/qiskit/visualization/state_visualization.py](https://localhost:8080/#) in _numbers_to_latex_terms(numbers, decimals)
   1333     terms = []
   1334     for number in numbers:
-> 1335         term = _num_to_latex(number, decimals=decimals, first_term=first_term, coefficient=True)
   1336         terms.append(term)
   1337         first_term = False

[/usr/local/lib/python3.8/dist-packages/qiskit/visualization/array.py](https://localhost:8080/#) in _num_to_latex(raw_value, decimals, first_term, coefficient)
     37     value = sympy.nsimplify(raw_value, rational=False)
     38 
---> 39     if isinstance(value, sympy.core.numbers.Rational) and value.denominator > 50:
     40         # Avoid showing ugly fractions (e.g. 50498971964399/62500000000000)
     41         value = value.evalf()  # Display as float

TypeError: '>' not supported between instances of 'method' and 'int'
```
Works fine with other arguments for `draw` (e.g. `text`, `bloch`, etc.).

Same problem for DensityMatrix.

**Comment by jakelishman** [comment] 2023-02-24 12:42
This is mostly caused by Google Colab having quite an old version of `sympy` installed by default, though Terra could also be better at catching the error (see #9505).  As an immediate workaround, you can run
```
!pip install -U sympy
```
in your colab session, and that should hopefully solve the issue.

We're working on a larger fix.  In the meantime, I'll close this issue (but thanks for raising it!) because we've already got a report in #9481.

**Comment by jakelishman** [comment] 2023-02-24 12:43
Duplicate of #9481.

**Closed by jakelishman** 2023-02-24 12:42 UTC
