### ISSUE TITLE
Some controlled gates have ctrl_state parameters. Some not.

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#6465] opened 2021-05-26 14:54 UTC
### What is the current behavior?

Based on https://github.com/Qiskit/qiskit-terra/issues/5098#issue-705776539

The `cx` method has `ctrl_state`  while `ccx` does not have that parameter.
```
from qiskit import QuantumCircuit

qc = QuantumCircuit(3)
qc.cx(0, 1, ctrl_state='0')
qc.ccx(0, 1, 2, ctrl_state='00')
```
```
TypeError: ccx() got an unexpected keyword argument 'ctrl_state'
```

### What is the expected behavior?

Consistency. Either the all controlled gate should have `ctrl_state` parameter  (vote with 🎉 ) or neither (vote with 🚀).

**Comment by eptru** [comment] 2021-05-27 14:33
Newcomer here. I am interested in taking this once we reach a decision! I can take the label issue at the same time.

**Comment by rupeshknn** [comment] 2021-05-28 13:37
All the control gates, like cu, cp, cry etc all have `ctrl_state` so I guess it would be preferable to add the same to ccx

**Comment by singhmeet11** [comment] 2021-06-04 13:43
I would like to add that `x.py` inside standard gates already have that parameter for ccx gate so the problem is only there with `quantumcircuit.py`. And it only requires a small correction.

**Comment by a-freakish** [comment] 2021-06-04 16:33
New to quantum world. Would love to work on this issue.

**Comment by fs1132429** [comment] 2021-06-04 17:26
I am new to open source contribution. I would like to contribute to this if its ok.

**Comment by singhmeet11** [comment] 2021-06-04 19:03
@iamsantanubanerjee As I can see, you have pulled another PR, which copies my exact same code. @1ucian0 Is this allowed?

As for what you suggested, I shall point out the reason I did not add, `label` parameter because issue #5098 clearly talks about how you they want to remove that particular parameter from all the gates. P.S look at my issue for the correct format(I am still getting some error for some reason taking a look into it).

**Comment by iamsantanubanerjee** [comment] 2021-06-04 19:15
@singhmeet11 I had no intention to create another PR copying your exact same code. I am very new to open source contributions, but I am aware it isn't allowed. I was only experimenting with PRs. As you might see, I immediately closed my PR after a few minutes. Sorry if I made some mistake.

I later figure out the 'label' issue. Thanks for mentioning though.

**Comment by singhmeet11** [comment] 2021-06-04 19:40
No worries bro @iamsantanubanerjee , I was myself not sure about how this works, this is my 2nd pull request and 1st to terra . So I am also super new.

**Comment by singhmeet11** [comment] 2021-06-05 07:53
@fs1132429 , @a-freakish I don't think that this issue will require any more corrections so you guys should checkout other ones. 
P.S why don't one of you (and @iamsantanubanerjee ) take a look at #5098, it is also a good first issue and will require you to remove all the `label` parameters in the code from `quantumcircuit.py` and I think removing from standard gates will make it too permanent so maybe not do that(It's your call).

**Comment by javabster** [comment] 2021-06-07 08:46
Hi all! Thank-you for your interest in taking on this issue, it seems to be popular! As @singhmeet11 was the first one to open a PR for this issue I am formally assigning it to them (although in future please let the first person who asked to be assigned have a go at it first before opening your PR, or see if you can reach the original person on slack and work on it together 😄 ).

For everyone else if you have suggestions for improvements to code please do not create a new PR but instead leave comments on suggestions on singhmeet11's PR instead. Or if you would like to choose another good first issue to work on you can go to the issues tab and use the filters to find one that is not yet assigned to someone.

Lastly, please remember to read the [Contributing Guidelines](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/Qiskit/qiskit/blob/master/CODE_OF_CONDUCT.md), and thank-you for your contributions 😄

**Comment by singhmeet11** [comment] 2021-06-08 10:21
Hi, I was not aware of the protocol, of how to approach the problem when someone has already made a comment but no one is assigned. So I waited for a week to see if anyone is going to try and fix the bug.  
However, that being said I will make sure from now on that whichever bug I am working on has not been assigned to someone else or contact the people who have commented before me.

**Closed** 2021-06-21 10:38 UTC
Labels: bug, good first issue
