### ISSUE TITLE
Opaque gate definitions give an error in CircuitBackend

### ISSUE THREAD

**Issue by eddieschoute** [Qiskit/qiskit-terra#337] opened 2018-03-13 19:16 UTC
Defining a general opaque gate raises an error when unrolling into a circuit.

## Expected Behavior
Either an opaque gate should be taken as-is and be left alone, or when it is defined in the basis it should be left alone when reading in OpenQASM.

## Current Behavior
My OpenQASM code
```
OPENQASM 2.0;
include "qelib1.inc";

opaque mygate q1, q2, q3;
qreg q[3];
creg c[2];

mygate q[0], q[1], q[2];

measure q[0] -> c[0];
measure q[1] -> c[1];
```
and parsing code
```py
from sys import argv
from pathlib import Path

import matplotlib
matplotlib.use('TkAgg') # OSX workaround

from qiskit.qasm import Qasm
from qiskit.unroll import Unroller, CircuitBackend
from qiskit.tools.visualization import circuit_drawer

if len(argv) != 2:
    raise RuntimeError("Exactly 1 argument is required.")

print(f"Opening {argv[1]}")
path = Path(argv[1]).resolve(strict=True)
qasm = Qasm(filename=str(path)).parse()
circuit = Unroller(qasm, CircuitBackend(
    basis=["u1","u2","u3","id","cx","x","y","z","h","s","t","rx","ry","rz"])).execute()
im = circuit_drawer(circuit)
im.save(path.with_suffix('.png'))
```
When reading in OpenQASM with an opaque gate definition I get the error
```
Opening quantum-simulation.qasm
Traceback (most recent call last):
  File "qasm-to-img.py", line 18, in <module>
    basis=["u1","u2","u3","id","cx","x","y","z","h","s","t","rx","ry","rz"])).execute()
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 280, in execute
    self._process_node(self.ast)
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 187, in _process_node
    self._process_children(node)
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 182, in _process_children
    self._process_node(kid)
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 222, in _process_node
    self._process_custom_unitary(node)
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 111, in _process_custom_unitary
    self.arg_stack[0:-1])
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_circuitbackend.py", line 211, in start_gate
    raise BackendError("opaque gate %s not in basis" % name)
qiskit.unroll._backenderror.BackendError: 'opaque gate mygate not in basis'
```

So I did the obvious, and added `mygate` to the basis of the CircuitBackend constructor. But this still gives an error:
```
Opening quantum-simulation.qasm
Traceback (most recent call last):
  File "qasm-to-img.py", line 18, in <module>
    basis=["u1","u2","u3","id","cx","x","y","z","h","s","t","rx","ry","rz","mygate"])).execute()
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 280, in execute
    self._process_node(self.ast)
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 187, in _process_node
    self._process_children(node)
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 182, in _process_children
    self._process_node(kid)
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 222, in _process_node
    self._process_custom_unitary(node)
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_unroller.py", line 111, in _process_custom_unitary
    self.arg_stack[0:-1])
  File "/Users/eddie/dev/quasci.com/img/circuits/.venv/lib/python3.6/site-packages/qiskit/unroll/_circuitbackend.py", line 260, in start_gate
    name)
qiskit.unroll._backenderror.BackendError: 'gate mygate not in standard extensions'
```

It seems that QISKit is insisting on unrolling opaque gates into an explicit circuit description, even though they are defined as opaque. (Even I don't know what `mygate` is.)

## Possible Solution
It seems that there is some code for detecting opaque gates in the CircuitBackend, but it still only expects gates from the standard library. Instead there should be support of opaque gates in a QuantumCircuit object.

Another design decision is whether to allow opaque gates to exist outside of the defined basis.

## Steps to Reproduce (for bugs)
1. Make a file `quantum-simulation.qasm` with the OpenQASM code above
2. Make a file `qasm-to-img.py` with the python code above
3. Install qiskit and pillow dependencies. (e.g. `pip install qiskit pillow`)
4. Run `python qasm-to-img.py quantum-simulation.qasm`

## Context
I'm trying to generate images of quantum circuits using OpenQASM. The circuit is supposed to represent some general quantum circuit for some arbitrary unitary U followed by some measurements.

## Your Environment
* Version used: qiskit 0.4.10
* Environment name and version (e.g. Python 3.6.1): 3.6.4
* Operating System and version: macOS 10.13

**Comment by jaygambetta** [comment] 2018-05-13 12:32
Yes we need to add opaque to qiskit.  @ewinston can you think about this the user will need to provide a definition of what it is as well.

**Comment by delapuente** [comment] 2018-07-31 11:08
Labelling this as a bug since we should explicitly say we are not currently supporting `opaque` gates instead of failing with non-clear error messages.

**Comment by 1ucian0** [comment] 2019-04-04 01:49
`CircuitBackend` is not a thing anymore. Therefore, I'm closing this. If this issue still exists in terms of the current code, please reopen and rename (and give a new way to reproduce it). Thanks!

**Closed by 1ucian0** 2019-04-04 01:49 UTC
Labels: bug, enhancement, priority: medium
