### ISSUE TITLE
Wire fragment bug in mapper

### ISSUE THREAD

**Issue by ajavadia** [Qiskit/qiskit-terra#1426] opened 2018-12-05 05:36 UTC
### What is the current behavior?
After the big DAG refactor, there were a couple test cases where the mapper failed. Those were disabled temporarily in the interest of merging that PR. Now they must be resolved and re-enabled. 

The bug is that the mapper complains that the DAG registers get fragmented during mapping.

```
test.python.test_mapper.TestMapper.test_move_measurements
test.python.tools.test_compiler.TestCompiler.test_mapping_multi_qreg
test.python.test_reordering.TestBitReordering.test_multi_register_reordering
```

**Comment by kdk** [comment] 2018-12-11 15:18
Looked into this briefly and it looks like this is caused by the way we construct the `identity_wire_map` up to a size `of `layout_max_index`, but elsewhere construct an output dag with size of the physical qubits in `coupling_map`. Since not all physical qubits are included in the layout, some physical qubits end up missing from the generated wire map. I've got a WIP PR that fixes at least some of the tests that I'll attach.

**Comment by 1ucian0** [comment] 2018-12-12 18:56
Fixed via https://github.com/Qiskit/qiskit-terra/pull/1464

**Closed** 2018-12-12 18:55 UTC
Labels: type: bug
