### ISSUE TITLE
Can't merge padded schedules

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#4653] opened 2020-07-06 22:14 UTC
### Information

- **Qiskit Terra version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

It's known that Delays prevent Schedules from being merged. Here's a simple example:

sched 0
d0 `|--------    Delay ------|`
u0 `|----- SamplePulse ---|`

sched 1
d0 `|--------    Delay ------|`
u4 `|----- SamplePulse ---|`

### Steps to reproduce the problem

I want to do `final = sched0.insert(0, sched1)`, but I get an error `'Overlap on channel DriveChannel(0) over time range [0, <T_f>]'`

### What is the expected behavior?

It should be valid to merge these. In particular, this came up while a user (Jin-sung Kim) was experimenting with simultaneous CNOTs.

### Suggested solutions

This is a somewhat tricky request, because sometimes we add a `Delay` to really mean "please don't do anything during this time". We've discussed having a boolean or a new instruction to force nothing to happen. Perhaps for now, we should allow delays to be replaced or split by new instructions. The in progress `replace` method of `Schedule`s might come in handy. 

If you are a contributor who would like to take this on, please type up a short description of the approach you plan to take.

**Comment by Randl** [comment] 2022-05-14 11:15
I can try to work on this.

I was thinking on adding an (internal) function, which, given timeslot, splits all the `Delay`s of the schedule on this timeslot: e.g., if there is a `Delay` (0,100) and timeslot [(10,20), (40,50)], we'll replace the former with a set of `Delay`s [(0,10), (20,40), (50,100)]. Applying this function to each of the schedules with the timeslot of the other one, we'll prevent intersection of the `Delay`s with other instruction. The same function can be made to ignore `Delay` with a specific boolean flag in future, if needed. We may also separately merge the consecutive `Delay`s which may appear after processing.

**Comment by jakelishman** [comment] 2022-05-16 13:54
Thanks for the interest!  Since the issue is rather old, and I don't know about the pulse module, I'll assign @nkanazawa1989 to it to have a look over and see if it's still in need of solving, and if your proposed approach makes sense.

**Comment by nkanazawa1989** [comment] 2022-05-17 05:27
We are kind of discouraging creating `Schedule` directly, since evaluation of time slot is performance bottleneck as shown in #8029 . Current primary interface of pulse module is the builder context. The above example is

```python
with build() as sched0:
    play(sample_pulse, u0)    

with build() as sched1:
    play(sample_pulse, u4)    

with build() as sched:
    with align_left():
        call(sched0)
        call(sched1)
```
If user explicitly adds delay in d0 channel in above example, `sched` will become
```
d0 |----Delay----|----Delay----|
u0 |-SamplePulse-|-------------|
u4 |-------------|-SamplePulse-|
```
rather than raising an error.

**Comment by jakelishman** [comment] 2023-04-22 14:38
Given the above discussion from Naoki, the pulse maintainer, I'll close this issue now as "wontfix".  If there's more to say, please feel free to re-open.

**Closed by jakelishman** 2023-04-22 14:38 UTC
Labels: bug, help wanted, short project, mod: pulse
