### ISSUE TITLE
Unreferenced variable CompleteMeasFitter

### ISSUE THREAD

**Issue by eendebakpt** [Qiskit/qiskit-terra#6789] opened 2021-07-22 16:08 UTC
### Information

- **Qiskit Nature version**: 0.1.4
- **Python version**: 3.8
- **Operating system**: Windows 10

### What is the current behavior?

Running one of the algoritms results in an error `UnboundLocalError: local variable 'CompleteMeasFitter' referenced before assignment` due to a missing import.

### Steps to reproduce the problem

A minimal example is:
```
from qiskit.utils import QuantumInstance
from qiskit.ignis.mitigation.measurement import CompleteMeasFitter
from qiskit.test.mock import FakeVigo
from qiskit import Aer

from qiskit_nature.drivers import UnitsType, Molecule
from qiskit_nature.drivers.second_quantization import PySCFDriver
from qiskit_nature.problems.second_quantization import ElectronicStructureProblem
from qiskit_nature.converters.second_quantization import QubitConverter
from qiskit_nature.mappers.second_quantization import JordanWignerMapper
from qiskit_nature.algorithms import VQEUCCFactory
from qiskit_nature.algorithms import GroundStateEigensolver

molecule = Molecule(geometry=[['H', [0., 0., 0.]], ['H', [0., 0., 0.735]]],
                     charge=0, multiplicity=1)
driver = PySCFDriver(molecule = molecule, unit=UnitsType.ANGSTROM, basis='sto3g')

es_problem = ElectronicStructureProblem(driver)
qubit_converter = QubitConverter(JordanWignerMapper())

backend = Aer.get_backend("qasm_simulator")
device = FakeVigo()
coupling_map = device.configuration().coupling_map
quantum_instance = QuantumInstance(backend=backend, 
                                   shots=400, 
                                   noise_model=None, 
                                   coupling_map=coupling_map,
                                   measurement_error_mitigation_cls=CompleteMeasFitter,
                                   cals_matrix_refresh_period=30)

vqe_solver = VQEUCCFactory(quantum_instance)
calc = GroundStateEigensolver(qubit_converter, vqe_solver)
res = calc.solve(es_problem) # fails with the combination coupling map and CompleteMeasFitter
```

### What is the expected behavior?

The algorithm should have executed without an error.

### Suggested solutions

Add an import of the `CompleteMeasFitter`

**Comment by woodsp-ibm** [comment] 2021-07-22 16:09
Duplicate of #6774

**Closed** 2021-07-22 21:45 UTC
Labels: mod: algorithms
