### ISSUE TITLE
Optimization: parallelize scheduler.schedule over circuits

### ISSUE THREAD

**Issue by lcapelluto** [Qiskit/qiskit-terra#2695] opened 2019-06-26 19:35 UTC
### What is the expected enhancement?
`qiskit.scheduler.schedule` accepts a list of quantum circuits. It should make use of `parallel_map` just like `transpile` does over quantum circuits to parallelize compilation.

**Comment by Avhijit-codeboy** [comment] 2021-12-16 03:14
The issue is still in "To Do" stage. Needs more information.

**Comment by upsideon** [comment] 2022-02-16 19:59
May I pick up this issue? I implemented @mtreinish's suggestion locally, as shown below:
`schedules = parallel_map(schedule_circuit, circuits, (schedule_config, method))`
And did not observe any adverse side effects when I added a unit test that calls `qiskit.scheduler.schedule`.

**Comment by javabster** [comment] 2022-05-25 21:48
Hi @upsideon sorry this issue fell off the radar, are you still interested n working on this?

**Comment by javabster** [comment] 2022-05-26 17:15
great, assigned to you! Let us know if you have any questions, and you can take a look at the following resources as well:

- [Contributing Guidelines](https://github.com/Qiskit/qiskit-terra/blob/main/CONTRIBUTING.md)
- [GitHub / CI tips for Qiskit Contributors](https://www.youtube.com/watch?v=-eLeOeF_-5o)

**Closed** 2022-06-08 12:56 UTC
Labels: help wanted, performance, mod: pulse
