### ISSUE TITLE
KeyError while printing COUNTS of particular qubit

### ISSUE THREAD

**Issue by mfaizan9** [Qiskit/qiskit-terra#7464] opened 2022-01-04 07:56 UTC
### Environment

- **Qiskit Terra version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

I apply X-gate to qubit-0
Then I measured it.
I simulate it on qasm_simulator with shots=1024
I plotted the histogram.
I printed counts

So, when I print  counts( ["1"] ), it gave me 1024
BUT when I printed counts counts( ["0"] ), it gave me "KEYERROR" instead of 0.

Kindly resolve this issue.

### How can we reproduce the issue?

I apply X-gate to qubit-0
Then I measured it.
I simulate it on qasm_simulator with shots=1024
I plotted the histogram.
I printed counts

So, when I print  counts( ["1"] ), it gave me 1024
BUT when I printed counts counts( ["0"] ), it gave me "KEYERROR" instead of 0.

Kindly resolve this issue.

### What should happen?

I apply X-gate to qubit-0
Then I measured it.
I simulate it on qasm_simulator with shots=1024
I plotted the histogram.
I printed counts

So, when I print  counts( ["1"] ), it gave me 1024
BUT when I printed counts counts( ["0"] ), it gave me "KEYERROR" instead of 0.

Kindly resolve this issue.

### Any suggestions?

I apply X-gate to qubit-0
Then I measured it.
I simulate it on qasm_simulator with shots=1024
I plotted the histogram.
I printed counts

So, when I print  counts( ["1"] ), it gave me 1024
BUT when I printed counts counts( ["0"] ), it gave me "KEYERROR" instead of 0.

Kindly resolve this issue.

**Comment by jakelishman** [comment] 2022-01-04 09:15
This is by design right now; storing explicit zeroes for all possible measurement outcomes scales exponentially in the number of qubits, and overriding `__getitem__` makes lookups linear in the number of qubits at best.  If you want to manually wrap the output, see https://github.com/Qiskit/qiskit-terra/issues/6937#issuecomment-904001950.  If we do merge new behaviour for the class, it will probably be in #5205, but see the rest of the discussion there for why that's currently a bit stalled.

As a side note, if you want to report a bug, please actually follow the template.  It is not very helpful if you copy and paste the same message four times.

**Comment by 1ucian0** [comment] 2023-03-11 20:05
Closing as `wont fix`

**Closed by 1ucian0** 2023-03-11 20:05 UTC
Labels: bug, wont fix
