### ISSUE TITLE
Long transpile time for simple circuits

### ISSUE THREAD

**Issue by HwajungKang** [Qiskit/qiskit-terra#9367] opened 2023-01-12 17:14 UTC
### Environment

- **Qiskit Terra version**:  0.39.4
- **Python version**: 3.7.9
- **Operating system**: Darwin

### What is happening?

Transpiling a simple circuit for a 100+ qubit IBM System such as 'ibm_sherbrooke' takes way longer than expected. 
I am attaching here the diagram of the circuit that was used and the result of profiling the transpiling time of the circuit against 'ibm_sherbrooke'.

 
<img width="479" alt="circuit" src="https://user-images.githubusercontent.com/59101727/212133518-c8512262-af51-48e1-aedf-c650307f9796.png">

<img width="792" alt="profile" src="https://user-images.githubusercontent.com/59101727/212133547-103cfd55-c1ed-4323-9c69-650bb8522b70.png">

### How can we reproduce the issue?

```python
from qiskit import *
from qiskit_ibm_provider import IBMProvider
import numpy as np

qc = QuantumCircuit(4)
qc.rx(np.pi*0.95, range(4))
qc.measure_all()

prov = IBMProvider()
backend = prov.get_backend('ibm_sherbrooke')

%%prun
qc_trans = transpile(qc, backend, optimization_level=3)
```

### What should happen?

I don't think that it should take that long.

**Comment by mtreinish** [comment] 2023-01-12 17:57
I think this will be fixed by: https://github.com/Qiskit/qiskit-terra/pull/9148 based on the profile timings there it looks like it's being caused by vf2layout trying really hard to try to find which permutation of qubits have the lowest noise in a very naive way. For your circuit it's basically evaluating 10334625 different possible layout permutations which takes a long time. #9148 should fix this by figuring out the lowest noise qubits and selecting those directly.

**Comment by HwajungKang** [comment] 2023-01-12 18:04
Hi Matthew, thanks for the reply. 10334625 is definitely a huge number of options! ;) Glad to hear that there is already a fix for it!

**Closed as completed** 2023-01-18 20:54 UTC
Labels: bug
