### ISSUE TITLE
Teleportation circuit plot

### ISSUE THREAD

**Issue by bettinaheim** [Qiskit/qiskit-terra#4886] opened 2020-08-04 20:04 UTC
### Informations

- **Qiskit version**:
0.19.6

- **Python version**:
3.8.5.

- **Operating system**:
Windows

### What is the current behavior?
The circuit plotted for the attached code is incorrect. 

### Steps to reproduce the problem
Load and plot the circuit.

### What is the expected behavior?
Getting a standard teleport circuit diagram. 

### Suggested solutions
None

Code to reproduce: 

OPENQASM 2.0;
include "qelib1.inc";

qreg qubits[3];
creg corrz[1];
creg corrx[1];
creg final[1];

h qubits[0];

h qubits[1];
cx qubits[1], qubits[2];

cx qubits[0], qubits[1];
h qubits[0];

measure qubits[0] -> corrz[0]; 
measure qubits[1] -> corrx[0];

if (corrz==1) z qubits[2]; 
if (corrx==1) x qubits[2];

h qubits[2];

measure qubits[2] -> final[0];

**Comment by deeplokhande** [comment] 2020-08-08 03:48
![image](https://user-images.githubusercontent.com/10705840/89701799-49d6c880-d908-11ea-900e-b34478c6082d.png)
I can see the measurements been done before applying the control on qubit 2. If this is not the reproduced error, Please upload the image if you can.

**Comment by bettinaheim** [comment] 2020-08-10 13:26
Hu, that is not the picture I am getting. 
![teleport](https://user-images.githubusercontent.com/34236215/89787508-6cb4d880-dad2-11ea-8e6a-8eda3e6119f7.PNG)

**Comment by bettinaheim** [comment] 2020-08-10 13:33
Here is also the driver code (not that that should be relevant): 

from qiskit import *
import argparse 

def run_experiment(circuit):
    backend = BasicAer.get_backend('qasm_simulator')
    job = execute(circuit, backend, shots=100)
    result = job.result()
    return result.get_counts(circuit)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--qasm", dest="qasm")
    args = parser.parse_args()
    circuit = QuantumCircuit.from_qasm_file(args.qasm)
    data = run_experiment(circuit)
    is_correct = lambda key: key.startswith('0')
    success = all(map(is_correct, data.keys()))

    if success: print("\nTeleportation succeeded!")
    else: print("\nTeleportation failed.")

    print("\nFull histogram:")
    print(data)
    print("\nCircuit:")
    print(circuit)

**Comment by deeplokhande** [comment] 2020-08-14 17:20
@bettinaheim Sorry for the late response. The Issue in this case is not your code but its just how the print( ) function in python prints the circuit. The printing happens along the depth i.e. horizontal length instead of the vertical length/ width. So it prints out gates corresponding to each qubit , qubit line by qubit line, Hence although in functionality the circuit works exactly as expected, while printing due to the above nature, it prints the Z gate where it finds space next on the qubit line. 
I recommend you using barriers between your circuit to resolve your problem. 
As for a permanent fix for this issue, i think developing an in-house qiskit circuit print functionality will solve it for printing in terminal. If you want you or I can start this now issue for enhancement. I have a standard pseudo code solution of how to print it in-house.

I hope this has helped you, and let me know if this issue can be closed.

Here's the attached changed QASM code, and the corresponding output if need be.

```
OPENQASM 2.0;
include "qelib1.inc";

qreg qubits[3];
creg corrz[1];
creg corrx[1];
creg final[1];

h qubits[0];

h qubits[1];
cx qubits[1], qubits[2];

cx qubits[0], qubits[1];
h qubits[0];

barrier qubits[0],qubits[1],qubits[2];

measure qubits[0] -> corrz[0];
measure qubits[1] -> corrx[0];

barrier qubits[0],qubits[1],qubits[2];

if (corrz==1) z qubits[2];
if (corrx==1) x qubits[2];

h qubits[2];

measure qubits[2] -> final[0];
```
![2020-08-11 17_17_57-dkl@DESKTOP-G9JHUFR_ _mnt_c_Users_deepl_Documents_qiskit_aqua](https://user-images.githubusercontent.com/10705840/90275774-d4e81f00-de30-11ea-8267-a1e04bcf0f5c.png)

**Comment by bettinaheim** [comment] 2020-08-17 13:54
@deeplokhande 
Thanks for the explanation! Feel free to do with this issue as you see fit - close it, migrate it, open a feature request. I am all set here; I just ran into this and wanted to file it since I wasn't sure whether you are aware of it.

**Comment by 1ucian0** [comment] 2021-12-14 09:10
Closing this. Thanks!

**Closed by 1ucian0** 2021-12-14 09:10 UTC
