### ISSUE TITLE
"QuantumCircuit.save_density_matrix()" method does not work unless the aer library is imported.

### ISSUE THREAD

**Issue by BOBO1997** [Qiskit/qiskit-terra#8674] opened 2022-09-05 00:08 UTC
### Environment

- **Qiskit Terra version**: please see the picture below
- **Python version**: please see the picture below
- **Operating system**: macOS Monterey version 12.2.1
<img width="329" alt="Screen Shot 2022-09-05 at 0 37 57" src="https://user-images.githubusercontent.com/28642796/188337907-bd4f70fe-bc94-4511-a8fe-0cb01d068d20.png">

### What is happening?

The default method `QuantumCircuit.save_density_matrix()` in `qiskit.circuit.QuantumCircuit` class is not available if we import QuantumCircuit only.
<img width="691" alt="Screen Shot 2022-09-05 at 1 05 14" src="https://user-images.githubusercontent.com/28642796/188338745-e80faba0-6617-4cf9-b1c0-9c095144db87.png">

However, once we import some other Qiskit libraries, `QuantumCircuit.save_density_matrix()` becomes available.
<img width="699" alt="Screen Shot 2022-09-05 at 1 05 47" src="https://user-images.githubusercontent.com/28642796/188338761-80a012c8-bec7-437e-9c9a-c2aa4d63a80a.png">

### How can we reproduce the issue?

Just running the following code can reproduce the error.
```py
from qiskit import QuantumCircuit
qc = QuantumCircuit(3)
qc.save_density_matrix()
```

I also attached an .ipynb file for further verification of this bug.
[save_density_matrix.ipynb.zip](https://github.com/Qiskit/qiskit-terra/files/9485719/save_density_matrix.ipynb.zip)

### What should happen?

Since the `QuantumCircuit.save_density_matrix()` is a standard method shown in the [document](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.save_density_matrix.html?highlight=save_density_matrix#qiskit.circuit.QuantumCircuit.save_density_matrix), the following code should be successfully run with no errors.
```py
from qiskit import QuantumCircuit
qc = QuantumCircuit(3)
qc.save_density_matrix()
```

### Any suggestions?

I guess some essential links (imports) that activate the `QuantumCircuit.save_density_matrix()` method are missed in the current version, though I did not identify the location of this bug in the program.

I hope someone can tackle this bug, many thanks!

**Comment by jakelishman** [comment] 2022-09-05 01:26
The method appears in the documentation like that (as opposed to Aer-specific documentation) as an unfortunate consequence of how Aer monkey-patches methods onto `QuantumCircuit`, and how the docs build happens.  These methods will start being documented in Aer's standalone documentation soon (_maybe_ with Aer 0.11 but probably the version after), to help avoid this confusion a bit.

You can see some more discussion in #6346.  I'll close this issue as a duplicate of that, just for book-keeping purposes; it's still an issue that needs fixing, we just already have a tracker for it.

**Comment by jakelishman** [comment] 2022-09-05 01:26
Duplicate of #6346

**Closed by jakelishman** 2022-09-05 01:26 UTC
Labels: bug

**Comment by BOBO1997** [comment] 2022-09-05 01:34
Thank you so much for your quick response, I am happy to hear this family of issues would be fixed in the near future.
I will also follow issue #6346.
