### ISSUE TITLE
MapperError consistently raised trying to run qft with 8qubits on melbourne

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-terra#1881] opened 2019-02-28 19:33 UTC
### Information

- **Qiskit Terra version**: Master
- **Python version**: 3.7
- **Operating system**: Linux

### What is the current behavior?

Running this script:

```
import math

from qiskit import QuantumCircuit
from qiskit import QuantumRegister
from qiskit import transpiler


def build_model_circuit(qreg, circuit=None):
    """Create quantum fourier transform circuit on quantum register qreg."""
    if circuit is None:
        circuit = QuantumCircuit(qreg, name="qft")

    n = len(qreg)

    for i in range(n):
        for j in range(i):
            circuit.cu1(math.pi/float(2**(i-j)), qreg[i], qreg[j])
        circuit.h(qreg[i])

    return circuit

n_qubits = 8
qr = QuantumRegister(n_qubits)
circuit = build_model_circuit(qr)

# Manually pulled configuration for melbourne
coupling_map = [[1, 0], [1, 2], [2, 3], [4, 3], [4, 10], [5, 4],
                [5, 6], [5, 9], [6, 8], [7, 8], [9, 8], [9, 10],
                [11, 3], [11, 10], [11, 12], [12, 2], [13, 1],
                [13, 12]]
transpiler.transpile(circuit,
                     basis_gates=['u1', 'u2', 'u3', 'cx', 'id'],
                     coupling_map=coupling_map)
```

will always raise the following error:

`qiskit.mapper.exceptions.MapperError: 'swap_mapper failed: layer 25, sublayer 3'`

It's worth pointing out that for any other value of n_qubits (<=14 which is the number of qubits for the backend) it seems to work fine. It on raises an error with 8 qubits.

### Steps to reproduce the problem

Run the above script.

### What is the expected behavior?

It transpiles the circuit successfully

### Suggested solutions

Fix it

**Comment by nonhermitian** [comment] 2019-02-28 19:39
You may need to add some ancilla qubits to the circuit to have the mapper succeed.

**Comment by mtreinish** [comment] 2019-02-28 19:47
I just tested it and yeah adding an ancilla qubit to the circuit does make the mapper work. But I still think there is potentially an issue here because the mapper works fine without an ancilla for the same circuit generation function with 1-7 and 9-14 qubits with that coupling map. It only fails when I use an 8 qubit register.

**Comment by nonhermitian** [comment] 2019-03-01 14:57
The above example actually works for me using master version.

**Comment by nonhermitian** [comment] 2019-03-01 15:02
![qft_mel_compiled](https://user-images.githubusercontent.com/1249193/53646395-1834da80-3c09-11e9-9394-ab409e37230f.png)

**Comment by mtreinish** [comment] 2019-03-01 18:22
Hmm, interesting. It fails very consistently on both my laptop and my desktop with the MapperError. Although they both run very similar software versions of everything. Linux x86_64 with Python 3.7.2

**Comment by nonhermitian** [comment] 2019-03-08 20:20
I have compiled this circuit 10,000 times with randomly picked seeds and it always works for me.

**Comment by nonhermitian** [comment] 2019-03-08 20:38
Grabbing the latest master, the example does not even run anymore:

`TranspilerError: 'initial layout not supplied, and cannot be inferred from backend.'`

**Comment by mtreinish** [comment] 2019-03-08 20:40
That error is being fixed by https://github.com/Qiskit/qiskit-terra/pull/1883

**Comment by nonhermitian** [comment] 2019-03-08 20:43
Actually that error only pops up on Win 10.  On OSX, the latest master now gives the same result you mentioned earlier:

`MapperError: 'swap_mapper failed: layer 25, sublayer 3'`

I do not know why the same master has two different errors for the same code on different platforms, nor do I understand why it worked previously.

**Comment by nonhermitian** [comment] 2019-03-08 21:13
The bug in the mapper was introduced with the merging of #1767.  So @1ucian0 should investigate it.

**Comment by 1ucian0** [comment] 2019-03-25 19:33
I think the problem is the lack of ancillas (the `MapperError` does not make any sense to me, tho). We have a pass to enlarge the layout with ancillas that should be called before `swap_mapper` in `qiskit/transpiler/transpiler.py:222`. So the fix can be added after PR https://github.com/Qiskit/qiskit-terra/pull/1862 is merged.

**Comment by 1ucian0** [comment] 2019-03-26 19:24
Fixed by https://github.com/Qiskit/qiskit-terra/pull/2023

**Closed** 2019-04-07 21:20 UTC
Labels: pass manager, status: pending PR

**Comment by nonhermitian** [comment] 2019-04-07 21:59
Is there a test that makes sure the pre bug circuit is the same as the new circuit returned?
