### ISSUE TITLE
rzx defined twice in QASM export

### ISSUE THREAD

**Issue by epelofske-LANL** [Qiskit/qiskit-terra#7779] opened 2022-03-15 03:47 UTC
### Environment

- **Qiskit Terra version**: `qiskit-terra==0.19.2`
- **Python version**: `3.9.7`
- **Operating system**: `macOS`

### What is happening?

A Qiskit circuit that contains the `ecr` two qubit gate exports two definitions of rzx when converting the circuit to a QASM file:

```
OPENQASM 2.0;
include "qelib1.inc";
gate rzx(param0) q0,q1 { h q1; cx q0,q1; rz(-pi/4) q1; cx q0,q1; h q1; }
gate rzx(param0) q0,q1 { h q1; cx q0,q1; rz(pi/4) q1; cx q0,q1; h q1; }
gate ecr q0,q1 { rzx(pi/4) q0,q1; x q0; rzx(-pi/4) q0,q1; }
```

### How can we reproduce the issue?

Create a Qiskit circuit with an ECR gate, and then export that circuit to QASM. 

### What should happen?

Upon reading in the QASM file (`QuantumCircuit.from_qasm_file`) it will throw an error because rzx is defined twice.

**Comment by jakelishman** [comment] 2022-03-15 04:01
Thanks for the report.  In this case, this is a duplicate of issue #7749, which is itself a duplicate in spirit of #7335.  There's a bit more information in those issues about why this happens, and how our near-term plans will help fix this.

**Comment by jakelishman** [comment] 2022-03-15 04:01
Duplicate of #7749.

**Closed by jakelishman** 2022-03-15 04:01 UTC
Labels: bug
