### ISSUE TITLE
Invitation link to Slack is missing

### ISSUE THREAD

**Issue by tbabej** [Qiskit/qiskit-terra#1237] opened 2018-11-08 00:34 UTC
The README page mentions the slack channel https://qiskit.slack.com, but does not provide an actual invitation link to join. This turns out to be a hard gem to find on the internet, as invitation links eventually expire. All of the following blog posts contain expired Slack invitation links:

https://medium.com/qiskit/qiskit-turns-one-looking-back-cbc2c48d7a95
https://developer.ibm.com/blogs/2018/09/07/join-quantum-community/

**Comment by atilag** [comment] 2018-11-08 16:47
Hi @tbabej!
[qiskit.org](https://qiskit.org) should always have a valid invitation link.
I think we might want to link to the front-page in future articles, instead of just putting a link in there.

Thanks for reporting!

**Comment by tbabej** [comment] 2018-11-08 16:49
Thanks for pointing that out @atilag !

However, the link on the qiskit.org is inactive too, unfortunately.

**Comment by 1ucian0** [comment] 2018-11-08 20:14
Confirmed. I created https://github.com/Qiskit/qiskit.org/issues/56 for updating the web. This issue for updating the documentation.

**Comment by 1ucian0** [comment] 2018-11-08 20:16
The link to the invitation without expiration is:

https://join.slack.com/t/qiskit/shared_invite/enQtNDc2NjUzMjE4Mzc0LTMwZmE0YTM4ZThiNGJmODkzN2Y2NTNlMDIwYWNjYzA2ZmM1YTRlZGQ3OGM0NjcwMjZkZGE0MTA4MGQ1ZTVmYzk

**Comment by atilag** [comment] 2018-11-09 11:44
https://github.com/Qiskit/qiskit.org/pull/57 has been merged. Closing this issue.
Thanks @tbabej and @1ucian0 !

**Comment by 1ucian0** [comment] 2018-11-09 18:17
Re-opeining, so the link is also in the README file in the repo is updated.

**Comment by 1ucian0** [comment] 2018-11-13 14:38
fixed in pending PR: https://github.com/Qiskit/qiskit-terra/pull/1254/commits/509312d3b71263b72834cf3be7f95d30fa6f87c2

**Comment by 1ucian0** [comment] 2018-11-15 01:00
Fixed in #1254. Thanks @tbabej !

**Closed by 1ucian0** 2018-11-15 01:00 UTC
Labels: status: confirmed, status: pending PR

**Comment by vaibhavsingh1993** [comment] 2019-06-30 12:52
> The link to the invitation without expiration is:
> 
> https://join.slack.com/t/qiskit/shared_invite/enQtNDc2NjUzMjE4Mzc0LTMwZmE0YTM4ZThiNGJmODkzN2Y2NTNlMDIwYWNjYzA2ZmM1YTRlZGQ3OGM0NjcwMjZkZGE0MTA4MGQ1ZTVmYzk

Seems like the link is dead again :(

**Comment by shahzebanwar** [comment] 2020-11-01 19:29
Do we have an active link to join the channel?

**Comment by 1ucian0** [comment] 2020-11-01 23:29
This one should be always updated 
https://ibm.co/joinqiskitslack

**Comment by wzhu8** [comment] 2020-12-26 21:59
:( inactive again

**Comment by 1ucian0** [comment] 2020-12-27 20:45
Fixed! Thanks for let us know!

**Comment by tysm** [comment] 2021-02-27 16:03
Hi, the links I've found are expired as well, would you provide a valid one?

**Comment by pratapwarrohit13** [comment] 2021-04-02 16:01
@1ucian0 slack link is dead again

**Comment by 1ucian0** [comment] 2021-04-02 19:47
it does work to me @pratapwarrohit13 . Do you mind checking again?

**Comment by pratapwarrohit13** [comment] 2021-04-03 08:50
> it does work to me @pratapwarrohit13 . Do you mind checking again?

Thanks @1ucian0 its working

**Comment by jamesphysics** [comment] 2021-06-07 13:27
@1ucian0 It seems to be dead again

**Comment by johnlager** [comment] 2021-08-15 18:30
Hi, do you guys have a valid invitation link?

**Comment by MajorCarrot** [comment] 2021-11-02 19:31
Hi, the link seems to be dead again (on all platforms). Can this be fixed? Thanks!

**Comment by lerongil** [comment] 2021-11-02 20:13
This is fixed. See this link: https://ibm.co/joinqiskitslack

**Comment by MajorCarrot** [comment] 2021-11-03 16:36
Thanks. It is working now!

**Comment by rtindru** [comment] 2022-05-06 18:35
None of these links are working anymore :(

**Comment by jakelishman** [comment] 2022-05-17 16:04
Is https://ibm.co/joinqiskitslack working again?  I believe @lerongil just refreshed its sign-up limit a few days ago.

(There's an unfortunate limit from Slack itself that causes the link to die after some number of registrations have occurred through it, and we have to generate a new invitation.)

**Comment by ju619** [comment] 2022-05-18 12:12
Perfect thanks it's working now, i'm in!

**Comment by Fation2070** [comment] 2022-06-02 08:18
@lerongil can you help me?

**Comment by fvelazquez-X** [comment] 2022-06-02 10:17
In the Qiskit Advocate 2022 form they provide a link to have an slack but is dead. Can somebody help a bit on this?

**Comment by jakelishman** [comment] 2022-06-06 12:44
The links should have been refreshed again.  We're still unfortunately limited by Slack, which deactivates a link once 100 people have used it to sign up.  Please keep commenting here if the links die again, and we'll get them refreshed.

**Comment by Harrison-Z1000** [comment] 2022-06-17 22:38
> This one should be always updated https://ibm.co/joinqiskitslack

This link worked for me. Thank you!!

**Comment by r-taeja** [comment] 2022-06-24 05:11
> This one should be always updated
> https://ibm.co/joinqiskitslack

Hey again! This link is working now. Thank you so much!

**Comment by kibrahim757** [comment] 2022-07-02 19:07
Hi , it seems that the link is down again , can you refresh it ? @jakelishman , @lerongil , Thanks

**Comment by kibrahim757** [comment] 2022-07-05 05:47
it is working now , thanks

**Comment by ianmcloughlin** [comment] 2023-01-28 10:47
Can you please refresh the link once again again?
Many thanks.

**Comment by jakelishman** [comment] 2023-01-31 16:25
Sorry for the delay - should be updated again now.

**Comment by HuangJunye** [comment] 2023-03-06 10:50
For future reference, we have switched the link, please use https://qisk.it/join-slack in the future.

**Comment by Shurtu-gal** [comment] 2023-06-23 10:46
![image](https://github.com/Qiskit/qiskit-terra/assets/100484401/cfb15dcd-ea7d-4664-971d-5a881985711b)
Not working @HuangJunye

**Comment by jakelishman** [comment] 2023-06-23 10:51
@Shurtu-gal: I've just updated it, thanks.  It could take up to a couple of hours to propagate - let us know if it doesn't work after that.

**Comment by Shurtu-gal** [comment] 2023-06-23 12:07
Yeah, it's working now. Thanks.

**Comment by sameerarora1** [comment] 2024-02-05 02:35
Hey, I've tried the Slack invites at the following webpages, but they're all inactive: 
- https://qisk.it/join-slack
- https://ibm.co/joinqiskitslack
- https://www.ibm.com/quantum/qiskit

Can anyone send an active one? Or possibly redirect me towards an active one? 
Thank you!

**Comment by jakelishman** [comment] 2024-02-05 11:38
Hi there - sorry about that, the Slack link had expired and I'd lost the notification telling me to remake it.  https://qisk.it/join-slack should be working again now (may take an hour or two for the redirect to fully propagate).

**Comment by sameerarora1** [comment] 2024-02-06 04:45
No worries, thank you!
