### ISSUE TITLE
Circuit parameters do not respect insertion order

### ISSUE THREAD

**Issue by HwajungKang** [Qiskit/qiskit-terra#7859] opened 2022-04-01 14:51 UTC
### Environment

- **Qiskit Terra version**:  0.19.2
- **Python version**: 3.7.7
- **Operating system**: OSX

### What is happening?

Parameters are not implemented on a parametrized circuit in the order defined by a user, but alphabetically. The circuit diagram shows the insertion order, but binding parameters is not done in the same order. 

### How can we reproduce the issue?

In the following example, I want to assign value [1, 2, 3] to [theta, gamma, lam].
The circuit diagram shows the order I defined, .i.e. theta, gamma , lam but the values are assigned in the alphabetical order rather than the insertion order, therefore, the parameters get wrong values. 

```python
param_keys = Parameter('theta'), Parameter('gamma'), Parameter('lam') 

ansatz = QuantumCircuit(1)
ansatz.u(*(param_keys), 0)
print(ansatz)

param_vals = np.array([1, 2, 3])
qc = ansatz.assign_parameters(param_vals)
print(qc)
```

```
   ┌────────────────────┐
q: ┤ U(theta,gamma,lam) ├
   └────────────────────┘
   ┌──────────┐
q: ┤ U(3,1,2) ├
   └──────────┘
```

### What should happen?

The list of the parameters should be bound in the order that is given by a user.

**Comment by jakelishman** [comment] 2022-04-01 15:06
This is the documented behaviour of `QuantumCircuit.assign_parameters`:
```text
Assign parameters to new parameters or values.

The keys of the parameter dictionary must be Parameter instances in the current circuit. The
values of the dictionary can either be numeric values or new parameter objects.
The values can be assigned to the current circuit object or to a copy of it.

Args:
    parameters (dict or iterable): Either a dictionary or iterable specifying the new
        parameter values. If a dict, it specifies the mapping from ``current_parameter`` to
        ``new_parameter``, where ``new_parameter`` can be a new parameter object or a
        numeric value. If an iterable, the elements are assigned to the existing parameters
        in the order of ``QuantumCircuit.parameters``.
```

The order matches `QuantumCircuit.parameters`, which is alphabetical with the exception that elements of a `ParameterVector` are numerically sequential.  I'm fairly sure we have downstream algorithms/applications code that depends on this order being maintained, so this is likely a can't/won't fix.

**Comment by HwajungKang** [comment] 2022-04-01 16:26
Thank you for the reply @jakelishman. But shouldn't at least circuit diagram show the order that is actually used? The figure totally misleads how the parameters are bound.

**Comment by jakelishman** [comment] 2022-04-01 16:33
The circuit diagram is showing how they're used; when you bind with an iterable as opposed to a dictionary, the parameters are (by design) bound in alphabetical order.  In your case, you can do something like:
```python
qc = ansatz.assign_parameters(dict(zip(param_keys, param_vals)))
```
which will explicitly pair each parameter with its value.

**Comment by Cryoris** [comment] 2022-04-01 16:40
We decided against sorting by insertion because then the order in which you call the gate, a seemingly random choice, would have an effect on how the array of values will be bound. That would've likely been a source of bugs in particular in the applications and implementation-wise it would be more effort since it would require book-keeping of the parameter order when ever we transpile or modify the circuit. Sorting by name is a global order which doesn't have these drawbacks 🙂

**Comment by HwajungKang** [comment] 2022-04-01 17:35
@jakelishman ahh, yes, that's right, the circuit diagram is showing the way it should. I was confused when looking at the circuit picture with the values assigned together. I know the way using dictionary but preferred the other way as it is shorter without knowing a default order would overwrite the insertion order. But now that I know that, will use dictionary. Thanks. @Cryoris Hi Julien, yeah, I understand the concern now. what you said totally makes sense. Thanks for the explanation!

**Comment by jakelishman** [comment] 2022-04-01 19:10
Thanks for the explanation Julien, and I'm glad this is all ok. I'll close the issue now, but feel free to open a new one if there are bugs in the handling.

**Closed by jakelishman** 2022-04-01 19:10 UTC
Labels: bug
