### ISSUE TITLE
Allow empty circuits in schema validation

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit-terra#2065] opened 2019-04-03 15:01 UTC
### What is the expected enhancement?

This is a repost of [an issue](https://github.com/Qiskit/qiskit-aer/issues/106) posted to aer that belongs here. It amounts to allowing an empty circuit to pass validation and be executed on a simulator (returning the trivial result), which in the case of a statevector simulator would be the initial state `|0...0>`.

From @matteoacrossi:

### What is the current behavior?
I get a `SchemaValidationError`

```python traceback
qiskit.qobj._schema_validation._SummaryValidationError: 'Original message too long to be useful: {\'qobj_id\': \'db850989-a583-4578-a0d6-8b4b275af261\', \'config\': {\'shots\': 1024, \'memory_slots\': 0, \'max_credits\': 10, \'memory\': False, \'n_qubits\': 1}, \'experiments\': [{\'instructions\': [], \'header\': {\'n_qubits\': 1, \'memory_slots\': 0, \'qubit_labels\': [[\'q0\', 0]], \'clbit_labels\': [], \'qreg_sizes\': [[\'q0\', 1]], \'creg_sizes\': [], \'name\': \'circuit0\', \'compiled_circuit_qasm\': \'OPENQASM 2.0;\\ninclude "qelib1.inc";\\nqreg q0[1];\\n\'}, \'config\': {\'memory_slots\': 0, \'n_qubits\': 1}}], \'header\': {\'backend_name\': \'statevector_simulator\'}, \'type\': \'QASM\', \'schema_version\': \'1.0.0\'} is not valid under any of the given schemas\n\nFailed validating \'oneOf\' in schema:\n    {\'$schema\': \'http://json-schema.org/draft-04/schema#\',\n     \'definitions\': {\'bfunc\': {\'properties\': {\'mask\': {\'type\': \'string\'},\n                                              \'memory\': {\'minimum\': 0,\n                                                         \'type\': \'integer\'},\n                                              \'name\': {\'enum\': [\'bf[...]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "initialize_bug.py", line 9, in <module>
    job_sim = execute(qc, backend)
  File "~/envs/quantum/lib/python3.7/site-packages/qiskit/tools/compiler.py", line 110, in execute
    return backend.run(qobj, **kwargs)
  File "~/envs/quantum/lib/python3.7/site-packages/qiskit/providers/aer/backends/aerbackend.py", line 80, in run
    aer_job.submit()
  File "~/envs/quantum/lib/python3.7/site-packages/qiskit/providers/aer/aerjob.py", line 73, in submit
    validate_qobj_against_schema(self._qobj)
  File "~/envs/quantum/lib/python3.7/site-packages/qiskit/qobj/_validation.py", line 23, in validate_qobj_against_schema
    err_msg='Qobj failed validation. '
  File "~/envs/quantum/lib/python3.7/site-packages/qiskit/qobj/_schema_validation.py", line 148, in validate_json_against_schema
    raise newerr
qiskit.qobj._schema_validation.SchemaValidationError: 'Qobj failed validation. Set Qiskit log level to DEBUG for further information.'
```

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit, QuantumRegister, execute
from qiskit.providers.aer import Aer

backend = Aer.get_backend('statevector_simulator')

q = QuantumRegister(1)
qc = QuantumCircuit(q)

job_sim = execute(qc, backend)
print(job_sim.result().get_statevector())
```

### What is the expected behavior?
```python
[1.+0.j 0.+0.j]
```

**Comment by mtreinish** [comment] 2019-04-03 15:17
This is a duplicate of #2020 and should have been fixed by #2048 so I'm closing this. If it's still an issue on current master feel free to reopen.

**Closed by mtreinish** 2019-04-03 15:17 UTC
