### ISSUE TITLE
QSphere not giving a circular shape plot

### ISSUE THREAD

**Issue by AbeerVaishnav13** [Qiskit/qiskit-terra#4905] opened 2020-08-11 05:17 UTC
### Information

- **Qiskit Terra version**: 0.14.2
- **Python version**: 3.8.5
- **Operating system**: MacOS, Windows, Linux

### What is the current behavior?
<img width="563" alt="Screenshot 2020-08-11 at 10 42 29 AM" src="https://user-images.githubusercontent.com/30632765/89859866-9f88ca80-dbbf-11ea-8ea1-bfb25e9d8d36.png">

### Steps to reproduce the problem
```
from qiskit.visualization import plot_state_qsphere
from qiskit.quantum_info import Statevector

sv = Statevector.from_label('0')

plot_state_qsphere(sv.data)
```
### What is the expected behavior?
The Qsphere should have a circular (or spherical, whichever way you want to see it as) shape. The shape is oval. This happened when I updated my qiskit-terra version recently.

### Suggested solutions
I think there's some issue with the plotting about the vertical axis. Please look into the matter.

**Comment by e-eight** [comment] 2020-08-11 18:30
Duplicate of #4770. Submitted pull request #4893 to fix it.

**Closed** 2020-09-26 00:45 UTC
Labels: bug
