### ISSUE TITLE
circuit without gates cannot be drew on latex

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#5025] opened 2020-09-03 21:03 UTC
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.7
- **Operating system**: MacOS

### Steps to reproduce the problem
```python
from qiskit import *
qc = QuantumCircuit(2)
qc.draw('latex')
```
```
IndexError: list index out of range
```

### What is the expected behavior?

Same as other drawers:
```python 
qc.draw('text')
```
```
q_0: 
     
q_1: 
```

```python
qc.draw('mpl')
```
![image](https://user-images.githubusercontent.com/766693/92166787-36375880-ee07-11ea-95ad-fef23f88e2fc.png)

**Comment by mlarocca** [comment] 2020-09-04 12:17
@1ucian0 Maybe I can help with this, would that be ok?

**Comment by 1ucian0** [comment] 2020-09-04 12:18
Sure! Thanks!

**Comment by mlarocca** [comment] 2020-09-04 13:41
Perfect, I'll start taking a look later today.
Thanks!

**Comment by mtreinish** [comment] 2020-09-04 14:10
Fwiw, this used to work fine. It looks this was a regression introduced in: https://github.com/Qiskit/qiskit-terra/pull/4410

**Comment by mlarocca** [comment] 2020-09-06 17:48
Yeah, the issue seems to be that "self.ops" is empty, but it's first element is checked in `if self.cregbundle and self.ops[0][0].name == "measure"`
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/visualization/latex.py#L302

Now, if I have understood correctly, self.ops is the list of layers in the circuit: @1ucian0 is it supposed to be empty for a QuantumCircuit?
I noticed in text.py it's handled differently (called instructions there, but still, if I'm not mistaken...), so my guess is that it's OK and it's fine just making sure the list isn't empty, is that right?

**Comment by 1ucian0** [comment] 2020-09-06 17:55
Sounds good to me. Let's discuss it in a PR 😊

**Closed** 2020-09-08 20:27 UTC
Labels: bug, good first issue
