### ISSUE TITLE
Aer simulator fails to work with custom parametrized circuits and VQE

### ISSUE THREAD

**Issue by GaidaiIgor** [Qiskit/qiskit-terra#10589] opened 2023-08-08 00:21 UTC
### Informations

- **Qiskit Aer version**: 0.12.2
- **Python version**: 3.11.3
- **Operating system**: Windows 10

### What is the current behavior?
When I try to execute the code below, I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\extensions\hamiltonian_gate.py", line 90, in __array__
    return scipy.linalg.expm(-1j * self.params[0] * float(self.params[1]))
                                                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\circuit\parameterexpression.py", line 480, in __float__
    raise TypeError(
TypeError: ParameterExpression with unbound parameters ({ParameterVectorElement(angles[0])}) cannot be cast to a float.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\transpiler\passes\basis\unroll_custom_definitions.py", line 88, in run
    unrolled = getattr(node.op, "definition", None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\circuit\instruction.py", line 239, in definition
    self._define()
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\extensions\hamiltonian_gate.py", line 117, in _define
    qc._append(UnitaryGate(self.to_matrix()), q[:], [])
                           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\circuit\gate.py", line 53, in to_matrix
    return self.__array__(dtype=complex)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\extensions\hamiltonian_gate.py", line 92, in __array__
    raise TypeError(
TypeError: Unable to generate Unitary matrix for unbound t parameter angles[0]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit_algorithms\minimum_eigensolvers\vqe.py", line 254, in evaluate_energy
    estimator_result = job.result()
                       ^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\primitives\primitive_job.py", line 55, in result
    return self._future.result()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit_aer\primitives\estimator.py", line 128, in _call
    return self._compute(circuits, observables, parameter_values, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit_aer\primitives\estimator.py", line 188, in _compute
    self._transpile_circuits(circuits)
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit_aer\primitives\estimator.py", line 481, in _transpile_circuits
    circuit = self._transpile(circuit)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit_aer\primitives\estimator.py", line 468, in _transpile
    return transpile(circuits, self._backend, **self._transpile_options.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\compiler\transpiler.py", line 418, in transpile
    out_circuits = pm.run(circuits, callback=callback)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\transpiler\passmanager.py", line 537, in run
    return super().run(circuits, output_name, callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\transpiler\passmanager.py", line 233, in run
    return [self._run_single_circuit(circuits[0], output_name, callback)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\transpiler\passmanager.py", line 292, in _run_single_circuit
    result = running_passmanager.run(circuit, output_name=output_name, callback=callback)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\transpiler\runningpassmanager.py", line 125, in run
    dag = self._do_pass(pass_, dag, passset.options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\transpiler\runningpassmanager.py", line 173, in _do_pass
    dag = self._run_this_pass(pass_, dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\transpiler\runningpassmanager.py", line 202, in _run_this_pass
    new_dag = pass_.run(dag)
              ^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit\transpiler\passes\basis\unroll_custom_definitions.py", line 90, in run
    raise QiskitError(f"Error decomposing node {node.name}: {err}") from err
qiskit.exceptions.QiskitError: 'Error decomposing node hamiltonian: Unable to generate Unitary matrix for unbound t parameter angles[0]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\MA-QAOA\temp\my_test.py", line 29, in <module>
    test_vqe()
  File "C:\Users\User\Desktop\MA-QAOA\temp\my_test.py", line 25, in test_vqe
    result = vqe.compute_minimum_eigenvalue(-hamiltonian)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit_algorithms\minimum_eigensolvers\vqe.py", line 183, in compute_minimum_eigenvalue
    optimizer_result = self.optimizer(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\scipy\optimize\_minimize.py", line 710, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\scipy\optimize\_lbfgsb_py.py", line 307, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\scipy\optimize\_optimize.py", line 383, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\scipy\optimize\_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\scipy\optimize\_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\scipy\optimize\_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\scipy\optimize\_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\python3.11_venv\Lib\site-packages\qiskit_algorithms\minimum_eigensolvers\vqe.py", line 256, in evaluate_energy
    raise AlgorithmError("The primitive job to evaluate the energy failed!") from exc
qiskit_algorithms.exceptions.AlgorithmError: 'The primitive job to evaluate the energy failed!'
```

Apparently, parametrized Hamiltonian gates fail to convert to unitaries when `AerEstimator` is used. However, if `qiskit.primitives.Estimator` is used instead, then everything works as expected. As far as I understand, one should be able to use these estimators interchangeably.

### Steps to reproduce the problem
The following code reproduces the problem:
```
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector
from qiskit.primitives import Estimator
from qiskit_aer.primitives import Estimator as AerEstimator
from qiskit.quantum_info import SparsePauliOp, Pauli
from qiskit_algorithms.minimum_eigensolvers import VQE
from scipy import optimize


def get_custom_ansatz(num_qubits: int) -> QuantumCircuit:
    params = ParameterVector('angles', num_qubits)
    circuit = QuantumCircuit(num_qubits)
    for i in range(num_qubits):
        circuit.hamiltonian(Pauli('X'), params[i], [i])
    return circuit


def test_vqe():
    n = 12
    estimator = AerEstimator()  # Estimator() works
    hamiltonian = SparsePauliOp.from_sparse_list([('ZZ', [0, 1], -1)], n)
    ansatz = get_custom_ansatz(n)
    optimizer = optimize.minimize
    vqe = VQE(estimator, ansatz, optimizer)
    result = vqe.compute_minimum_eigenvalue(-hamiltonian)
    return -result.eigenvalue.real


test_vqe()
```

### What is the expected behavior?
I expect no errors.

**Comment by ikkoham** [comment] 2023-08-08 17:13
Thanks. As @mtreinish transferred, this is the transpilation issue.

minimal code to reproduce this is

```python
from qiskit import QuantumCircuit, transpile
from qiskit.circuit import ParameterVector
from qiskit_aer import AerSimulator


def get_custom_ansatz(num_qubits: int) -> QuantumCircuit:
    params = ParameterVector('angles', num_qubits)
    circuit = QuantumCircuit(num_qubits)
    for i in range(num_qubits):
        circuit.hamiltonian(Pauli('X'), params[i], [i])
    return circuit


transpile(get_custom_ansatz(n), AerSimulator())
```

**Comment by mtreinish** [comment] 2023-08-08 20:35
It's actually more of an issue with the implementation of the [`HamiltonianGate`](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/extensions/hamiltonian_gate.py), it is raising errors when there is an unbound parameter when the transpiler is asking for it's definition to unroll it into terms that can be used for basis translation. There isn't a way to transpile it directly with an unbound parameter because it's definition can only be realized with a numeric parameter for `time` because the definition just returns a unitary gate, and we can't define the matrix without a numerical value for `time`.

**Comment by Cryoris** [comment] 2023-08-15 07:55
Yeah this only work with the `Estimator` in Qiskit (Terra) as it binds the parameter values before simulating the circuit.

If you'd like to use operator evolutions with the Aer Estimator, you can use the `PauliEvolutionGate` instead of the `QuantumCircuit.hamiltonian` function. The `PauliEvolutionGate` implements a Trotter expansion, so it is not exact, but this is what we would also have to run on a quantum computer. 

I'll go ahead and close this issue, but feel free to re-open if the answers above didn't answer your question.

**Closed by Cryoris** 2023-08-15 07:55 UTC
Labels: bug
