### ISSUE TITLE
Latex drawer does not print the qubit name

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-terra#2778] opened 2019-07-12 18:13 UTC
### Information

- **Qiskit Terra version**: master
- **Python version**: 3.5
- **Operating system**: macos

### What is the current behavior?
<img width="621" alt="Screen Shot 2019-07-12 at 2 11 13 PM" src="https://user-images.githubusercontent.com/766693/61149354-ee40ce00-a4ae-11e9-8e1b-915bbec88295.png">

### Steps to reproduce the problem

```python
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
qr = QuantumRegister(4, 'qr')
circuit = QuantumCircuit(qr)
circuit.h(qr)
circuit.h(qr)
circuit.draw(output='latex')
```
Notice that the following works
```python
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
qr = QuantumRegister(4, 'qr')
circuit = QuantumCircuit(qr)
circuit.h(qr)
circuit.draw(output='latex')
```
<img width="407" alt="Screen Shot 2019-07-12 at 2 12 48 PM" src="https://user-images.githubusercontent.com/766693/61149432-27793e00-a4af-11e9-855f-9b539da7c487.png">

### What is the expected behavior?

I would like to see the qubit name in the beginning of the circuit, always.

**Comment by mtreinish** [comment] 2019-07-22 08:21
I think this is also fixed by: #2840 From what I can tell the name is getting clipped in the first example with 2 gates for the same reason as in #2780, we're not factoring the register name length into the depth calculation. Running your example circuit with #2840 applied fixes it locally for me. That being said I feel like both of these bugs are recent regressions, because I don't remember this behavior before (especially this one which is pretty bad), I'm assuming it was #1977, but I'll bisect to be sure.

**Closed** 2019-08-02 13:45 UTC
Labels: bug
