### ISSUE TITLE
Bug when drawing circuits containing barriers

### ISSUE THREAD

**Issue by maddy-tod** [Qiskit/qiskit-terra#1306] opened 2018-11-20 15:30 UTC
### Informations

- **Qiskit Terra version**:0.6.1
- **Python version**: 3.6.5
- **Operating system**:  macOS

### What is the current behaviour?
When attempting to draw some circuits which contain barriers using the circuit drawer, an error is produced.

### Steps to reproduce the problem
```q = QuantumRegister(2)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)


qc.h(q[0])
qc.barrier()
qc.h(q[1])
qc.barrier()
qc.measure(q, c)

img = circuit_drawer(qc)
```
Should produce the error `"Error during Latex building: invalid literal for int() with base 10: '1} \\\\barrier{1'"` .

It may be worth noting some other circuits, such as the one below, do not have the same issue and they circuits can be drawn.

```
qc.h(q[0])
qc.barrier()
qc.x(q[1])
qc.barrier(q)
qc.h(q[1])
qc.barrier()
qc.measure(q, c)

img = circuit_drawer(qc)
```

**Comment by mtreinish** [comment] 2018-11-26 17:56
So the underlying issue here is that the drawer is trying to draw 2 barriers next to each other the on the q[0] bit line in the same column of the qcircuit xymatrix. This is breaking the regex used on measure when looking for a \barrier{} string to adjust the spacing for the measure box: https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/tools/visualization/_latex.py#L972 so instead of returning the string `1` it's returning the string `'1} \\barrier{1` While I can try fix the regex so it doesn't fail on this the output circuit won't be right because it'll look something like:

![test-2](https://user-images.githubusercontent.com/2447371/49032122-cdbf4000-f179-11e8-85d2-6c2fef73f75f.png)

because we'll be drawing 2 barrier lines right on top of each other.

Instead of the desired:

![test-3](https://user-images.githubusercontent.com/2447371/49032400-6655c000-f17a-11e8-9354-a338f113803e.png)

This means that this is actually a duplicate of #1124 which is about things not being spaced properly when there is a barrier. So I'm closing this issue so we can track the fix there.

**Closed by mtreinish** 2018-11-26 17:56 UTC
Labels: type: bug
